# Reviews {.unnumbered}

> 'Ik had al enige tijd het vermoeden dat Van Wirdum de beste historicus van Bitcoin is, en dit boek bevestigt dat.
> 
> Het is een indrukwekkend werk. Het Genesisboek biedt een toegankelijk en essentieel overzicht van de geschiedenis, en onthult de vele verbanden tussen het Weense klassiek-liberalisme, de Anglo-Saksische Cypherpunkbeweging en de opkomst van Bitcoin.
> 
> Waar andere boeken in de branche vaak de nadruk leggen op veelgeprezen ondernemers, heeft Van Wirdum de technische kennis om belangrijke figuren te belichten die de fundamenten legden waarop het Bitcoin-gebouw later is opgericht.
> 
> In zestien informatieve hoofdstukken biedt Het Genesisboek een combinatie van diepgaand onderzoek en filosofische inzichten die je alleen verwacht van een veteraan in de sector (Van Wirdum was een van de eerste schrijvers die in de Bitcoin-industrie aan de slag ging), met de aantrekkelijke schrijfstijl die je zoekt in een gerespecteerd tijdschrift.
> 
> Je kunt Bitcoin niet begrijpen zonder kennis te maken met zijn bijzondere oorsprong, en ik ben blij dat dit boek bestaat om die kennis voor een breed publiek toegankelijk te maken.'
> 
> **— Tuur Demeester**

> 'Het Genesisboek neemt je mee op een eeuwenlange reis door minder bekende verhalen van visionairs, wiens inzichten en innovaties de basis vormden voor de revolutionaire creatie van Bitcoin. Van economen die de gevestigde orde uitdaagden tot Cypherpunks die nieuwe wegen op het gebied van privacy verkenden, weeft Aaron van Wirdum zorgvuldig een verhaal over technologische overwinningen, tegenslagen en bijzondere doorbraken. De anekdotes over mensen die buiten de gebaande paden durfden te dromen en grenzen verlegden om de financiële wereld te veranderen, zullen je zeker fascineren.'
> 
> **— Jameson Lopp**

> 'Waarom verschilt Bitcoin zo van eerdere versies? Dit boek werpt licht op de *problemen* die slimme en hardwerkende mensen in de tijd vóór Bitcoin bezig hielden. Dit is de juiste manier om het verhaal van een technologie te vertellen. Alle belangrijke kwesties worden behandeld en zijn in een logische volgorde gepresenteerd. Dit is het beste boek dat ooit over Bitcoin geschreven is.'
> 
> **— Paul Sztorc**

> 'Tot nu toe waren er veel boeken over Bitcoin, maar geen enkel boek pakte de veelzijdige culturele achtergrond zo compleet, gestructureerd en elegant aan. Aaron van Wirdum, bekend om zijn talent om technische materie helder naar een breder publiek over te brengen, heeft dat nu gedaan. Dit is een *must-read* als je wilt begrijpen waar Bitcoin vandaan komt.'
> 
> **— Giacomo Zucco**
