# Spontane orde

Net als zijn vader wilde Friedrich August von Hayek hoogleraar in de biologie worden, maar de Eerste Wereldoorlog veranderde zijn levenspad volledig.[^8] Hij werd geboren in 1899 en groeide op tijdens de laatste jaren van het Oostenrijks-Hongaarse Rijk. Op zijn achtiende verjaardag werd hij opgeroepen om te vechten aan het Italiaanse front. Het laatste deel van de oorlog bracht hij door als waarnemer in vliegtuigen.

Toen hij in 1918 na het einde van de oorlog thuis kwam, vond Hayek (het aristocratische voorvoegsel *von* werd na de ineenstorting van de dubbele monarchie weggelaten) zijn woonplaats Wenen in totale verwoesting terug. De oorlog was verloren, de economie vernietigd en het rijk was niet meer. Het moreel in de stad was gebroken.

Erger nog, de nieuwe Oostenrijkse regering spendeerde zoveel om de naoorlogse kosten te dekken dat de waarde van hun nationale munteenheid enorm kelderde. Hoewel de krone tijdens de oorlog al meer dan 90 procent van zijn koopkracht had verloren, liep dit in de naoorlogse jaren pas echt uit de hand. Terwijl een Amerikaanse dollar voor ongeveer negen kronen verkocht werd in 1917, kon diezelfde dollar tegen 1923 meer dan 70.000 van de Oostenrijkse munteenheden opbrengen. Het nationale geld was in feite vernietigd.[^9]

Nadat hij van dichtbij geconfronteerd was met de verschrikkingen van de Grote Oorlog, waarin bijna achttien miljoen mannen en vrouwen het leven lieten, besloot Hayek om zijn tijd en energie te besteden aan het proberen te voorkomen van een herhaling van dergelijke dramatische conflicten in de toekomst. Hij was vastberaden om betere manieren te vinden om de maatschappij te organiseren.

Als leergierig persoon uit een hoogopgeleid gezin -- beide grootvaders van hem waren ook academici -- schreef Hayek zich in aan de Universiteit van Wenen, de oudste universiteit in de Duitstalige wereld en een van de meest gerenommeerde academische instituten in heel Europa. Gemotiveerd door zijn nieuwe missie, koos Hayek ervoor om politieke wetenschappen en recht te studeren, terwijl hij naast zijn hoofdstudies ook lessen in filosofie, psychologie en economie volgde.

Hij schreef zich niet meteen in voor alle economielessen. Voor de socialistisch-geïnspireerde Hayek leek de economieprofessor aan de universiteit een beetje te hard te denken vanuit vrijemarktprincipes. Pas toen diezelfde economieprofessor Hayek in dienst nam om een tijdelijk overheidskantoor in de stad te bemannen, besloot hij eindelijk zijn lessen een kans te geven.[^10]

De naam van de professor was Ludwig von Mises. Hayek kwam al snel te weten dat Mises een vooraanstaand econoom was binnen een relatief nieuwe school van economisch denken.[^11]

## Oostenrijkse economie

De Eerste Wereldoorlog was het gewelddadige hoogtepunt van een tijdperk dat sterk doordrenkt was van nationalisme, de ideologie die stelt dat collectieven van mensen met een gemeenschappelijke herkomst, geschiedenis, cultuur of taal --- *naties* --- zichzelf als staten moesten organiseren en handelen in het belang van deze staten.

Het nationalisme had in de negentiende eeuw ook invloed op de economische wetenschap. Waar de *klassieke economie*, met haar sterke nadruk op vrije markten zoals voorgesteld door baanbrekende economen zoals David Hume, Adam Smith, en David Ricardo, dominant was in de late achttiende eeuw, begonnen Europese universiteiten gedurende de jaren 1800 de methoden van de *historische school van economie* te omarmen. De meest invloedrijke experts pleitten voor staatsinterventies in de economie, zoals arbeidswetten, beschermde heffingen, en progressieve belastingen.[^12]

De methodologie van de historische economische school -- de verzameling methoden die gebruikt worden om de economie te bestuderen -- sloot algemene economische theorieën uit en stelde dat de *regels* waaraan economieën voldoen verschillen per cultuur en tijd. In tegenstelling tot het opstellen van modellen of theorema's, verzamelden historische economen grote hoeveelheden historische data voor empirische analyse.

Maar professor Carl Menger van de Universiteit van Wenen had deze aanpak in de jaren 1870 al afgewezen. Hij geloofde dat mensen en menselijke interacties te complex waren om enkel op basis van empirische gegevens waardevolle wetenschappelijke inzichten te kunnen afleiden. Een ontelbare hoeveelheid factoren beïnvloedt de gedachten en acties van een typisch persoon, redeneerde hij --- het is onbegonnen werk om het aantal factoren die een hele samenleving beïnvloeden te bestuderen. Geen enkele hoeveelheid empirische data zou groot genoeg zijn om al deze factoren te omvatten, geloofde Menger. Elke conclusie die uit zo'n dataset wordt getrokken, zou nooit overtuigend zijn.

In plaats daarvan betoogde Menger dat economen moesten proberen om economische verschijnselen te begrijpen en uit te leggen door deductieve redenering. Door te beginnen met basisprincipes, kon logisch redeneren leiden tot onweerlegbare inzichten die het wetenschappelijke begrip van economische processen *a priori* uitbreidden (de Latijnse term *a priori* verwijst naar kennis die onafhankelijk is van ervaring, zoals wiskunde, in tegenstelling tot *a posteriori* kennis die afhankelijk is van empirisch bewijs, zoals meer typisch is in de meeste andere wetenschappelijke vakgebieden).

Menger bracht deze aanpak in de praktijk in zijn boek uit 1871 getiteld *Grundsätze der Volkswirtschaftslehre*. Hierin schetste hij de theorie van het marginale nut, die stelt dat de prijs van goederen en diensten deels afhangt van hoeveel extra voldoening men krijgt door er meer van te hebben.[^13]

Het boek en de methode van Menger betekende een fundamentele verschuiving in denkwijze. Tot dan toe hadden economen, zowel uit de klassieke als uit de historische school, altijd aangenomen dat de waarde van een product werd afgeleid van zijn productiekosten. Zij stelden dat een paar schoenen waardevol is omdat de productie ervan kosten met zich meebrengt --- met name de kosten van arbeid, leer en benodigdheden. De reden dat het leer en de benodigdheden kosten met zich meebrengen, is op hun beurt omdat het produceren van het leer en de benodigdheden eveneens arbeid vereist (en mogelijk ook andere kosten). Dit werd de arbeidswaardetheorie genoemd.

Volgens de theorie van het marginale nut, stelde Menger dat waarde subjectief is: individuen waarderen producten en diensten als deze een persoonlijke behoefte of verlangen vervullen. De waarde van een paar schoenen komt niet voort uit de productiekosten, maar uit het feit dat *mensen het dragen van schoenen waarderen*.

Dit betekent dat de waarde van een bepaald product kan variëren van persoon tot persoon. Iemand die helemaal geen schoenen heeft, zal een nieuw paar waarschijnlijk meer waarderen dan iemand die al meerdere paren bezit. Op dezelfde manier kan *dezelfde* persoon hetzelfde product op verschillende tijdstippen anders waarderen. Nadat de persoon zonder schoenen in het vorige voorbeeld een paar heeft verworven, waardeert hij waarschijnlijk een tweede, identiek paar schoenen niet even hoog als het eerste.[^14]

Met deze *subjectieve theorie van waarde*, plaatste Menger het individu opnieuw in het centrum van de economie. Hij stelde dat niet landen of andere collectieven de drijvende kracht waren achter economische beslissingen, maar mensen en hun subjectieve voorkeuren. In plaats van de staat als uitgangspunt te nemen voor analyse, geloofde Menger dus dat de studie van economie moest beginnen door te begrijpen wat de kleinste onderdelen van elk economisch systeem beïnvloedt. Precies, de individuen.

Met zijn benadering, wellicht het best beschreven als een herleving van de klassieke economie gericht op individuele subjectieve ervaring, won Carl Menger de steun van verschillende van zijn collega's aan de Universiteit van Wenen. Door de publicatie in de jaren 1880 van zijn tweede boek,[^15] had Menger een filosofisch debat aangewakkerd over de methodologie van de economische wetenschap binnen Duitstalige universiteiten.

Tijdens deze soms vijandige *Methodenstreit*, begonnen Duitse economen -- die sterk neigden naar de historische school -- ietwat minachtend naar Mengers aanpak te verwijzen als de 'Oostenrijkse school van economie'. Hoewel oorspronkelijk bedoeld als een sneer (in die tijd associeerden de Duitsers het predicaat *Oostenrijks* met het verlies van Oostenrijk in de Oostenrijks-Pruisische oorlog van 1866), bleef de naam in gebruik. Economen die Mengers methodologie aannamen, werden sindsdien aangeduid als Oostenrijkse economen, zelfs wanneer ze niet uit Oostenrijk afkomstig waren.[^16]

De vijandige sfeer tijdens de methodenstrijd in de late negentiende eeuw bereikte zijn hoogtepunt met de *de facto* verbanning van de Oostenrijkse economie uit Duitse universiteiten. De boycott bleef decennia van kracht, en verhinderdde in grote mate dat Mengers ideeën zich door de nieuwe, verenigde natiestaat verspreidden. In plaats daarvan bleef het nationalisme domineren, terwijl een andere collectivistische ideologie zich zonder veel wezenlijk tegengas ook begon te verspreiden doorheen de Duitse universiteiten: het socialisme was in opkomst.

## Economische berekening

Oorspronkelijk gepopulariseerd door de Duitse auteur en sociale commentator Karl Marx, geloofden socialisten dat de economische geschiedenis van de wereld het best begrepen wordt als een klassenstrijd tussen degenen die kapitaal bezitten (goederen die kunnen worden gebruikt als productiemiddel, zoals fabrieken en hun machines) en de arbeidersklasse, die alleen hun arbeid te verkopen hebben. Marx voorspelde dat deze strijd in het voordeel van de kapitaalbezittende klasse (de *kapitalisten*) moest uitdraaien, omdat ze steeds meer kapitaal en eindeloos groeiende winsten zouden genieten, totdat de arbeidersklasse (het proletariaat) onvermijdelijk in opstand kwam.

Volgens Marx was het socialisme de uiteindelijke oplossing voor economische ongelijkheid: een economisch systeem waarin de productiemiddelen onder gemeenschappelijk eigendom gebracht worden en hun opbrengsten over de hele samenleving worden verdeeld. Dit moest in eerste instantie onder toezicht van de staat gebeuren, om geleidelijk aan vervangen te worden door een anarchistische vorm van zelfbestuur.

Hoewel de ideeën van Marx pas echt populair leken te worden na zijn dood in 1883, hadden ze ook een behoorlijk aantal critici. Een vaak gehoord bezwaar was dat mensen in een socialistisch systeem geen stimulans zouden hebben om te werken, aangezien ze toch een vast aandeel van alle geproduceerde goederen ontvingen, terwijl de goederen die ze zelf hielpen te maken, verspreid werden over de rest van de samenleving. Een tweede bezwaar was het risico dat socialistische leiders zich tegen hun eigen bevolking zouden keren en veel van de onder staatsbeheer geproduceerde goederen voor zichzelf zouden opeisen, in plaats van ze eerlijk te verdelen.

Desondanks heeft het de opkomst van de socialistische leer in het Russische Rijk niet gestopt. In 1917, midden in de Eerste Wereldoorlog, wierpen revolutionairen, georganiseerd via arbeidersraden bekend als 'Soviets', de zittende regering omver en richtten de Sovjet-Unie op als een communistische staat.

Ongeveer drie jaar na deze gebeurtenissen bracht Mises, de professor die Hayek zijn overheidsbaan had aangeboden, een baanbrekende nieuwe kritiek op het socialisme.[^17] Belangrijk om te vermelden, is dat deze kritiek standhield *zelfs* als mensen gemotiveerd waren om te werken, en *zelfs* als socialistische leiders zich inzetten voor een eerlijke verdeling van de economische winsten. Mises beweerde echter dat het fundamentele probleem van het socialisme het ontbreken van een direct feedbackmechanisme was om producenten te informeren of ze überhaupt waarde toevoegden aan de samenleving.

Laten we een autofabriek nemen om dit argument te illustreren. In een vrije markt voegt een fabriek die auto's produceert en winst maakt duidelijk waarde toe aan de maatschappij: mensen zijn bereid meer te betalen voor auto's dan de fabriek moet betalen voor de benodigde hulpbronnen -- staal, machines, arbeidskrachten -- om ze te produceren. Winst wijst erop dat de productie van de fabriek meer wordt gewaardeerd dan de input.

Een autofabriek die verlies draait daarentegen, voegt duidelijk geen waarde toe aan de maatschappij, aangezien mensen de gebruikte middelen meer waarderen dan het eindproduct. Uiteindelijk zal zo'n fabriek de deuren moeten sluiten. De middelen die de fabriek gebruikte, kunnen nu worden gekocht (of in het geval van arbeid, ingehuurd) door winstgevendere bedrijven om beter ingezet te worden (de Oostenrijkse econoom Joseph Schumpeter zou dit later *creatieve destructie* noemen).

In een socialistische samenleving zou een staatsgeleide autofabriek op bevel van een centrale planner auto's produceren. Wanneer de auto's op bevel geproduceerd worden, is er geen terugkoppeling van de maatschappij in de vorm van winst of verlies. De autofabriek kan mogelijk middelen verspillen aan het maken van auto's die mensen niet waarderen, of niet zo hoog waarderen als andere producten die gemaakt hadden kunnen worden met dezelfde middelen.

Zonder vrije markt is er geen *economische berekening* mogelijk, wat de fundamentele taak van ieder economisch systeem onmogelijk maakt: de efficiënte verdeling van schaarse middelen over de samenleving.[^18]

'Zonder economische berekening kan er geen economie zijn', concludeerde Mises. 'Daarom kan er in een socialistische staat, waarin het nastreven van economische berekening onmogelijk is, in onze betekenis van het woord, geen economie bestaan.'[^19]

## Prijzen

Mises, en met name zijn concept van economische berekening, zou op Hayek een grote invloed hebben. Aan de Universiteit van Wenen groeide hij uit tot een enthousiaste student van de Oostenrijkse school van economie. Hij bestudeerde de werken van Menger, evenals andere 'eerste generatie'-Oostenrijkers zoals Eugen von Böhm-Bawerk. Hij werd ook een vaste bezoeker van privé-seminaries die Mises tweemaal per maand organiseerde in zijn overheidskantoor. Daar kwam een kleine groep geleerden samen om economische theorie, filosofie en welke andere onderwerpen Mises en zijn gasten die week ook interessant vonden, te bespreken.

Mises hielp Hayek persoonlijk bij het opstarten van zijn academische carrière in de economie. In 1927, nadat hij zijn studie aan de Universiteit van Wenen had afgerond, werd Hayek benoemd tot directeur van Mises' pas opgerichte Oostenrijks Instituut voor Conjunctuuronderzoek. Dit bood de jonge econoom een perfecte omgeving om de theorie van zijn voormalige professor over economische berekening verder te ontwikkelen.

Hayek concentreerde zich met name op de functie en het effect van *prijzen*. Zoals hij in de volgende jaren zou uitleggen, zijn prijzen volgens hem de gedecentraliseerde en maatschappelijk schaalbare communicatiemiddelen van de markt.[^20] Hoewel men prijzen meestal ziet als een eenvoudige functie van vraag en aanbod van goederen en diensten binnen een economie, liet Hayek zien dat prijzen in feite een breed scala aan relevante informatie bevatten die mensen nodig hebben om economische beslissingen te nemen.

Laten we als (vereenvoudigd) voorbeeld opnieuw de autofabriek van Mises nemen. Zoals eerder genoemd, heeft deze fabriek hulpbronnen nodig zoals staal, machines en arbeid om auto's te produceren --- maar we concentreren ons voor nu alleen op staal. Stel dat deze specifieke fabrieksoperator zijn staal koopt van een staalproducent in een nabijgelegen stad. Deze staalproducent haalt op zijn beurt ijzererts uit een mijn halverwege het land. Tegelijkertijd koopt een lokale autodealer de auto's van de fabriek, in de tegenovergestelde richting van de toeleveringsketen, om ze vervolgens aan klanten te verkopen.

Iedereen in deze leveringsketen heeft de informatie die ze nodig hebben om hun eigen bedrijf uit te baten, en ze communiceren dit met alle andere marktdeelnemers door middel van prijzen.

De autohandelaar heeft een goed beeld van hoe hij auto's moet verkopen; hij weet bijvoorbeeld hoeveel vraag er is naar nieuwe auto's, en hij weet wat hij nodig heeft om ze te verkopen --- misschien een toonzaal op een gunstige locatie en wat was om de auto's er mooi en glanzend uit te laten zien. De prijzen die klanten bereid zijn te betalen voor auto's, en de prijs die hij moet betalen voor een toonzaal en was, zullen dus bepalen welke prijs hij zelf bereid is te betalen aan de autofabriek voor nieuwe auto's.

Intussen weet de staalproducent hoeveel hij moet betalen voor erts, wat zijn oven kost om het erts om te zetten in staal en wat hij aan salarissen moet uitgeven. Zolang zijn klanten, zoals de autofabriek, meer betalen voor zijn staal dan wat het hem kost om het te produceren, zal hij staal blijven produceren.

Hoewel iedereen in de toeleveringsketen van elkaar afhangt, hoeft niemand *exact* te weten hoe iemand anders zijn werk doet. De kosten van een toonzaal kunnen van invloed zijn op hoeveel de autodealer bereid is aan de fabriek te betalen voor een nieuwe auto. Maar de fabrieksmanager hoeft zich niet echt te verdiepen in de vastgoedmarkt voor toonzalen. Hij hoeft zich ook niet te buigen over de schaarste van erts. Deze informatie wordt weerspiegeld in de prijzen die de autodealer biedt voor nieuwe auto's, en de prijs die de staalproducent vraagt voor nieuw staal.

Bij uitbreiding, kunnen prijzen helpen bij de herverdeling van hulpbronnen wanneer er iets verandert in de economie.

Als de ijzerertsmijn bijvoorbeeld gedeeltelijk moet sluiten vanwege een brand, wordt het aanbod van erts kleiner, en de algehele vraag naar het overgebleven erts zal de prijs van ijzer opdrijven. De staalproducent zou dan op zijn beurt de prijs van zijn staal moeten verhogen om winstgevend te blijven. Deze verhoogde prijs voor staal communiceert eigenlijk de relevante informatie aan de autofabriek die deze nodig heeft om economische beslissingen te nemen (de autofabriek zou bijvoorbeeld kunnen besluiten staal te kopen bij een andere producent die zijn erts van een andere mijn krijgt).

Op dezelfde manier, als de consumentenvraag naar keukenapparatuur stijgt, zou de fabriek van keukenapparatuur meer staal willen kopen, waardoor de staalprijs stijgt wanneer het de autofabriek overbiedt. De staalproducent zou de staallevering verplaatsen van de autofabriek naar de fabriek van keukenapparatuur, niet omdat hij iets weet over (de vraag naar) auto's of keukenapparatuur, maar simpelweg omdat het prijssysteem hem heeft geïnformeerd dat dit winstgevender zou zijn (op de lange termijn zou de staalproducent ook gestimuleerd worden om meer staal te produceren).

Hayek legde uit dat relevante informatie in de economie kenbaar wordt gemaakt door middel van het prijssysteem, wat ervoor zorgt dat markten efficiënt middelen kunnen toewijzen over de samenleving daar waar ze het meest gewaardeerd worden.

'In wezen, in een systeem waarin de kennis van de relevante feiten is verspreid over vele mensen, kunnen prijzen fungeren om de afzonderlijke acties van verschillende mensen te coördineren op dezelfde manier als subjectieve waarderingen het individu helpen om de onderdelen van zijn plan te coördineren', schreef de Oostenrijker: 'een wonder.'[^21]

En belangrijk is dat dit allemaal mogelijk is zonder centrale planning. De vrije markt, zo betoogde Hayek, valt het best te begrijpen als een vorm van zelforganisatie van onderaf: een *spontane orde*.

## Rentetarieven

Waar Mises Hayeks begrip van spontane orde vormde doorheen ruimte -- de toewijzing van middelen van het ene punt in de samenleving naar het andere -- hielpen de werken van Von Böhm-Bawerk om Hayeks begrip van spontane orde in de tijd te vormen.

Von Böhm-Bawerk kwam in de jaren 1890 op de proppen met een nieuw idee in het vakgebied van de economie, dat van groot belang werd voor de Oostenrijkse School: *tijdsvoorkeur*. Von Böhm-Bawerk stelde dat mensen doorgaans liever vroeger dan later goederen en diensten willen ontvangen. De mate van deze voorkeur verschilt echter van persoon tot persoon. Iedereen heeft zijn eigen -- en subjectieve -- tijdsvoorkeur.

Deze tijdsvoorkeuren, bepleitte von Böhm-Bawerk, worden weerspiegeld op de markt door middel van rentetarieven.

Stel je voor dat zowel Marie als Joris graag een nieuwe auto willen hebben. Ze hebben beiden liever vandaag dan volgend jaar een nieuwe auto. Maar Marie, wier auto net kapot is gegaan en die elke dag naar haar werk moet rijden, hechte veel meer waarde aan een nieuwe auto vandaag dan aan een nieuwe auto volgend jaar. Joris daarentegen heeft nog steeds een redelijk goede auto en werkt van thuis uit, dus heeft hij niet zo'n haast om een nieuwe te krijgen. Marie heeft een hogere tijdsvoorkeur dan Joris.

Stel je voor dat een nieuwe auto $ 20.000 kost. Marie heeft helaas geen geld, terwijl Joris $ 20.000 aan spaargeld heeft. Op het eerste zicht zou dit suggereren dat Joris eerder dan Marie een nieuwe auto zal kopen: Joris kan het zich vandaag al veroorloven, terwijl Marie eerst nog geld moet sparen voordat ze een nieuwe auto kan betalen.

Maar er is een andere optie. Joris zou Marie $ 20.000 kunnen lenen.

Of dit een goede deal is voor hen beiden, kan eenvoudig worden ontdekt door middel van rentetarieven. Laten we zeggen dat Marie, omdat ze een hoge tijdsvoorkeur heeft, vandaag in principe een auto 10 procent meer zou waarderen dan een auto volgend jaar. Dat wil zeggen dat ze zou bereid zijn om $ 22.000 voor een auto van $ 20.000 te betalen als ze deze vandaag kan hebben in plaats van een jaar vanaf nu. Ze is daarom bereid om 10 procent rente te betalen op een lening van $ 20.000. Joris, die een lage tijdsvoorkeur heeft, zou een nieuwe auto vandaag slechts 1 procent meer waarderen dan een auto volgend jaar, een verschil van slechts $ 200.

Joris zou dus kunnen besluiten om zijn aankoop uit te stellen en in plaats daarvan $ 20.000 te lenen aan Marie. Na een jaar zal hij het geleende bedrag plus een extra $ 2.000 aan rente terugkrijgen. Dit zorgt ervoor dat Marie de auto vandaag al kan kopen, terwijl de extra $ 2.000 voor Joris de *kosten* van het uitstellen van de aankoop van $ 200 ruimschoots goedmaakt. Beide partijen zouden er voordeel uit halen. Rentetarieven stellen hen in staat onderling hun middelen in de tijd te verdelen, zodat ze het beste overeenkwamen met hun individuele tijdsvoorkeuren.

Hoewel dit natuurlijk een zeer vereenvoudigd voorbeeld is, doen kredietmarkten iets vergelijkbaars op grotere schaal. Geldverstrekkers en -ontleners komen een rentetarief overeen waar het aanbod en de vraag naar geld elkaar treffen, gebaseerd op de gezamenlijke tijdsvoorkeuren. Als zodanig zijn rentetarieven in feite ook prijzen. Ze weerspiegelen de prijs van geld.

En net zoals alle prijzen, communiceert de prijs van geld relevante informatie. Hayek was van mening dat de gemiddelde rente iets onthult over de hele economie. Als de rentetarieven hoog zijn, wijst dit erop dat veel mensen een hoge tijdsvoorkeur hebben en niet erg bereid zijn om geld uit te lenen. Ze geven er de voorkeur aan om goederen en diensten eerder dan later aan te schaffen. Omgekeerd, als de rentetarieven laag zijn, suggereert dit dat veel mensen een relatief lage tijdsvoorkeur hebben en bereid zijn hun aankopen uit te stellen als dat betekent dat ze ondertussen wat rente kunnen verdienen.

Hayek was dus van mening dat rentetarieven producenten informeerden over de productiefase waar ze hun middelen aan moesten besteden. Lage rentetarieven signaleerden aan producenten dat ze dit *goedkope geld* moesten benutten om productieprocessen op lange termijn te verbeteren door te investeren in goederen van een hogere orde, zoals een nieuwe oven om staal te produceren, die later kan worden gebruikt in de productie van auto's (of keukenapparatuur). Daarentegen maken hoge rentevoeten het lenen van geld duur, wat producenten aanmoedigt om reeds beschikbare middelen te gebruiken en zich te concentreren op het voltooien van de productie in een laat stadium (het laatste deel van het proces waar de uiteindelijke consumptiegoederen zoals auto's worden gemaakt en tentoongesteld in toonzalen voor mensen om te kopen).

Het mooie hiervan, zag Hayek in, is dat de tijdsvoorkeuren van mensen netjes overeenkomen met de productiecapaciteit van de economie. Als tijdsvoorkeuren laag zijn, investeren mensen hun geld (of in de meeste gevallen zouden ze het *sparen* op een bankrekening en de bank investeert het voor hen), en producenten worden gestimuleerd om te investeren in hun langetermijnproductieprocessen. Dus wanneer tijdsvoorkeuren in de toekomst toenemen, kunnen mensen hun geld en de rente die ze verdienen uitgeven aan de vruchten van al deze verhoogde productiviteit.

Rentevoeten, legde Hayek uit, bevorderen spontane orde door de tijd heen!

Dat is natuurlijk zo, *als* rentetarieven in feite de tijdsvoorkeuren nauwkeurig weerspiegelen. Hayek merkte echter op dat het in de praktijk vaak niet toegelaten werd om zo te zijn.

## De Federale Reserve

Een aantal jaren voordat zijn student afstudeerde aan de Universiteit van Wenen, hielp Mises Hayek opnieuw om een tijdelijke functie te verkrijgen als onderzoeksassistent bij de Universiteit van New York.

Toen de jonge Oostenrijker in 1923 in de Verenigde Staten aankwam, waren de *Roaring Twenties* in volle gang. De Amerikaanse economie floreerde, en mensen waren maar al te blij om geld te lenen om auto's van Ford te kopen, nieuwe technologische wonderen zoals wasmachines, of vastgoed te kopen in de voorsteden van grote steden. Of ze gebruikten het geld om te investeren in aandelen: de Dow Jones-beursindex bereikte jaar na jaar nieuwe hoogtepunten.

Hayeks onderzoek zou zich richten op de economische rol van één instituut in het bijzonder: het relatief nieuwe centrale banksysteem van de Verenigde Staten, genaamd de Federal Reserve. De *Fed*, zoals dit centraal banksysteem vaak wordt genoemd, was in 1913 opgezet om vertrouwen en stabiliteit te brengen in het Amerikaanse bankensysteem.

Er werd gedacht dat een anker voor vertrouwen en stabiliteit noodzakelijk was, omdat commerciële banken werkten op basis van *fractionele reserves*: ze hadden minder echt geld in hun kluizen dan wat spaarders op hun bankrekeningen hadden toegeschreven. Het verschil werd uitgeleend aan kredietnemers en bracht rente op voor zowel banken als hun spaarders. Maar dit kon ook economische instabiliteit veroorzaken, want als te veel spaarders het vertrouwen in een bank verloren en ervoor kozen om tegelijkertijd hun geld op te nemen, zou de bank krap bij kas kunnen komen te zitten, waardoor ze niet alle opnameverzoeken konden honoreren.

In het scenario van zo'n *bankrun*, kon de Federal Reserve nu optreden als *kredietverstrekker in uiterste nood* door een lening te verstrekken aan de bank die in de problemen kwam. Zo'n lening zou de bank van voldoende liquiditeit (contant geld) voorzien om de storm te doorstaan, zodat er geen reden was voor spaarders om zich zorgen te maken.

Maar Hayek, die helemaal uit Oostenrijk was gekomen om de rol van de Fed als kredietverstrekker in uiterste nood te onderzoeken, en haar invloed op de Amerikaanse economie, was kritisch.

Hayek vond dat de garanties van de nieuwe instelling economische prikkels verstoorden. Hij vreesde dat gunstige economische vooruitzichten de commerciële banken konden aansporen om leningen ruimer te verstrekken dan voorheen, waardoor de geldhoeveelheid in wezen toenam. Meer bankleningen betekent meer geld om in de economie uit te geven.[^22] Dit *nieuwe geld* zou de algemene prijzen omhoog drijven -- *inflatie* -- waardoor bedrijfswinsten over de hele lijn hoger uitvallen en op hun beurt de gunstige economische vooruitzichten bevestigen. De mogelijkheid van commerciële banken om in wezen nieuw geld aan te maken door middel van leningen, zou een feedback-loop van uitbundige kredietcreatie kunnen veroorzaken.

Wanneer de kredietcreatie echter onvermijdelijk vertraagt, stopt de muziek. Als de hoeveelheid nieuw geld die in de economie wordt geïnjecteerd afneemt, zullen de prijzen dalen --- deflatie. Bedrijven zullen geconfronteerd worden met hun te optimistische inschattingen van de economische vooruitzichten en kunnen hun producten niet voor de verwachte prijzen verkopen. Sommige bedrijven zullen moeten inkrimpen, wat leidt tot een stijging van de werkloosheid en de economie verder vertraagt, omdat mensen minder te besteden hebben. Andere bedrijven zullen failliet gaan omdat ze hun leningen niet kunnen terugbetalen, wat commerciële banken in de problemen brengt om aan de depositovereisten te voldoen. Deze banken zullen nieuwe leningen moeten stopzetten, wat de economie nog verder vertraagt, resulterend in meer ontslagen en onbetaalde leningen, en zo verder.

Economen zouden later naar een dergelijke dynamiek verwijzen als een *deflatoire schuldenspiraal*. Deze lagen aan de basis van enkele bankencrises die de oprichting van de Federal Reserve in eerste instantie motiveerden.[^23]

Volgens Hayek was er geen reden om aan te nemen dat het oprichten van een *kredietverstrekker in uiterste nood* deze kwalijke dynamiek zou beperken. Integendeel, het zou het zelfs kunnen versterken.

In het oude systeem, merkte hij op, hadden commerciële banken tenminste nog een goede reden om voorzichtig te zijn en niet te veel leningen te verstrekken:

> 'In afwezigheid van enige centrale bank, is de voornaamste beperking voor individuele banken tegen het uitgeven van buitensporig krediet in een stijgende economische activiteitsfase, de noodzaak om voldoende liquiditeit te behouden om de vraag in een periode van krap geld het hoofd te bieden met hun eigen middelen.'[^24]

Het oprichten van een *kredietverstrekker in uiterste nood* kan inderdaad een toeloop op de bank en paniek voorkomen. Maar Hayek stelde dat dit tegelijkertijd de prikkel voor banken wegneemt om in eerste instantie enige terughoudendheid te tonen bij het verstrekken van leningen.

'Het moet dus onvermijdelijk leiden tot een gestage toename in het gebruik van krediet en daardoor de herhaling van recessies nog onvermijdelijker maken', concludeerde Hayek.[^25]

Dit soort verkeerde afstemming van economische prikkels, waar bepaalde economische spelers -- in dit geval, banken -- beloond worden voor het nemen van meer risico's, maar niet de volledige kosten van deze risico's dragen, wordt in de economie *moreel risico* genoemd. Hayek vond dat de Federal Reserve dit morele risico in de economie introduceerde.

En Hayek geloofde dat dit niet eens de belangrijkste manier was waarop de Federal Reserve onhoudbare, door krediet geïnduceerde, economische bubbels stimuleerde.

## De Oostenrijkse conjunctuurcyclus

Het lezen van het jaarverslag 1923 van de Federal Reserve bepaalde de koers van Hayeks carrière als econoom voor de komende decennia.

In het document legde de Amerikaanse centrale bank uit hoe ze haar beheer over de geldhoeveelheid gebruikte om economische activiteit te stabiliseren. Meer in het bijzonder verklaarde de Amerikaanse monetaire autoriteit hoe ze rentetarieven gebruikte als beleidsinstrument: een zeer nieuw concept op dat moment, geïntroduceerd door wat zelf een zeer nieuwe instelling was.[^26]

Het idee was vrij eenvoudig. Door valuta in het bankensysteem te injecteren (doorgaans door overheidsobligaties te kopen), kon de Fed commerciële banken voorzien van meer reserves en daardoor bereid (en in staat) maken om leningen te verstrekken tegen steeds lagere rentetarieven. Dit zou bedrijven en mensen stimuleren om te lenen. Anderzijds, door reserves uit het bankensysteem te halen (door overheidsobligaties te verkopen), konden banken worden ontmoedigd om leningen te verstrekken, waardoor de rentetarieven stijgen en economische activiteit wordt afgeremd.

De Federal Reserve geloofde dat ze de conjunctuurcyclus konden afvlakken door de rentetarieven zorgvuldig te beheren. Als de Fed de rentetarieven tijdens recessies licht kon verlagen, en ze tijdens oplevingen een beetje kon verhogen, konden ze de markt een kleine stimulans bieden als die in een dip zat, en een beetje afremmen als hij op hol sloeg.

Hayek was een grote criticus van dit beleid.

De Oostenrijker was van mening dat de Federal Reserve valse signalen naar de markt zond door de rentetarieven kunstmatig laag te houden. Iedereen maakte gebruik van goedkoop geld om te investeren in bedrijven, die dit kapitaal gebruikten om meer middelen toe te wijzen aan hun productieprocessen. Echter, waarschuwde Hayek, er was geen overeenkomstige uitgestelde consumptie om de toekomstige productiegroei op te vangen. De rentetarieven waren niet laag omdat veel mensen een lage tijdsvoorkeur hadden en hun geld spaarden voor toekomstige uitgaven, maar omdat de Fed ze zo laag hield.

Wanneer rentetarieven uiteindelijk zouden stijgen en de creatie van nieuw krediet zou vertragen, zouden bedrijven worden gedwongen om de productie te voltooien, maar zouden ze ontdekken dat er geen echte vraag was om dit te evenaren. Zonder klanten om hun goederen te kopen, of in ieder geval niet tegen de prijzen die ze hadden verwacht, zouden bedrijven gedwongen zijn om werknemers te ontslaan en mogelijk in gebreke te blijven op hun leningen. Zo start een deflatoire schuldenspiraal.

Toen Hayek in de Verenigde Staten aankwam, bloeide de economie: zowel consumptie als investeringen schoten omhoog. Maar hij kwam tot de conclusie dat dit niet stand kon houden. De manipulatie van rentetarieven verstoorde de opkomst van de spontane economische orde in de tijd. Hayek was bezorgd dat de Federal Reserve in plaats van het afvlakken van de hoogte- en dieptepunten van de economische cyclus, deze eigenlijk versterkte.

En inderdaad, toen de Fed aan het eind van het decennium eindelijk de rente verhoogde, droogden de investeringen op terwijl er geen toename in consumptie was om dit te compenseren. De Roaring Twenties eindigden in 1929 met een knal en de Amerikaanse aandelenmarkt stortte in. In de daaropvolgende jaren verloor de Dow Jones-aandelenindex bijna 90 procent van zijn waarde, gingen tienduizenden bedrijven failliet, steeg de werkloosheid sterk en (ondanks de verantwoordelijkheid van de Federal Reserve als kredietverstrekker in uiterste nood) gingen ook duizenden banken op de fles.

Alhoewel het pijnlijk was, geloofde Hayek dat de beste aanpak destijds was om de deflatoire schuldenspiraal zijn gang te laten gaan. Daar waar kunstmatig lage rentetarieven een valse economische bloei hadden ingeluid, zou de economische malaise de economie herkalibreren naar duurzamere niveaus. Terwijl niet-rendabele bedrijven onderuitgingen, konden rendabele bedrijven hun middelen (inclusief hun werknemers) overnemen en ze beter benutten. Dit proces zou waarschijnlijk een tijdje duren, maar zou uiteindelijk tot een gezondere economie leiden.

Midden in de scherpe economische crisis die later bekend zou worden als de Grote Depressie, was de voorgestelde oplossing van Hayek echter niet erg geliefd. De meeste mensen waren van mening dat er *iets moest gedaan worden*.

## De rivaliteit

En er kon iets gedaan worden, zo stelde een academicus uit Cambridge genaamd John Maynard Keynes. De Britse econoom zou tijdens de Grote Depressie snel naam maken door een onconventionele, maar dringend gewenste oplossing aan te dragen om de economie weer op de been te krijgen. In schril contrast met de pijnlijke oplossing die Hayek voorstelde, verspreidde Keynes een boodschap waar veel mensen reikhalzend naar uitkeken.[^27]

Keynes negeerde Hayeks analyse van de oorzaken van de depressie en beweerde dat de economische malaise gewoon het ongelukkige resultaat was van een daling van de totale vraag. Hij redeneerde dat de economie stagneerde omdat mensen, voornamelijk om psychologische redenen, minder geld uitgaven dan eerder. Hij omschreef het fenomeen als *dierlijke instincten*. Om uit de depressie te geraken, moesten mensen weer meer geld uitgeven.

In wat de basis zou worden van nog een nieuwe school van economisch denken - het *Keynesianisme* - beargumenteerde de Britse econoom dat als het grote publiek geen geld zou uitgeven, de overheid het hun plaats moest doen. De overheid kon bijvoorbeeld investeren in openbare infrastructuurwerken, zelfs als dat zou betekenen dat daarvoor geld geleend moest worden. Geld lenen zou volgens Keynes sowieso goedkoop moeten zijn, aangezien de centrale bank de rentetarieven moest verlagen.

Door geld te besteden aan openbare infrastructuurwerken, zou de overheid banen creëren. Dat zorgt ervoor dat mensen lonen hebben om uit te geven en geld weer in de economie kan gaan circuleren. Wanneer mensen weer op eigen houtje gaan uitgeven, zou de overheid vervolgens haar uitgaven moeten verminderen. Keynes stelde voor dat beleidsmakers een *anti-cyclische* aanpak van overheidsuitgaven zouden moeten adopteren.

Eén specifieke beleidsmaker was volledig klaar voor deze uitdaging. Franklin D. Roosevelt (FDR), die in 1932 de eerste Amerikaanse presidentsverkiezingen sinds de beurskrach won, had zijn campagne gevoerd met de belofte om via zijn presidentieel mandaat actief een einde te maken aan de depressie. Toen hij zijn ambt opnam, vormden Keynes' ideeën het economische kader om zijn beleid te ondersteunen (zij het enigszins *nadat* dit beleid werd aangekondigd[^28]). Via een reeks overheidsprogramma's, die *de New Deal* werden genoemd, begon FDR al snel miljarden dollars uit te geven aan wegen, luchthavens, bruggen, dammen en nog veel meer.

Hayek was echter helemaal niet overtuigd van de ideeën van Keynes. Aangezien hij geloofde dat de economische malaise slechts een correctie was van de onhoudbare boom die eraan voorafging, was hij van mening dat overheidsuitgaven de uiteindelijk onhoudbare situatie alleen maar langer lieten voortduren.

Daarbovenop was er een wellicht nog belangrijker bezwaar tegen de Keynesiaanse anti-cyclische benadering, die niet eens echt gerelateerd was aan economie. Dit bezwaar was van politieke aard: Hayek geloofde niet dat politici te vertrouwen waren om te beslissen wanneer een economie in een opwaartse of neerwaartse trend zit. In plaats daarvan zouden ze in de verleiding komen om geld te lenen en in de economie uit te geven wanneer daar vraag naar is... wat evengoed continu het geval kan zijn.

'Er zullen altijd delen van het land of bevolkingsgroepen zijn die van mening zijn dat ze het moeilijk genoeg hebben om hulp te mogen ontvangen', schreef Hayek. 'Kan onder deze omstandigheden een rationeel anti-cyclisch beleid ontwikkeld worden als het in handen van politieke organen wordt gegeven?'[^29]

Voor Hayek was het antwoord een overduidelijke *nee*.

Dit leidde tot wat vaak beschouwd wordt als een van de grootste intellectuele confrontaties van de twintigste eeuw. Gedurende de jaren 1930 stonden Hayek, die op dat moment professor was aan de London School of Economics, en Keynes, nog steeds bij *King's College* in Cambridge, vaak tegenover elkaar in publieke debatten en ook in hun privécorrespondentie. Hun respectieve universiteiten in het zuidoosten van Engeland dienden als het strijdtoneel voor de opkomende titanen van de economie en hun twee tegenovergestelde economische visies.

En er was in belangrijke opzichten een scherp contrast. Terwijl Keynes geloofde dat de economie onder andere regels werkt wanneer deze op nationale schaal wordt geanalyseerd (het macro-niveau), hield Hayek vol dat alles uiteindelijk voortkomt uit individuen en hun subjectieve keuzes (het micro-domein). Waar Keynes graag focuste op prijsgemiddelden en totalen, was Hayek meer geïnteresseerd in prijsverschillen. En terwijl Keynes betoogde dat overheden een actieve rol moesten spelen in het beheren van de economie, volhield Hayek dat de vrije markt het beste aan zichzelf kon worden overgelaten.

Als Hayek het boegbeeld was van spontane orde van onderaf, dan had hij in Keynes en zijn interventiebeleid van bovenaf zijn hedendaagse, intellectuele rivaal gevonden.

[^8]: ​Deirdre N. McCloskey, *How to be Human -- Though an Economist*, 33.

[^9]: ​Lawrence H. Officer, *Exchange Rates Between the United States Dollar and Forty-one Currencies*, MeasuringWorth, 2023.

[^10]: ​Eamonn Butler, *Hayek: His Contribution to the Political and Economic Thought of Our Time*.

[^11]: ​Bruce Caldwell and Hansjoerg Klausinger, *Hayek: A Life, 1899--1950, Chs. 6--9*.

[^12]: ​Ludwig von Mises, *The Historical Setting of the Austrian School of Economics*, 12.

[^13]: ​Mises, *Historical Setting*, 12--13, 19--20.

[^14]: ​Ludwig von Mises, Human Action: A Treatise on Economics, The Scholar's Edition, 21, 38--54.

[^15]: ​Carl Menger, *Untersuchungen über die Methode der Sozialwissenschaften und der Politischen Oekonomie insbesondere*.

[^16]: ​Mises, *Historical Setting*, 3--19.

[^17]: ​Ludwig von Mises, *Economic Calculation in the Socialist Commonwealth*.

[^18]: Hoewel dit argument inderdaad is aangevoerd in de context van consumptiegoederen, is een meer precieze verwoording van dit argument, uitgewerkt in latere economische debatten, dat dit vooral van toepassing is op kapitaalgoederen.

[^19]: ​Mises, *Economic Calculation*, 18.

[^20]: Friedrich A. Hayek, *Prices and Production*.

[^21]: Friedrich A. Hayek, *The Use of Knowledge in Society*, American Economic Review. XXXV, No. 4: 526--27.

[^22]: Als persoon A € 100 bij de bank stort en de bank hiervan € 90 uitleent aan persoon B, zal persoon A nog steeds denken dat hij of zij € 100 heeft, terwijl persoon B € 90 zal hebben, voor een totaal van € 190. Bovendien, als persoon B de € 90 opnieuw bij de bank stort en de bank hiervan € 81 uitleent aan persoon C, zullen drie mensen denken dat ze samen € 271 bezitten. Dit kan zo doorgaan, wat lijkt alsof er steeds meer geld in omloop komt. Dit concept staat bekend als de *geldmultiplier*. In werkelijkheid kan de geldmultiplier zelfs nog agressiever zijn dan dit conventionele voorbeeld van fractioneel bankieren suggereert, omdat banken geen stortingen hoeven te ontvangen voordat ze leningen kunnen verstrekken; ze kunnen leningen uitgeven door eenvoudigweg krediet te creëren in de bankrekeningen van klanten.

[^23]: Gary Richardson and Tim Sablik, *Banking Panics of the Gilded Age: 1863--1913*, Federal Reserve History, 4 december 2015, [online](https://www.federalreservehistory.org/essays/banking-panics-of-the-gilded-age.)

[^24]: ​Friedrich A. Hayek, *Monetary Policy in the United States after the Recovery from the Crisis of 1920*, in The Collected Works of F.A. Hayek, Good Money: part I, ed. Stephen Kresge, 145.

[^25]: ​Hayek, *Monetary Policy*, 146.

[^26]: Stephen Kresge, *The Collected Works of F.A. Hayek, Good Money: part I*, 13.

[^27]: Het meest uitgebreid uiteengezet in John Maynard Keynes, *The General Theory of Employment, Interest and Money*.

[^28]: ​George Selgin, *The New Deal and Recovery, Part 15: The Keynesian Myth*, Cato Institute, 16 maart 2022, [online](https://www.cato.org/blog/new-deal-recovery-part-15-keynesian-myth.)

[^29]: ​Friedrich A. Hayek, *The Gold Problem*, in *The Collected Works of F.A. Hayek, Good Money: part I*, ed. Stephen Kresge, 184.
