# Denationalisatie van geld

Economische depressie en valutadevaluaties hadden geleid tot fascisme en, uiteindelijk naar de Tweede Wereldoorlog.

Maar Friedrich Hayek merkte met spijt op dat veel van zijn collega's in de academische wereld destijds niet opmerkten welke schade het monetair beleid had aangericht. In plaats daarvan schreven vele intellectuelen van die tijd de opkomst van het fascisme toe aan het falen van de vrije markten. Economen, politicologen en andere academici in het Westen overwogen alternatieve manieren om de samenleving te organiseren, en socialistische ideeën werden steeds populairder, een ontwikkeling die Hayek ronduit gevaarlijk vond.

Om deze trend tegen te gaan, nam de Oostenrijker het op zich om uit te leggen waarom socialisme niet het antwoord was, maar deel uitmaakte van het probleem. Het resulterende boek, *De Weg naar Slavernij*, nam een meer politieke benadering, hoewel het sterk werd ondersteund met economische inzichten zoals het economisch calculatieprobleem. Geschreven en gepubliceerd tijdens de oorlogsjaren, was de kernthese dat collectivistische ideologieën, inclusief zowel fascisme als socialisme, de neiging hebben om te leiden tot totalitarisme. Het zou het meest succesvolle boek van Hayeks carrière worden.

Het was wellicht een geschikt moment voor Hayek om zijn aandacht en energie te verschuiven van de economie naar de politieke sfeer. Na twee decennia van debatten en rivaliteit, werd het duidelijk dat niet zijn, maar de ideeën van Keynes over het monetaire beleid mensen en instituten binnen universiteiten, beleidsinstellingen en overheidsinstellingen voor zich wonnen. Als de vrijemarktideologie al zou overleven, zou het waarschijnlijk gebaseerd zijn op de Keynesiaanse doctrine.

Dit werd bevestigd toen vertegenwoordigers van de geallieerde landen, vol vertrouwen in hun overwinning in de oorlog, in 1944 bijeenkwamen in het Mount Washington Hotel in Bretton Woods, New Hampshire. De deelnemers waren er om een nieuw monetair systeem te ontwerpen voor de periode na de oorlog en Keynes was uitgenodigd om het Verenigd Koninkrijk te vertegenwoordigen. Hayek, die tegen die tijd ook de Britse nationaliteit had gekregen, werd helemaal niet uitgenodigd.

Het belangrijkste resultaat van de Bretton Woods-conferentie kan worden beschouwd als een herinvoering van de goudwisselstandaard, maar in tegenstelling tot de vooroorlogse klassieke goudstandaard was deze sterk gericht op de Amerikaanse dollar. Internationale handel zou in dollars worden uitgevoerd, terwijl deze dollars op hun beurt konden worden ingewisseld voor goud: één troy ounce per $ 35. Andere nationale valuta zouden vaste wisselkoersen vaststellen ten opzichte van de dollar, en centrale banken werden verwacht de rentetarieven te sturen om hun nationale valuta te stabiliseren.

Bretton Woods was ook de geboorteplaats van twee nieuwe internationale monetaire instellingen, met Keynes als drijvende kracht achter hun oprichting. De eerste hiervan, het Internationaal Monetair Fonds (IMF), kreeg de taak om toezicht te houden op internationale wisselkoersen en kon geld lenen aan landen in financiële problemen. Het tweede, de Wereldbank, zou ook leningen verstrekken, maar met een sterkere focus op het heropbouwen van het naoorlogse Europa (en later andere ontwikkelingslanden).

Het *Bretton Woods-systeem*, zoals het later genoemd werd, werd kort na de nederlaag van de Asmogendheden in 1945 uitgerold, maar dan alleen in het Westen. Hoewel de Sovjet-Unie vertegenwoordigers naar Bretton Woods had gestuurd, weigerde deze communistische staat uiteindelijk om de overeenkomst te ratificeren. Ze beschuldigden het IMF en de Wereldbank 'takken van Wall Street'[^79] te zijn. In plaats daarvan nam het vele Oost-Europese landen over na de oorlog. Het markeerde het begin van de Koude Oorlog, waarin (een Keynesiaanse variant van) vrijemarktkapitalisme in de Verenigde Staten en West-Europa op vele manieren zou concurreren met de socialistische doctrine in het Oosten.

Keynes was er echter niet om de effecten van het Bretton Woods-systeem en de instellingen van deze nieuwe monetaire orde te bestuderen. De econoom overleed kort na de oorlog, in 1946.

Hoewel Hayek zijn rivaal had overleefd, erkende hij dat de ideeën van Keynes de voorkeur genoten boven de zijne. Hij had niet het gevoel dat de nieuwe generatie Keynesiaanse economen echt geïnteresseerd was in een eerlijk en zinvol debat. De Oostenrijker besloot de London School of Economics te verlaten en zich aan te sluiten bij de Universiteit van Chicago. Daar trok hij zich grotendeels terug uit het vakgebied economie en verschoof zijn focus naar de wereld van de politiek en de filosofie.

## Het tijdperk van Keynes

Halverwege de twintigste eeuw was *het tijdperk van Keynes* onmiskenbaar aangebroken in het kapitalistische Westen. Overheden, centrale banken en andere instellingen bepaalden het economische beleid en economen trachtten het theoretische raamwerk achter fiscale planning, stabilisatiebeleid en monetaire stimuli verder uit te werken. Zo introduceerde bijvoorbeeld Professor William Phillips van de London School of Economics de Phillips-curve, die aangaf dat er een omgekeerd verband was tussen inflatie en werkloosheid. Dit was precies zoals de Keynesiaanse theorie suggereerde: meer overheidsuitgaven resulteerden in meer banen.

Politici kregen de theoretische rechtvaardiging om met overheidsuitgaven een economische neergang te bestrijden. Dit leek een tijdje de oplossing voor alles, aangezien Keynesiaanse beleidslijnen overal in de westerse wereld werden uitgerold. In het Verenigd Koninkrijk had premier Winston Churchill in 1944 volledige werkgelegenheid tot een nationaal beleidsdoel verheven. In de Verenigde Staten ondertekende Franklin D. Roosevelt's opvolger, president Harry S. Truman, in 1946 de Employment Act, waardoor de uitvoerende tak van de regering verantwoordelijk werd voor het beheer van de economie. En in Europa had het naoorlogse herstelprogramma, informeel bekend als het Marshallplan, het hele westelijke deel van het continent omgevormd tot een soort Keynesiaans laboratorium.

Iets later in de Verenigde Staten was Truman's opvolger Dwight D. Eisenhower de eerste president die het Keynesiaanse economiebeleid echt ten volle toepaste. Toen de VS in het midden van de jaren '50 werd geconfronteerd met enkele korte recessies, bestreed de president de werkloosheid met grote investeringen in de snelwegeninfrastructuur. En nadat de Sovjet-Unie erin slaagde de Spoetnik-satelliet in een baan om de aarde te brengen, volgde Eisenhower dit op met aanzienlijke financiële injecties in het ruimtevaartprogramma van NASA. Het leek te werken zoals bedoeld: de Amerikaanse economie bloeide op.

Toen Eisenhower tegen het einde van zijn presidentstermijn echter de uitgaven moest beperken, resulteerde dit vrijwel onmiddellijk in een nieuwe depressie. Het Amerikaanse volk was hier niet blij mee. Ze waren van mening dat Eisenhower alle middelen voorhanden had om deze trend te keren, maar dat hij deze keer naliet om in te grijpen.

Tegen de tijd dat de verkiezingen voor de opvolger van Eisenhower er aankwamen, was de economische neergang een groot thema geworden in de presidentiële campagnes. Terwijl de jonge Democratische kandidaat John F. Kennedy zijn aanhangers mobiliseerde onder het motto 'Laten we dit land weer in beweging krijgen', worstelde de Republikeinse kandidaat en zittend vicepresident Richard Nixon om zich te distantiëren van Eisenhower's conservatieve fiscale benadering aan het einde van zijn tweede termijn. Toen Kennedy uiteindelijk met een ongelooflijk kleine marge de race won, bleef een verslagen Nixon ervan overtuigd dat hij de verkiezingen zou hebben gewonnen als de bezuinigingen van Eisenhower niet in de weg hadden gestaan.[^80]

Gedurende zijn presidentschap bevestigde Kennedy dat hij royaal zou investeren in de economie op basis van Keynesiaanse principes. Hij blies Eisenhower's initiële uitgavendrift snel nieuw leven in, door geld te pompen in het Amerikaanse ruimtevaartprogramma, terwijl hij ook rijkelijk uitgaf aan het leger. Na de moord op de president slechts enkele jaren later, in 1963, zette zijn vicepresident en opvolger Lyndon B. Johnson dit beleid voort, met de Vietnamoorlog als grote, nieuwe geldverslindende factor.

In 1968, aan het eind van Johnson's presidentschap, was Nixon klaar voor een nieuwe gooi naar het ambt. En deze keer won hij. Toen hij het roer van Johnson overnam, leek Nixon, in zijn hart conservatief op fiscaal vlak, aanvankelijk bereid en gretig om een einde te maken aan deze Keynesiaanse vrijgevigheid. Hij wees er op dat de regering jarenlang tientallen miljarden dollars meer had uitgegeven dan het aan belastingen ontving.

Toen de bezuinigingen van Nixon echter onmiddellijk resulteerden in een milde economische recessie, besloot de president alsnog mee te spelen met het spel. Hij verklaarde zichzelf een Keynesiaan, kondigde een plan voor volledige werkgelegenheid aan en stelde een expansieve begroting voor om de economie te stimuleren. Nixon had een waardevolle les geleerd tijdens zijn mislukte poging om een decennium eerder president te worden, en was klaar om de nieuwe politieke werkelijkheid te accepteren.[^81]

Zoals de president verklaarde in de State of the Union van 1970:

> 'Ik erken de politieke populariteit van uitgavenprogramma's, en zeker in een verkiezingsjaar.'[^82]

De Keynesiaanse leer stelde eigenlijk zowel overheidsuitgaven als bezuinigingen als vereiste: uitgaven om de economie een impuls te geven, en bezuinigingen wanneer dit niet langer noodzakelijk was, om ongecontroleerde inflatie te voorkomen. Het probleem was echter dat het nu duidelijk werd dat hoewel verhoogde uitgaven verkiezingen konden winnen, bezuinigingen dat niet deden. Nixon had op de harde manier geleerd dat het beter was om vast te houden aan het populairdere stadium van de Keynesiaanse cyclus van uitgaven, en gemakshalve dat deel van de leer te negeren dat voorschreef wanneer bezuinigingen nodig waren.

Dit probleem was natuurlijk voorzien. Hayek heeft altijd beweerd dat de grootste nalatigheid van Keynes wellicht niet op economisch gebied lag, maar op politiek gebied: het was over het algemeen niet zo dat je van verkozen vertegenwoordigers kon verwachten dat ze de discipline zouden volhouden die een *anti-cyclische* aanpak vereist.

## De Nixon-schok

De overdadige uitgavendrift van Nixon en een aantal van zijn voorgangers kon in zekere zin worden verklaard als een uitvoering van de Keynesiaanse doctrine. Maar tegen de jaren '70 werden sommige van de grootste dollar-bezitters wantrouwend. Het werd steeds duidelijker dat de Verenigde Staten boven hun stand leefden en veel meer geld drukten en uitgaven dan ze in goud konden verantwoorden.

Sommige landen met grote dollarreserves besloten uiteindelijk om hun papieren geld geleidelijk aan af te bouwen. Ze wilden dollars omzetten in goud, wat makkelijker gezegd dan gedaan was, aangezien het verplaatsen en opslaan van grote hoeveelheden goud een ernstige logistieke uitdaging vormde. De Franse president Georges Pompidou stuurde uiteindelijk een compleet oorlogsschip naar New York om het goud van zijn land op te halen bij de plaatselijke Federal Reserve Bank. Er waren sterke aanwijzingen dat de Britten hetzelfde plan hadden.

Tot Nixon er op 15 augustus 1971 een einde aan maakte.

Tegenwoordig bekend als de *Nixon-schok*, kondigde de president in een televisietoespraak aan dat de *opschorting* van de omwisselbaarheid van dollars naar goud 'in het belang van monetaire stabiliteit, en in het beste belang van de Verenigde Staten' was.[^83] Zonder voorafgaande waarschuwing zorgde Nixon met een Executive order er eigenhandig voor dat er een bom terechtkwam onder het Bretton Woods-systeem: landen die dollars hielden als onderdeel van hun reserves konden het papieren geld niet langer omzetten in edelmetaal.

Omdat de dollar de enige munteenheid was die onder het Bretton Woods-systeem omwisselbaar was naar goud, betekende dit onmiddellijk het einde van de goudstandaard. Wat overbleef waren nationale, ongedekte valuta, oftewel fiatvaluta. Toen kort daarna zes Europese landen ermee instemden om de waarde van hun munteenheden aan elkaar te koppelen en ze te laten fluctueren tegenover de dollar, werd het Bretton Woods-systeem effectief volledig verlaten.[^84]

Ondertussen had Nixon in de verkiezingsperiode van 1972 het voornemen om de economie te laten opbloeien. Volgens hem kon hij dit realiseren door de Federal Reserve ertoe aan te zetten de rente te verlagen. Goedkoop geld zou leiden tot inflatie en dat zou op zijn beurt weer leiden tot minder werkloosheid, zoals de Phillips-curve aangaf. Nixon wees zijn economische raadgever Arthur Burns aan als voorzitter van de Federal Reserve. Aangezien de eerdere beperkingen opgelegd door de gouddekkingsratio nu waren opgeheven, oefende hij onmiddellijk druk uit op de nieuwe voorzitter.

Nixon kreeg zijn zin. Hij won de herverkiezing. En tegen 1973 waren de officiële inflatiecijfers, gebaseerd op de consumentenprijsindex (CPI), gestegen naar 9,6 procent, om vervolgens in de daaropvolgende jaren te stijgen naar dubbele cijfers.[^85]

## Inflatie

Hayek beweerde dat kunstmatig lage rentes zouden leiden tot een economische groei die niet vol te houden was, gevolgd door een pijnlijke correctie, waarbij de markt het best met rust kon worden gelaten om een natuurlijker evenwicht te vinden. Keynesianen daarentegen adviseerden dat de overheid met extra uitgaven zou moeten ingrijpen om de economie weer op het juiste spoor te krijgen na zo'n recessie.

Hayek erkende altijd dat dergelijke Keynesiaanse overheidsuitgaven op de korte termijn inderdaad kunnen werken. Als de overheid nieuw geld in de economie pompt, zou het kunnen lijken alsof de economie redelijk stabiel blijft. Maar onder die façade van aanhoudende welvaart, waarschuwde Hayek, zou een donkerdere economische realiteit schuilgaan: het creëren van geld was slechts een verlenging van de verkeerde toewijzing van middelen die door de initiële verstoring werd veroorzaakt.

Dit was misschien wel Hayeks grootste bezwaar tegen deze vorm van inflatie: het zou na verloop van tijd erg moeilijk worden om het terug te draaien. Inflatie is verslavend, waarschuwde de econoom. Zodra de economie gewend raakt aan gemakkelijk geld, zal het alleen maar meer nodig hebben om het kunstmatig hoge werkgelegenheidsniveau te handhaven.

In een vroeg stadium lijkt inflatie de economie inderdaad te stimuleren. Als inflatie begint, drijft het de prijzen op naar een hoger niveau dan bedrijven hadden verwacht. Dit wordt door hen als een aangename verrassing gezien, omdat ze hun producten voor meer geld kunnen verkopen dan ze hadden ingecalculeerd, waardoor ze grotere winsten genieten. Bedrijven die in zwaar weer verkeerden en anders ten onder waren gegaan, kunnen hun hoofd boven water houden dankzij deze onverwachte economische opleving.

Maar als de inflatie langere tijd aanhoudt, legt Hayek uit, zullen bedrijven uiteindelijk de verwachting van hogere toekomstige prijzen moeten meewegen. Om concurrerend te blijven, zullen ze hun investeringen in het productieproces moeten verhogen, wat de prijs van kapitaal en arbeid omhoogdrijft, tot het punt waarop de algehele winstmarges weer terug zijn op het punt waar ze begonnen.

Dit betekent ook dat de bedrijven die al kampten met problemen vóórdat de inflatie toesloeg, weer het risico lopen om failliet te gaan.

Om te voorkomen dat deze bedrijven kopje onder gaan, en om het positieve effect van het nieuwe geld te verlengen, is nog hogere inflatie nodig. Deze hogere inflatie zal de prijzen nog meer opdrijven dan verwacht, wat opnieuw een welkome verrassing betekent voor de bedrijven.

Maar als deze hogere inflatie ook aanhoudt, moet het natuurlijk uiteindelijk opnieuw worden meegenomen in het productieproces, waardoor de bedrijven die al worstelden weer het risico lopen om ten onder te gaan.

Deze bedrijven zouden misschien gered kunnen worden door nog meer inflatie, maar uiteindelijk, waarschuwde Hayek, kan nieuw geld alleen op korte termijn stimuleren, terwijl er naarmate de tijd vordert steeds meer van nodig zou zijn. Het zou onvermijdelijk resulteren in een economie met zowel hoge inflatie als economische stagnatie.

Hayek:

> 'Als inflatie al enige tijd aan de gang is, zullen veel activiteiten afhankelijk zijn geworden van het voortduren ervan in een progressief tempo. Er zal een situatie ontstaan waarin, ondanks de stijgende prijzen, veel bedrijven verlies zullen lijden, en waarin er aanzienlijke werkloosheid kan zijn. Zodra de economie zich heeft aangepast aan een bepaald inflatietempo is een depressie met stijgende prijzen een typisch gevolg van slechts het afremmen van de stijging van de inflatie.'[^86]

In economische termen wordt dit resultaat (een economie met zowel inflatie van de munteenheid als economische stagnatie) stagflatie genoemd.

## Het Cantillon-effect

Hayek maakte zich om diverse redenen zeer veel zorgen over inflatie (en het uiteindelijke vooruitzicht van stagflatie).

Ten eerste kan inflatie het intertemporele prijssysteem verstoren. Misschien wel het belangrijkste is, dat het de kredietmarkten in de war kan brengen, aangezien schuldenaren en schuldeisers door inflatie op zeer verschillende manieren worden beïnvloed: schuldenaren profiteren als de reële waarde van hun schulden daalt, terwijl schuldeisers verlies lijden omdat het geld dat ze later terugkrijgen minder waard zal zijn dan het geld dat ze hebben uitgeleend.

Een tweede aspect van inflatie, en in de ogen van Hayek wellicht nog bedrieglijker, is dat het de boekhoudkundige praktijken vertekent. Inflatie kan namelijk winstcijfers oppompen, waardoor het lijkt alsof het rendement op investeringen hoger is dan in werkelijkheid. Slimme individuen kunnen misschien de devaluatie van de munteenheid meenemen in hun winst-en-verliesberekeningen, maar de econoom merkt op dat belastinginspecteurs nog steeds zullen aandringen op het belasten van de *schijnwinsten*. Inflatie leidt in wezen tot een impliciete stijging van de belastingen.

Maar Hayeks grootste bezorgdheid omtrent inflatie was een zorg die al in de achttiende eeuw beschreven was door de Iers-Franse econoom Richard Cantillon, en die bekend stond als het Cantillon-effect.[^87]

Het probleem, kort gezegd, is dat nieuw geld als eerste in omloop wordt gebracht door het in de economie te spenderen. En wanneer dit nieuwe geld voor het eerst wordt uitgegeven, wordt het uitgegeven in een economie die nog steeds de *oude* prijzen hanteert, die nog niet de extra bijgedrukte geldhoeveelheid weerspiegelen. Het spenderen van dit geld leidt vervolgens tot het opdrijven van de prijzen van de eerste goederen of diensten die ermee worden gekocht. De bedrijven die deze goederen of diensten verkopen, genieten van extra winst.

Deze bedrijven krijgen de kans om het nieuwe geld als eerste opnieuw uit te geven, terwijl de meeste prijzen in de economie nog niet zijn aangepast aan de toename van de geldhoeveelheid. De bedrijven die *deze* betalingen ontvangen mogen vervolgens het geld uitgeven in een economie waarin sommige prijzen zijn bijgesteld, maar nog niet allemaal; toch een voordeel. Dit gaat door totdat het nieuwe geld volledig door de economie is verspreid: prijsverhogingen vinden eerst plaats in een deel van de economie, waarna het zich als een rimpeling door de rest van de samenleving verspreidt.

Dit betekent dat degenen die *dichtbij* de bron van het geld zijn, hiervan kunnen genieten voordat de prijzen aangepast zijn: ze ervaren een toename in hun reële inkomen. Degenen die zich aan de *buitenkant* bevinden, zien alle prijzen stijgen voordat ze het nieuwe geld te pakken krijgen. Als ze uiteindelijk een beetje van het nieuwe geld ontvangen, biedt dit geen comparatief voordeel meer. Tot het moment dat het nieuwe geld hen bereikt, ervaarden ze een daling in hun reële inkomen.

Zoals Hayek de bevindingen van Cantillon samenvatte:

> 'Alleen die personen profiteren van de toename van geld waarvan de inkomens vroeg stijgen, terwijl voor personen waarvan de inkomens later stijgen, de toename van de geldhoeveelheid schadelijk is.'[^88]

Goudproducenten waren historisch gezien te vinden in het hart van het Cantillon-effect. Maar naarmate de rol van goud in het financiële systeem minder belangrijk werd en het Keynesianisme zijn intrede deed, begonnen overheden steeds vaker hun plaats te claimen in het centrum van het geldcreatieproces. Telkens wanneer overheden de geldhoeveelheid vergroten om de economie te stimuleren, komt dit in onevenredige mate de overheid zelf ten goede. Door het Cantillon-effect profiteren ook overheidsmedewerkers, aannemers van de overheid en de bedrijven die het dichtst bij de overheid staan, zoals financiële instellingen.

Dit resulteert in hogere prijzen in de delen van de economie die dicht bij de overheid staan, wat op zijn beurt weer meer middelen zal aantrekken. Belangrijk echter is dat deze middelen niet naar die delen van de economie stromen omdat ze daar de meeste waarde bieden voor de individuen in de samenleving. In plaats daarvan zal het Cantillon-effect de verdeling van middelen scheef trekken richting de bron van het nieuwe geld, in de praktijk richting de overheid en de financiële sector.

Aangezien het verslavende effect van inflatie vereist dat er steeds meer van is, zal na verloop van tijd een overmatige hoeveelheid bedrijfsactiviteit zich gaan richten op de overheid, volledig afhankelijk van de creatie van nieuw geld, maar zonder dat het veel waarde aan de samenleving toevoegt. Hayek voorspelde een voortdurende misallocatie van middelen ten gunste van de staat en ten nadele van de rest van de economie.

En uiteindelijk, zo waarschuwde de econoom, kan voortdurende, overdadige geldcreatie leiden tot de vernietiging van wat er nog over is van het vrije-marktsysteem. Hoge inflatie kan de prijzen, en daarmee de verdeling van middelen, zo ernstig verstoren dat er uiteindelijk sterke maatschappelijke druk ontstaat voor de invoering van prijscontroles.

Een rampzalige uitkomst, volgens Hayek:

> 'Openlijke inflatie is al erg genoeg, maar inflatie die onderdrukt wordt door [prijs]controles is nog erger: het is het echte einde van de markteconomie.'[^89]

## De overheid buitenspel zetten

Keynesianen, zo'n beetje alle mainstream economen van die tijd, deelden Hayeks zorg over inflatie en in het bijzonder stagflatie niet. Ze geloofden in feite dat stagflatie onmogelijk was. Zoals de Phillips-curve had aangetoond, waren inflatie en werkloosheid *omgekeerd* gecorreleerd: een hogere inflatie zou betekenen dat er minder werkloosheid was.

Maar de beleidsmaatregelen van Nixon begonnen de aannames van deze Keynesianen te weerleggen. Een combinatie van lage rentetarieven en stijgende olieprijzen door aanhoudende internationale strubbelingen zorgde in het begin van de jaren '70 al snel voor een opkomende inflatie. Maar nu verslechterden de economische vooruitzichten wereldwijd tegelijkertijd. Het decennium zou in het teken komen te staan van stagflatie. Dit bracht een geloofscrisis in de Keynesiaanse denkwijze met zich mee.

Hayek had zich in de aanloop naar de jaren '70 voornamelijk op de politiek gericht: hij had bijvoorbeeld uitgelegd hoe spontane orde ook gold voor de ontwikkeling van het rechtssysteeem, waardoor hij gematigder werd vergeleken met enkele van de radicalere libertarische Oostenrijkse economen. Maar halverwege de jaren '70 besloot hij dat hij niet langer kon zwijgen. Na een lange academische loopbaan die hem van de Universiteit van Chicago naar de Universiteit van Freiburg en uiteindelijk de Universiteit van Salzburg bracht, wendde Hayek zich opnieuw tot het schrijven over monetair beleid.

Hayek, een Oostenrijker, was ervan overtuigd dat de Keynesiaanse leer en haar onjuiste ideeën over geld de wereldwijde economie aan het ruïneren waren. Hij vond dat mensen hiervan bewust moesten worden gemaakt: dit was opnieuw een prioriteit voor hem geworden. Hoewel Hayek al ver in de zeventig was, was hij nog net zo vastberaden en compromisloos als altijd. Hij beschreef inflatie nu niet alleen als schadelijk, maar ook als ronduit onethisch, en vergeleek het zelfs met diefstal. Het geld was volgens Hayek al heel lang defect, en hij vond dat het hoog tijd was dat het gerepareerd werd.

Hoewel decennia van onverantwoorde overheidsuitgaven hadden geleid tot stagflatie, vond Hayek het te makkelijk om simpelweg de verantwoordelijke politici de schuld te geven. Hij geloofde dat het probleem dieper lag. Overheidsuitgaven waren populair vanwege de kortetermijnvoordelen die ze konden bieden. Al die geldcreatie gebeurde in democratische samenlevingen, in feite op verzoek van de maatschappij. Zolang de overheid en haar instellingen de poortwachters van de munteenheid waren, zouden invloedrijke belangengroepen politici er uiteindelijk toe aanzetten om zo'n krachtig instrument in hun voordeel te gebruiken.

Hayek kwam dus tot de conclusie dat overheden helemaal geen poortwachters van geld zouden moeten zijn:

'Een goede munteenheid, net als een goede wet, moet functioneren zonder rekening te houden met de effecten die beslissingen van de uitgever zullen hebben op bekende groepen of individuen', schreef Hayek.[^90] 'Zelfs met de beste bedoelingen ter wereld, kan geen enkele regering deze druk weerstaan [van zulke groepen of individuen], tenzij ze kunnen wijzen op een vaste barrière die ze niet kunnen overschrijden.'[^91]

Goud zou in theorie een dergelijke sterke barrière kunnen bieden. Idealiter zou goud dan zelf als munteenheid worden gebruikt, in plaats van dat het in bankkluizen wordt opgeslagen, wat het fractioneel reservebankieren mogelijk maakt. Maar de onpraktische aard van het rechtstreekse gebruik van goud bij transacties en de uitdagingen van een veilige opslag betekenen waarschijnlijk dat dit ideaal onhaalbaar is.

Een valuta gedekt door goud --- zoals bij de klassieke goudstandaard --- was praktischer, maar dit vereist vertrouwen dat regeringen niet de valuta zullen devalueren ten opzichte van goud, de dekkingsratio eenzijdig zullen veranderen, of zelfs de omwisselbaarheid volledig zullen opheffen. Dit zijn inderdaad allemaal dingen die Hayek regeringen in zijn eigen leven heeft zien doen.

Hayek heeft daarom altijd moeite gehad met het vinden van de ideale oplossing voor het problematische geldstelsel.

Maar in de nadagen van zijn carrière, viel het kwartje eindelijk voor hem.

'Midden in mijn radeloosheid over de hopeloosheid van het vinden van een politiek haalbare oplossing voor wat technisch gezien het eenvoudigst mogelijke probleem is, namelijk het stoppen van inflatie, heb ik ongeveer een jaar geleden in een lezing een ietwat schokkende suggestie geopperd. Het verder uitdiepen hiervan heeft geheel onverwachte nieuwe horizonten geopend', schreef Hayek halverwege de jaren '70.

> 'Ik kon niet nalaten het idee verder uit te diepen, omdat de taak om inflatie te voorkomen mij altijd van het grootste belang heeft geleken. Niet alleen vanwege de schade en het leed dat grote inflaties veroorzaken, maar ook omdat ik er al lang van overtuigd ben dat zelfs milde inflaties uiteindelijk de steeds terugkerende depressies en werkloosheid veroorzaken. Deze vormen terecht argumenten tegen het systeem van vrij ondernemerschap en moeten worden voorkomen als een vrije samenleving wil overleven.'[^92]

Het idee was dat geld aan de vrije markt overgelaten moest worden.

## Denationaliseren van geld

Hayek bepleitte zijn zaak voor het eerst in zijn toespraak tot de Gold and Monetary Conference in Genève in 1975.[^93] In 1976 presenteerde Hayek dit onconventionele voorstel uitvoerig in zijn boek *Denationalisatie van Geld*. In essentie betoogde de econoom dat banken volledig gedereguleerd moesten worden, zodat ze elk geld dat ze geschikt achten konden uitgeven: gedekt of ongedekt, inflatoir of deflatoir, al dan niet gecreëerd door leningen, en tegen elk renteniveau dat ze wilden vragen.

Hayek stelde voor om het feitelijke staatsmonopolie op geld te beëindigen.

In dit systeem (een behoorlijk radicale vorm van *vrij bankieren*) concurreren banken om klanten hun geld te laten gebruiken. Hayek geloofde dat juist deze concurrentie nodig was om de beste vorm van geld te ontwikkelen: zoals in elke vrije markt, moeten banken hun klanten een product leveren -- in dit geval, geld zelf -- met betere eigenschappen dan de producten die hun concurrenten aanbieden. Hayek redeneerde dat deze concurrentie tot verbetering zou leiden, omdat de markt het beste beschikbare geld zou selecteren.

Een bijzonder belangrijke eigenschap van elke munteenheid is ongetwijfeld de hoeveelheid geldeenheden, of specifieker, de groeisnelheid van de geldvoorraad --- de grootste oorzaak van inflatie. Gebruikers van een munteenheid zullen waarschijnlijk niet willen dat de voorraad te snel uitgebreid wordt, omdat dit de koopkracht van de eenheden die ze bezitten, zou schaden. Hayek geloofde dat concurrentie in dit domein de uitgevers van valuta eerlijk zou houden: als één bank te veel van zijn geld creërde, zouden klanten snel naar een alternatief overstappen. In feite zou ongewenste inflatie in essentie onmogelijk zijn, omdat mensen gewoonweg kunnen kiezen om niet mee te doen.

Terwijl het vrijwel onmogelijk was gebleken om overheden te stoppen met het opblazen van hun nationale munteenheden om hun uitgaven te financieren, redeneerde Hayek dat de discipline van de vrije markt dit probleem vanzelf zou oplossen.

Als een hypothese over hoe geld eruit zou zien in een wereld met vrij bankieren, stelde de econoom zich voor dat banken waarschijnlijk zouden streven naar een specifiek niveau van koopkracht, mogelijk gebaseerd op een bepaalde prijsindex. Ze kunnen dit doen door meer valuta uit te geven als de koopkracht van het geld boven dat doelniveau stijgt en door valuta uit de circulatie te halen als de koopkracht daaronder zakt. Een groot deel van het werk van de banken zou zijn om uit te zoeken wat mensen als een wenselijk niveau van koopkracht voor hun valuta beschouwen, zodat ze het soort geld kunnen selecteren dat het beste aan hun behoeften voldoet.

'Elke uitgever van een aparte valuta zou in staat moeten zijn om de hoeveelheid ervan te reguleren om het zo voor het publiek het meest acceptabel te maken, en concurrentie zou hem daartoe dwingen', schreef Hayek. 'Sterker nog, hij zou weten dat de straf voor het niet waarmaken van de opgewekte verwachtingen zou leiden tot het onmiddellijk verlies van klanten.'

Hij voegde eraan toe: '[...] de uitgevende banken, enkel geleid door hun streven naar winst, zouden zo het publieke belang beter dienen dan welke instelling dan ook die dat zogenaamd nastreeft.'[^94]

In *The Argument Refined*, de herziene en uitgebreidere versie van het boek dat twee jaar later werd gepubliceerd, stelde Hayek voor dat het meest aannemelijke resultaat van een vrij bankensysteem niet een breed scala aan valuta met verschillende doelen voor koopkracht zou zijn. In plaats daarvan speculeerde de econoom dat de overgrote meerderheid van de mensen zich zou richten op één type geld dat een algemeen acceptabel stabiliteitsdoel heeft. Dit stabiliteitsdoel zou op zijn beurt ook door andere valuta worden aangenomen, verwachtte Hayek, in wezen het stabiliteitsdoel zelf veranderend in iets van een meta-valuta waarop andere valuta zouden worden gebaseerd.

Op het eerste gezicht zou dit als een toegeving aan het gebruik van een consumentenprijsindex om stabiliteit te bepalen kunnen worden beschouwd, en tot op zekere hoogte was dat misschien ook zo. Maar het is belangrijk om te benadrukken dat Hayeks versie van dit idee niet verplicht of bindend was, noch dat het een door de overheid aangewezen centraal orgaan omvatte om te bepalen hoe zo'n index opgezet zou moeten worden. Hij geloofde dat dit aan de vrije markt overgelaten moet worden, zodat mensen vrij zijn om te kiezen voor welk doel zij het meest stabiel (of anderszins wenselijk) beschouwen.

Dit zou inderdaad een valuta met een vaste voorraad kunnen omvatten, of wat Hayek eerder in zijn carrière had omschreven als neutraal geld.

## Ongedekt geld

Het voorstel van Hayek kreeg niet meteen de steun van al zijn collega's binnen de Oostenrijkse school van economie. Veel Oostenrijkers waren van mening dat de markt al een lange tijd geleden de beste vorm van geld had gekozen. In een strijd die duizenden jaren heeft geduurd, had goud gewonnen. Zij hielden vol dat goud nog steeds de beste vorm van geld was, en dat nieuwe valuta op z'n minst *gedekt* moesten worden door het kostbare metaal.

Hoewel het in een vrij bankensysteem uiteraard mogelijk was om een door goud gedekte valuta te bieden, verwachtte Hayek niet dat de meeste mensen hiervoor zouden kiezen. Hij erkende dat de markt oorspronkelijk goud had gekozen als de beste vorm van geld, maar Hayek geloofde dat regeringen sindsdien de verdere ontwikkeling van geld hadden verhinderd door monopolisatie en strikte regulatie. Hayek verwachtte dat geld drastisch zou verbeteren als het aan de markt werd overgelaten.

'Ik geloof dat we het veel beter kunnen doen dan goud ooit mogelijk heeft gemaakt. Overheden kunnen het niet beter doen. Vrij ondernemerschap, oftewel de instellingen die zouden voortkomen uit een proces van concurrentie om goed geld te bieden, zouden dat ongetwijfeld wel kunnen', schreef hij. 'De mogelijkheid tot omzetting [naar goud] is een noodzakelijke waarborg die men aan een monopolist moet opleggen, maar is onnodig bij concurrerende aanbieders die zich niet in de concurrentiestrijd kunnen handhaven tenzij ze geld bieden dat minstens zo voordelig is voor de gebruiker als elk ander.'[^95]

Hayek overwoog echter wel dat nieuwe munten van de vrije markt mogelijk in eerste instantie door fiatgeld gedekt moesten worden. Dit zou vergelijkbaar zijn met hoe fiatgeld in eerste instantie door goud werd gedekt tot mensen het nieuwe geld leerden vertrouwen. Dit kon een tijd duren, gaf de econoom toe: 'Het bijgeloof sterft maar langzaam.'[^96] Maar uiteindelijk zouden mensen gaan begrijpen dat inflatoir fiatgeld continu waarde verliest tegenover het privégeld. Ze zouden door economische prikkels tot het inzicht komen dat wat ze echt van geld verwachten, schaarste is.

In een vrij bankensysteem zou er wel geen regulering zijn die garandeert dat gedekte valuta inderdaad uitwisselbaar waren voor datgene waardoor ze gedekt werden. Hoewel specifieke afspraken onder regulier contractrecht bindend kunnen zijn, zouden er geen bijzondere wetten zijn over de dekkingsratio en zou er ook geen kredietverstrekker in uiterste nood zijn. Banken zouden de kosten van hun eigen risico's dragen, en dat geldt ook voor de klanten die ervoor kiezen om deze banken te vertrouwen met hun geld. Maar dit kan misschien worden gezien als een goede zaak: vrij bankieren zou het morele risico wegnemen.

En door vrije banken volledig onafhankelijk van het bestaande financiële systeem te laten functioneren, geloofde Hayek dat het plan ook daadwerkelijk haalbaar was.

'Niet het minste voordeel van het voorgestelde afschaffen van het overheidsmonopolie op de uitgifte van geld, is dat het ons de kans zou geven om ons te bevrijden uit de impasse waarin deze ontwikkeling [van het bankwezen] ons heeft geleid', schreef Hayek. 'Het zou voorwaarden creëren waarbij de verantwoordelijkheid voor het beheren van de hoeveelheid valuta wordt gelegd op agentschappen wiens eigenbelang hen ertoe zou aanzetten het op zo'n manier te beheren dat het voor de meeste gebruikers het meest acceptabel is.'[^97]

In een wereld waar banken en andere financiële instellingen in de loop der tijd afhankelijk waren geworden van een sterk gereguleerd en nauw verweven financieel systeem, en waar het buitengewoon moeilijk was om zinvolle veranderingen aan te brengen, betekende Hayeks oplossing een nieuwe start. Hij stelde voor om een marktgebaseerd monetair systeem uit te rollen naast de gevestigde financiële sector, om zo een volledig nieuw valutasysteem te laten ontstaan als mensen het vrijwillig zouden adopteren.

Hayek zag geld als een spontane orde.

## Het realiseren van vrij bankieren

Hoewel de meeste landen technisch gezien alternatieve valuta toestaan (er zijn doorgaans geen wetten die ze expliciet illegaal maken) wordt dit vaak niet weerspiegeld in de praktijk. Bankregulaties, vergunningen voor geldtransfers, antiwitwasregels, wetten tegen vervalsing evenals belastingen (zoals vermogenswinstbelasting op alternatieve valuta) bieden wetshandhavingsinstanties meer dan voldoende middelen om bedrijven die valuta uitgeven compleet te sluiten, en hun operators veroordeeld te krijgen, of op zijn minst maken ze het opereren van dergelijke bedrijven praktisch onmogelijk.

Hayek wist dat het volledig elimineren van al deze wettelijke en fiscale obstakels -- ware deregulatie -- op enorme tegenstand zou stuiten.

Het merendeel van deze weerstand, verwachtte hij, zou afkomstig zijn van overheden: precies dezelfde partijen die deze deregulering uiteindelijk moesten doorvoeren en juridisch de ruimte voor valutaconcurrentie moesten faciliteren. Hayek was van mening dat overheden elke reden hadden om dit te voorkomen: zij waren de grootste begunstigden van het fiatgeldsysteem en hadden in feite het monopolie op geld. Hayek geloofde dat als overheidsvaluta moesten concurreren met vrijemarktvaluta, deze geen schijn van kans zouden hebben, en overheden dus waarschijnlijk niet tevreden zijn met vrije banken.

Om het nog moeilijker te maken, zou het merendeel van de economen waarschijnlijk ook tegen zijn, voorzag Hayek. Geld van de vrije markt zou immers waarschijnlijk elke kans op het manipuleren van rentetarieven om de koopkracht van de munteenheid te beïnvloeden en deflatie te voorkomen, elimineren. De meeste economen van de jaren '70 waren van mening dat overheidsinstellingen zoals de Federal Reserve een belangrijke rol speelden bij het beheer van de geldvoorraad.

'Ik vrees dat *Keynesiaanse* propaganda doorgedrongen is tot de massa, [en] inflatie respectabel heeft gemaakt en onruststokers heeft voorzien van argumenten die de professionele politici niet kunnen weerleggen', schreef Hayek gefrustreerd.[^98]

Hayek, de Oostenrijkse econoom, voegde nog toe dat hij verwachtte dat de meeste van de huidige banken ook tegen de verandering zouden zijn. De 'oude bankiers', zoals hij ze noemde, zouden niet in staat zijn om de nieuwe uitdagingen aan te kunnen die een vrije bankensector op hen zou zetten.

'Vooral in landen waar de concurrentie tussen banken al generaties lang wordt beperkt door kartelafspraken, die meestal worden getolereerd en zelfs aangemoedigd door overheden, zou de oudere generatie bankiers waarschijnlijk totaal niet in staat zijn om zich voor te stellen hoe het nieuwe systeem zou werken en daarom in de praktijk unaniem zijn in het afwijzen ervan', schreef Hayek.[^99]

Met overheden, economen en bankiers als voorziene tegenstanders, verwachtte Hayek zeker dat het realiseren van vrij bankieren een moeilijke strijd ging zijn, maar toch geloofde hij sterk dat het desondanks gedaan moest worden.

Hayek schreef in de tweede, verfijnde versie van zijn boek: '[Denationalisatie van geld is] de enige manier waarop we nog kunnen hopen om de voortdurende vooruitgang van alle overheidssturing richting totalitarisme te stoppen, wat voor veel scherpzinnige waarnemers onvermijdelijk lijkt. Maar de tijd dringt. Wat nu dringend nodig is, is niet de bouw van een nieuw systeem, maar het snel verwijderen van alle wettelijke obstakels die al tweeduizend jaar de weg hebben geblokkeerd naar een evolutie die ongetwijfeld gunstige resultaten zal opleveren die we niet kunnen overzien.'[^100]

En hij geloofde dat het mogelijk was. De sleutel lag bij het winnen van de steun van de algemene bevolking. Hayek maakte een vergelijking met de vrijhandelsbewegingen uit de negentiende eeuw en stelde dat een nieuwe burgerbeweging, een *vrij geld-beweging*, mensen zou kunnen informeren over de schade die inflatie en valutamanipulatie veroorzaken. Een bredere publieke bewustwording van deze kwesties zou een solide basis kunnen vormen voor de zaak. De daadwerkelijke politieke verandering (de deregulering van de bankensector) werd verondersteld in een later stadium te volgen.

Opgericht door onderzoekers George Selgin, Lawrence White, en Kevin Dowd een paar jaar later, in de jaren '80, kwam de moderne vrije-bankenschool waarschijnlijk het dichtst in de buurt van het opzetten van zo'n beweging. De door Hayek geïnspireerde lobbygroep deed onderzoek naar de geschiedenis en het potentieel van vrije banken en publiceerde hun bevindingen in verschillende boeken en artikelen.

Maar hoewel de moderne vrije-bankenschool een kleine aanhang kreeg van gelijkgestemde, meestal Oostenrijkse, economen, slaagde het er niet in om de harten en de geesten van het grote publiek te winnen. Hoewel Hayek nog lang genoeg leefde om een nieuwe generatie politici en economen zijn werk over vrije markten en het prijssysteem te zien herontdekken en revitaliseren, tot het hem zelfs de Nobelprijs voor economie opleverde in 1976, bleef Hayeks oproep voor monetaire hervorming onbeantwoord. fiatvaluta bleef oppermachtig tot, in 1992, Hayek op tweeënnegentig jarige leeftijd stierf.

Toch waren zijn ideeën niet volledig vergeten.

Het werk van Hayek op het gebied van geld diende kort na zijn overlijden als inspiratie voor een groep hackers en cryptografen uit Californië. Maar deze hackers en cryptografen waren niet van plan om politici, economen en bankiers te overtuigen om de wet te veranderen.

Ze gingen een toekomst bouwen zonder hen...

[^79]: ​Edward S. Mason and Robert E. Asher, *The World Bank Since Bretton Woods: The Origins, Policies, Operations and Impact of the International Bank for Reconstruction*, 29.

[^80]: ​Andrew F. Brimmer, *Remembering William McChesney Martin Jr.*, Federal Reserve Bank of Minneapolis, 1 september 1998, [online](https://www.minneapolisfed.org/article/1998/remembering-william-mcchesney-martin-jr.)

[^81]: ​Wapshott, *Keynes & Hayek*, 242.

[^82]: ​Wapshott, *Keynes & Hayek*, 242.

[^83]: ​Richard Nixon, *Address to the Nation Outlining a New Economic Policy: 'The Challenge of Peace'*, 15 augustus 1971.

[^84]: ​Michael J. Graetz and Olivia Briffault, *A 'Barbarous Relic': The French, Gold, and the Demise of Bretton Woods*, in The Bretton Woods Agreements, eds. Naomi Lamoreaux and Ian Shapiro: 121--142.

[^85]: Federal Reserve Economic Data, *Consumer Price Index for All Urban Consumers*, beschikbaar [online](https://fred.stlouisfed.org/series/CPIAUCSL)

[^86]: ​Friedrich A. Hayek, *Can We Still Avoid Inflation?* in *The Austrian Theory of the Trade Cycle and Other Essays*, ed. Richard M. Ebeling: 101.

[^87]: ​Mark Blaug, *Economic Theory in Retrospect*, 4th edition, 20--23.

[^88]: ​Hayek, *Prices and Production*, 203.

[^89]: ​Hayek, *Can We Still Avoid Inflation?* 108.

[^90]: Friedrich A. Hayek, *Denationalisation of Money*, 89.

[^91]: Friedrich A. ​Hayek, *Denationalisation of Money*, 91.

[^92]: ​Friedrich A. Hayek, *Denationalisation of Money: The Argument Refined*, 13.

[^93]: Opnieuw gepubliceerd in Friedrich A. Hayek, *Choice in Currency: A Way to Stop Inflation*.

[^94]: Friedrich A. Hayek, *The Argument Refined*, 78.

[^95]: Friedrich A. Hayek, *The Argument Refined*, 83.

[^96]: Friedrich A. Hayek, *The Argument Refined*, 109.

[^97]: Friedrich A. Hayek, *The Argument Refined*, 77.

[^98]: Friedrich A. Hayek, *The Argument Refined*, 133.

[^99]: Friedrich A. Hayek, *The Argument Refined*, 93.

[^100]: Friedrich A. Hayek, *The Argument Refined*, 134.
