# RPOW

In het begin van de jaren 2000 had de Cypherpunk-beweging het grootste deel van zijn momentum verloren.

Terwijl sommige van de oorspronkelijke Cypherpunks gedesillusioneerd raakten en stopten met deelnemen aan de Cypherpunk-mailinglijst, ging de algehele kwaliteit van dit discussieplatform achteruit, met veel nieuwe berichten die weinig meer waren dan gescheld en schreeuwpartijen, of zelfs regelrechte spam. John Gilmore, de oorspronkelijke host van de lijst, had eind jaren 1990 geprobeerd om een moderatiebeleid te introduceren, maar dit werd streng afgewezen door mensen zoals Tim May, die zich in reactie daarop uitschreef (May keerde terug toen het beleid werd aangepast om boze berichten en andere inhoud van lage kwaliteit om te leiden in plaats van te censureren, hoewel hij nog steeds niet blij was met de veranderingen).[^242]

Gilmore besloot uiteindelijk te stoppen met het hosten van de mailinglijst, waarna enkele van de overgebleven abonnees nieuwe groepen creëerden en overstapten naar Usenet, die op een meer verspreide manier konden worden gehost door meerdere mensen tegelijk.[^243] Desalniettemin, zou het verval van de beweging alleen maar versnellen. Na de terroristische aanslagen van 11 september 2001, maakte een scherpe toename van digitale surveillance mensen huiverig om discussies over radicale privacytools te faciliteren, en toen de enige resterende Cypherpunk-server werd gehost vanaf het webadres al-qaeda.net, besloot zelfs Tim May dat het tijd was om te vertrekken. Dit keer, voorgoed.

Dat betekende niet dat de Cypherpunk-ethos verloren of volledig vergeten was. Velen van de cypherpunks behielden hun interesse in bestaande privacytools zoals PGP, evenals in nieuwe technologieën zoals Tor (The Onion Router): het privacy-netwerk dat in 2002 werd gelanceerd leek op Zero-Knowledge Systems' Freedom, maar vereiste geen betaald abonnement. Tor stelde iedereen in staat om anoniem het internet te gebruiken.

Veel van de Cypherpunks bleven ook in contact via andere middelen. Online migreerden nogal wat van hen uiteindelijk naar de strikter gemodereerde Cryptografie mailinglijst, die soms werd beschouwd als de feitelijke opvolger van de Cypherpunk-lijst. Offline liepen enkele van de Cypherpunks elkaar regelmatig tegen het lijf op cryptografieconferenties of hackerevenementen.

Ondertussen ontstonden vele andere initiatieven voor elektronisch geld. Rond de overgang van het millennium werkten honderden start-ups aan online betalingssystemen, en veel van deze bedrijven omschreven hun oplossingen als een vorm van digitaal geld. Hoewel dat vaak gewoon betekende dat de betaalsystemen snel, goedkoop en gemakkelijk te gebruiken waren, waren ze niet per se privé. CyberCash, bijvoorbeeld, trok veel media-aandacht voor zijn digitaal geldsysteem, genaamd CyberCoin, dat zich specialiseerde in kleine betalingen in plaats van anonimiteit. Hetzelfde gold voor het systeem van elektronisch geld van Compaq, dat veel aandacht trok, genaamd Millicent.

Andere initiatieven die enig potentieel toonden, zoals n-Count (medeontworpen door een voormalige werknemer van DigiCash), Proton (een project van samenwerkende Europese banken), of Mondex (een initiatief van de Britse bank NatWest dat later werd verkocht aan Mastercard), waren vooral gebaseerd op het concept van fysieke smartcards. Net zoals de smartcard die in ontwikkeling was bij de start-up van David Chaum, moesten deze stukken hardware (gelijkend aan een kredietkaart) vooraf geladen worden met een waarde die fiatvaluta vertegenwoordigde, om vervolgens te worden gebruikt voor persoonlijke transacties. Hoewel de meeste van deze privacyfuncties aanboden, waren ze vooral ontworpen om fysiek geld te vervangen in plaats van te dienen als anonieme valuta voor cyberspace.

Misschien nog dichter bij de visie van de Cypherpunks, richtte Robert Hettinga, die sinds 1996 de jaarlijkse Financial Cryptography conferenties had georganiseerd, in 1999 de Internet Bearer Underwriting Corporation op. Na het falen van DigiCash, wilde deze Cypherpunk financiering veiligstellen om een nieuw soort eCash-systeem te ontwikkelen, maar deze keer geoptimaliseerd voor goedkope transacties. Hij was van mening dat sterke privacygaranties niet alleen individuen beschermen tegen Big Brother, maar dat ze ook de wrijving kunnen verminderen en dus economische voordelen kunnen opleveren.

Maar geen van deze projecten heeft haar beloftes kunnen waarmaken. Hoewel sommige technologieën banenbrekend waren in specifieke sectoren, zoals het openbaar vervoer of voor betaalkaarten voor telefooncellen, slaagde digitaal geld er niet in om veel aantrekkingskracht te winnen bij het algemene publiek. Door het gebrek aan interesse begon de financiering ook te verminderen.

'Eerlijk gezegd is het dot-com geld verdwenen', concludeerde Hettinga in 2001, nadat hij er niet in geslaagd was genoeg geld op te halen om het elektronische geldsysteem van zijn bedrijf te ontwikkelen. 'We gaan ook over terrein waar CyberCash, DigiCash en veel andere mensen hun vingers aan verbrand hebben.'[^244]

In plaats van het investeren in nieuwe crypto-initiatieven, richtten traditionele banken en financiële dienstverleners zich op het verbeteren van bestaande cashloze betalingsystemen, zoals transacties via creditcards en betaalpassen. Intussen wonnen flamboyante nieuwe web-gebaseerde betalingsverwerkers zoals PayPal snel aan marktaandeel en het leek erop dat privacy (laat staan ​​monetaire hervorming) geen grote zorg was voor de meesten van hen. De dystopische toekomst waar Chaum en veel van de Cypherpunks voor gewaarschuwd hadden (een toekomst waarin alle financiële transacties konden worden gemonitord, geregistreerd en mogelijk gecensureerd) werd snel realiteit.

Toch was niet iedereen bereid de hoop op te geven...

## Hal Finney

Geboren in het voorjaar van 1956 in het kleine Californische dorpje Coalinga, toonde Hal Finney al vroeg, nog als een jong kind, een interesse in codes: op de basisschool, vond hij het leuk om codes met letters en cijfers te maken voor willekeurige teksten die hij tegenkwam.

Iets later, in zijn tienerjaren, ontwikkelde Hal een fascinatie voor computers. Gelukkig was de middelbare school die hij bezocht zijn tijd ver vooruit: de schooladministratie maakte al gebruik van een computer voor het beheer en de opslag van leerlinggegevens jaren voordat dit gebruikelijk werd. Jonge Hal, enthousiast om met de machine te werken, bood vrijwillig zijn hulp aan het schoolpersoneel aan, waardoor hij tussen de lessen door een soort bijbaantje kreeg.

Finney behaalde in 1974 zijn middelbareschooldiploma als beste student van zijn klas en werd toegelaten tot het California Institute of Technology (Caltech), één van de meest prestigieuze en selectieve universiteiten ter wereld. Omdat Caltech toen nog geen bacheloropleiding in informatica aanbood, besloot hij een opleiding in techniek te volgen, terwijl hij tegelijkertijd zoveel mogelijk programmeercursussen volgde.

Rond dezelfde tijd ontwikkelde Finney een sterke waardering voor logica en omarmde hij de libertaire filosofie. Hij ging graag filosofische discussies aan met zijn medestudenten aan de universiteit, waar een combinatie van prikkelende ideeën, stevige argumentaties en een bedachtzame benadering van gesprekken hem veel aandacht opleverde van zijn leeftijdsgenoten. Onder hen was Fran, het meisje met wie hij later zou trouwen en de rest van zijn leven zou doorbrengen.

Kort na zijn afstuderen aan Caltech in 1978, vond Finney zijn eerste serieuze baan als programmeur bij een kleine ingenieursfirma APh Technological Consulting. APh was zojuist een samenwerking gestart met speelgoedfabrikant Mattel om het besturingssysteem voor hun Intellivision-spelcomputer te ontwikkelen, naast een aantal vroege spellen. In de daaropvolgende jaren zette Finney zijn werk voort in het ontwikkelen van baanbrekende videogames zoals *Space Battle* en *Star Strike* voor de Intellivision, alsook *Adventures of Tron*, *Astroblast!* en *Space Attack* voor het Atari Video Computersysteem.

Als algemeen optimistisch mens, was Finney ervan overtuigd dat de wereld van morgen beter zou zijn dan die van vandaag, en stond hij open voor verandering. Dus toen de Extropiaanse-gemeenschap eind jaren '80 begon te vormen, paste hij er ook goed in. Het vooruitzicht van technologische vernieuwingen zoals nanotechnologie, kunstmatige intelligentie en *mind uploading* maakte hem enthousiast. En als een overtuigd atheïst die niet in het hiernamaals geloofde, was Finney al erg geïnteresseerd in het potentieel van cryonics sinds hij over het concept las tijdens zijn eerste jaar op de universiteit.

Zoals Fran het later zei: 'Hij geloofde niet in God. Hij geloofde in de toekomst.'[^245]

## Cypherpunkrealisme

Toen het internet begin jaren '90 voor het eerst publiek toegankelijk werd, was Finney een van de allereerste gebruikers die zich een verbinding wist te bemachtigen.

Terwijl hij de verschillende, op dat moment enkel op tekst gebaseerde, hoeken van de gloednieuwe informatiesnelweg verkende, herkende Finney al snel het revolutionaire potentieel van het ontluikende digitale domein. Voor het eerst zou de mensheid over de hele wereld verbonden zijn, ongeacht geografische afstanden, willekeurige grenzen of culturele verschillen. Hij geloofde dat de gevolgen hiervan de wereld zouden veranderen.

Maar al snel besefte hij dat er ook een nadeel was aan de digitalisering van communicatie. Als kenner van de technische architectuur van het internet, wist Finney dat zonder beschermende maatregelen, cyberspace rampzalige inbreuken op individuele privacy kon faciliteren: alles dat iemand online doet, kon potentieel bespioneerd worden. Hij voorzag dat het internet eigenlijk een bedreiging voor de menselijke vrijheid kon worden.

Dit was het geval voor gewone communicatie, en Finney dacht dat dit net zo goed opging voor financiële transacties.

'Er kunnen dossiers worden gemaakt die de uitgavenpatronen van ons allemaal volgen', waarschuwde Finney. 'Als ik nu iets bestel via de telefoon of elektronisch met mijn Visa kaart, wordt er een record bijgehouden van hoeveel ik precies heb uitgegeven en waar ik het heb besteed. Naarmate de tijd vordert, kunnen er meer transacties op deze manier plaatsvinden, en het uiteindelijke resultaat kan een groot verlies aan privacy zijn.'[^246]

Het internet had behoefte aan een ontraceerbare vorm van geld, concludeerde Finney --- digitaal contant geld. En hij was opgetogen te ontdekken dat zo'n systeem al in ontwikkeling was.

'Het leek me zo duidelijk', herinnerde Finney zich later. 'We worden geconfronteerd met problemen zoals het verlies van privacy, oprukkende computarisering, enorme databases en meer centralisatie, en Chaum biedt een volledig andere weg om in te slaan, eentje die macht in handen van individuen legt in plaats van regeringen en bedrijven. De computer kan eerder als instrument gebruikt worden om mensen te bevrijden en te beschermen, in plaats van hen te controleren.'[^247]

Finney had daarom een uitnodiging aanvaard van mede-Extropiaan Tim May, die een ontmoeting organiseerde met een groep lokale hackers en cryptografen uit de Bay Area, die zichzelf spoedig de Cypherpunks zouden noemen.

Kort daarna bevond Finney zich in de positie waar hij Chaums eCash-project aan het promoten was onder zijn mede-Extropianen, en op een bepaald moment daarover een zeven pagina's tellende uitleg voor het *Extropy* magazine schreef. Finney schreef aan de techno-libertarische menigte dat cryptografie individuen kon beschermen tegen overheidsmacht, inmenging, en controle, en legde uit hoe elektronisch geld de Extropiaanse zaak kon bevorderen.

En, als een echte Cypherpunk, schreef Finney code. De game-ontwikkelaar was verantwoordelijk voor een vroeg Cypherpunk-succes toen hij Eric Hughes hielp de allereerste Chaumian remailer te ontwikkelen. Het was ook Finney's idee om de uitdaging te organiseren om de (verzwakte) export-grade encryptiestandaard van Netscape te kraken, een uitdaging die voltooid werd door mede-Cypherpunk Ian Goldberg. Dit bleek een grote overwinning tijdens de crypto-oorlogen.

Maar Finney's meest opmerkelijke bijdragen vielen ten goede aan PGP: nadat Phil Zimmermann voor het eerst de encryptietool had uitgebracht, werd Finney een belangrijke bijdrager aan het project. De tweede versie van de software, een grote verbetering ten opzichte van versie 1, werd grotendeels door hem ontwikkeld, hoewel dit een beetje stil werd gehouden om Finney te behoeden voor mogelijke juridische problemen zoals Zimmermann die ondervond. Een paar jaar later zou Finney de eerste werknemer worden van Zimmermanns PGP-bedrijf.

Finney stond echter niet achter de visie van Tim May om met behulp van Cypherpunk-hulpmiddelen een crypto-anarchistische samenleving te stichten.

Dit was niet omdat hij het idee om de staat uit economische interacties te verwijderen niet leuk vond, of omdat de ideeën van May op dat vlak te radicaal voor zijn smaak waren. Als een Extropiaan en libertariër vond Finney in feite dat Mays visie in principe geweldig klonk. Hij geloofde echter niet dat Mays idee om een anarchistische samenleving te bereiken door middel van cryptografie erg realistisch was.

'[...] er bestaat niet zoiets als cyberspace', schreef Finney op een gegeven moment aan de mailinglijst van de Cypherpunks in reactie op een van de betogen van May. 'Ik ben nu niet in cyberspace, ik ben in Californië. Ik val onder de wetten van Californië en de Verenigde Staten, ook al communiceer ik met een andere persoon, of het nu per post of elektronisch is, via telefoon of TCP/IP-verbinding. Wat betekent het om te spreken over een regering in cyberspace? Het is de regering in de fysieke ruimte die ik vrees. Haar agenten dragen fysieke wapens die echte kogels afvuren. Totdat ik in mijn computer kan leven en elektronen kan eten, zie ik de relevantie van cyberspace niet in.' [^248]

Hoewel individuen Cypherpunk hulpmiddelen konden gebruiken om hun privacy te beschermen, geloofde Finney niet dat de meeste mensen hun hele leven zich in cyberspace zouden kunnen *verbergen*. Zelfs als Cypherpunk-hulpmiddelen een kleine groep technisch onderlegde elite zouden kunnen helpen om bepaalde wetten te omzeilen, verwierp hij de gedachte dat dit de beschaving ingrijpend zou veranderen, omdat hij uiteindelijk niet geloofde dat een libertaire samenleving gerealiseerd kon worden zonder wijdverspreide steun van de bevolking.

In plaats van een anarchistisch utopia om naar te migreren, zag Finney het internet eerder als een plek voor intellectuele uitwisseling: in plaats van een Galt's Gulch, zag hij cyberspace als een plek om ideeën vrijelijk uit te wisselen en te bediscussiëren. En dit, zo geloofde Finney, was de echte sleutel tot het bereiken van ware vrijheid. De beste en enige manier om een vrije samenleving te creëren was om de massa ervan te overtuigen dat een vrije samenleving een goed idee is.

> 'In de kern geloof ik dat we de soort samenleving zullen hebben die de meeste mensen wensen. Als we vrijheid en privacy willen, moeten we anderen overtuigen dat deze waardevol zijn. Er zijn geen snelkoppelingen. Terugtrekken in technologie is als het over je hoofd trekken van je dekens. Het voelt even goed, totdat de realiteit je inhaalt.'[^249]

## Elektronisch geld

Ondanks zijn nuchtere en misschien wel meer realistische kijk op de mogelijkheden van cryptografie, was Finney altijd gedreven om elektronisch geld te realiseren. Hij voerde uitvoerig gesprekken over de mogelijkheden hiervan met zowel de Extropianen als de Cypherpunks op hun respectievelijke mailinglijsten, en ook op de Libtech mailinglijst van Nick Szabo.

Op de Cypherpunks mailinglijst was hij bij gesprekken over digitale valuta altijd één van de meest actieve deelnemers en nam hij soms zelfs een soort ondersteunende rol aan. Hoewel sommige Cypherpunks hevig konden twisten over de beste benadering van elektronisch geld, stond Finney meer open voor verschillende ideeën. In plaats van vast te houden aan één oplossing, gaf hij liever een overzicht van de verschillende compromissen die elk van hen met zich meebracht.

Finney leek bijvoorbeeld grotendeels onbeslist, of misschien beter gezegd, open-minded over het onderwerp van dekking. Hij merkte op dat het dekken van elektronisch geld met fiatvaluta werkte, maar speculeerde soms ook over digitale valuta's gedekt door een mandje van goederen, of door een synthetisch gemiddelde van meerdere nationale valuta's, of helemaal niet gedekt.

Elke keer wanneer een nieuw voorstel voor elektronisch geld opdook op de mailinglijst, was Finney altijd enthousiast om het te beoordelen, met een speciale nadruk op hun privacyfuncties. Na het bestuderen van het ontwerp, koppelde hij vaak terug op de mailinglijst om in zijn eigen woorden uit te leggen hoe het werkte, hoe het zich verhield tot eerdere voorstellen, en wat hij van het idee vond. Naast (meestal constructieve) feedback voor de indiener, bood Finney aan andere Cypherpunks in wezen een openbare dienst door hen te helpen de mogelijkheden en beperkingen van verschillende benaderingen te begrijpen.

Finney had ook een speciale interesse in de wettelijkheid van elektronisch geld, een onderwerp dat hem in de begindagen van de Cypherpunk-gemeenschap naar de geschiedenis van het geld leidde. Hier kwam hij voor het eerst het werk van George Selgin over vrij bankieren tegen. Terwijl hij wetten over wettig betaalmiddel, belastingregels, bankregulering en meer bestudeerde, deelde Finney zijn bevindingen op de mailinglijst van de Cypherpunks en begon hij de mogelijkheden en risico's in kaart te brengen (het was bijvoorbeeld Finney die ontdekte dat niet-commerciële experimenten voor systemen zoals eCash getolereerd zouden moeten worden, zelfs als ze gebruik maakten van Chaums gepatenteerde blinde handtekeningenschema).

Tegelijkertijd stelde Finney zich terughoudend op tegenover enkele uitspraken, geïnspireerd door crypto-anarchie, over de beloften van elektronisch geld. Ook hier was hij sceptisch over enkele van de meer radicale voorspellingen met betrekking tot massale belastingontduiking en hoe elektronisch geld dit zou mogelijk maken.

'We zijn verblind door het beeld van monetaire stromen die over de hele wereld flitsen. Wat ik echter nooit precies kan plaatsen is, wat precies verhindert dat zoiets vandaag de dag wordt gedaan?' vroeg Finney aan de mailinglijst. 'Als je in goud wilt investeren, kun je toch naar de goudhandelaar gaan en wat kopen? Of je kunt je geld in een beleggingsfonds in goud stoppen en het als een betaalrekening gebruiken. Als je yen of marken wilt, kun je daarin investeren. Als het punt is om dit in het geheim te doen, waarom zou het dan gemakkelijker zijn om je salaris per post naar de digicash-bank in de Bahamas te sturen dan naar een bestaande bank daar?'[^250]

Ook hier was het niet zo dat Finney de meer radicale beloftes van Tim May onaantrekkelijk vond. Hij beschouwde ze gewoon als niet erg realistisch. Afgezien van het feit dat de meeste mensen hun belastingen toch al rechtstreeks van hun salaris betaalden, moest iedereen uiteindelijk in de fysieke wereld leven, waar belastingontduiking nog steeds illegaal zou zijn. Het was voor Finney verre van duidelijk dat het verbergen van rijkdom in cyberspace de meeste mensen in het echte leven ten goede zou komen.

'Het lijkt mij dat de zwakte in deze plannen om de overheid te omzeilen met digitaal geld zit in de omzetting van fysiek geld naar digitaal geld. Dat lijkt het knelpunt te zijn waar de overheid nog steeds controle kan houden', concludeert Finney.[^251]

## Herbruikbare proofs-of-work

In de jaren 2000, ongeveer tien jaar nadat Finney bij Extropianen begon te pleiten voor elektronisch geld, was er nog steeds geen succesvol elektronisch geldsysteem. Hoewel een reeks ideeën besproken was op de mailinglijst van de Cypherpunks, en Finney veel van de voorstellen persoonlijk had beoordeeld, was geen van hen van de grond gekomen. In sommige gevallen, zoals bij de start-ups van Chaum of Hettinga, was dit omdat het product uiteindelijk commercieel niet haalbaar bleek te zijn, of althans zo leek het. Maar in andere gevallen, zoals bij het Bit Gold van Nick Szabo of de b-money voorstellen van Wei Dai, waren de systemen in de eerste plaats nooit geïmplementeerd.

Wellicht was het omdat zijn verwachtingen voor het potentieel van elektronisch geld meer ingetogen waren dan die van Tim May en andere crypto-anarchisten in de eerste plaats, of misschien was het gewoon vanwege zijn over het algemeen optimistische karakter, maar waar vele andere Cypherpunks tegen deze tijd ontgoocheld waren geraakt, wilde Finney het idee nog een kans geven. Hij besloot uiteindelijk om een op proof-of-work gebaseerd elektronisch geldsysteem te ontwikkelen, zelfs als het in een vereenvoudigde vorm moest.

In 2004 lanceerde hij *Reusable Proofs of Work*, of kortweg *RPOW* (uitgesproken als *arpow*). Hij nodigde mensen uit om het systeem te testen, adverteerde het elektronische geld op een eenvoudige blauw-groene webpagina met een RPOW-logo in stripboekstijl (denk aan de 'POW' letters die de plek markeren waar Batmans uppercut de kaak van een ongelukkige handlanger raakt).

'Beveiligingsonderzoeker Nick Szabo heeft de term bit gold bedacht om een soortgelijk concept van tokens, dat inherent een bepaald niveau van inspanning vertegenwoordigt, te omschrijven', schreef Finney op de website van het project. 'Het concept van Nick is complexer dan het eenvoudige RPOW-systeem, maar zijn inzicht is van toepassing: op sommige manieren kun je een RPOW-token zien als het hebben van de eigenschappen van een zeldzame grondstof zoals goud. Het kost moeite en uitgaven om goud te delven en munten te slaan, waardoor ze inherent zeldzaam zijn.'[^252]

Waar Bit Gold was ontworpen rondom een *eigendomsclub*, zou ook RPOW beheerd worden door specifieke servers. Voor het prototype had Finney zelf een RPOW-server opgezet. Deze voerde de basisbewerkingen uit die nodig zijn voor het elektronische geldsysteem: het gaf nieuwe RPOW-tokens uit (de munteenheden), en controleerde of tokens niet twee keer werden uitgegeven.

Het is belangrijk te vermelden dat de RPOW-server alleen nieuwe tokens uitgaf als aan één van de twee voorwaarden was voldaan: er moest een geldige hash worden ingediend, of een oudere token moest worden ingeleverd als ruil.

De eerste optie was een eenvoudige proof-of-work functie. Als gebruiker Alice een RPOW-token wilde, moest ze verbinding maken met Finney's server (mogelijk via Tor voor optimale privacy), een aantal gegevens die uniek zijn voor de server en voor haarzelf nemen, en beginnen met hashen tot ze een geldige hash (beginnend met genoeg nullen) vond. Vervolgens stuurt ze de hash naar de server, die deze op geldigheid controleert, en (indien geldig) een unieke RPOW-token terugstuurt, in feite gewoon een unieke gegevensreeks. De server bewaarde ook een kopie van de token in een lokale database.

Wanneer Alice een RPOW-token wilde uitgeven, bijvoorbeeld om een MP3-bestand te kopen, zou ze het simpelweg naar de beoogde ontvanger, Bob, sturen. Technisch gezien maakte het voor het RPOW-systeem niet uit hoe ze het verzond, zolang ze er maar zeker van was dat het bij Bob terechtkwam zonder dat iemand het onderschepte (een bericht aan Bob versleuteld met zijn publieke sleutel zou de klus klaren).

Wanneer Bob de RPOW-token ontving, zou hij deze moeten valideren en controleren dat deze niet dubbel was uitgegeven. Hij zou daarom de token direct doorsturen naar de RPOW-server, die naging of de token in de interne database stond en of deze niet dubbel was uitgegeven. Als de token geldig was, zou de server dit aan Bob bevestigen. Hierdoor kon Bob het MP3-bestand naar Alice sturen. De server zou ook de RPOW-token als uitgegeven bestempelen, waardoor deze in de toekomst niet meer gebruikt kon worden.

Ten slotte zou de server Bob een nieuw RPOW-token geven, en die nieuwe token opnemen in zijn interne database. Op deze manier kon Bob de nieuwe token later uitgeven.

Stel je voor dat Bob zijn nieuwe RPOW-token wil gebruiken om toegang te krijgen tot Carols website. Als Carol de RPOW-token van Bob krijgt, stuurt ze hem weer door naar de RPOW-server van Finney. De server bevestigt dan dat de token echt is, markeert deze als besteed in zijn interne database en geeft vervolgens een nieuwe RPOW-token uit aan Carol. Deze wordt ook toegevoegd aan de interne database van de server.

Op deze manier kon het proof-of-work, vertegenwoordigd door een enkele geldige hash (gemaakt door Alice), effectief oneindig blijven circuleren. Het was inderdaad *herbruikbaar* proof-of-work.

## Betrouwbaar rekenen

Het systeem zoals tot dusver beschreven zou vrij goed werken, behalve dat het vertrouwen vereist in de beheerder van de RPOW-server om geen dubbele uitgaven te doen of RPOW-tokens voor zichzelf te maken zonder een proof-of-work te leveren. Finney wilde echter niet dat de gebruikers de beheerder van de RPOW-server moesten vertrouwen, zelfs als die beheerder hijzelf was. Daarom voegde Finney nog een speciale eigenschap toe aan het ontwerp.

Ten eerste zou de RPOW-server gebruik maken van gratis en open source software. Iedereen kon online de broncode van RPOW vinden en controleren hoe het functioneerde.

En, als hoofdinnovatie van het systeem, was de RPOW-server gehost op een veilige hardwarecomponent, de IBM 4758. Dit maakte *betrouwbaar rekenen* mogelijk.

Kortom, de sabotagebestendige hardware bevatte een geheime sleutel, ingebed door IBM, die niemand, zelfs niet de eigenaar van de veilige hardwarecomponent, kon manipuleren of eruit kon halen. Met behulp van een techniek die *remote attestation* wordt genoemd, kon de geheime sleutel vervolgens de gratis en open source software die op de veilige hardwarecomponent was geïnstalleerd, cryptografisch ondertekenen. Met deze handtekening en de bijbehorende publieke sleutel van IBM kon iedereen verifiëren dat de veilige hardwarecomponent daadwerkelijk de RPOW-broncode uitvoerde die Finney had gepubliceerd, zonder achterdeuren of aanpassingen.

Zolang men IBM vertrouwde om niet mee te werken met Finney om een valse handtekening te fabriceren (en aannemende dat de centrale server niet volledig offline ging), konden RPOW-gebruikers er zeker van zijn dat het elektronische geldsysteem functioneerde zoals het moest.

'[...] Het RPOW-systeem is ontworpen met één overkoepelend doel: het onmogelijk maken dat iemand, zelfs de eigenaar van de RPOW-server of zelfs de ontwikkelaar van de RPOW-software, in staat zou zijn om de regels van het systeem te overtreden en RPOW-tokens te vervalsen', legde Finney uit op de RPOW-website. 'Zonder zo'n garantie tegen vervalsbaarheid, zouden RPOW-tokens het werk dat is gedaan om ze te creëren niet geloofwaardig kunnen vertegenwoordigen. Vervalsbare tokens zouden meer lijken op papiergeld dan op bit-goud.'[^253]

## Het lot van RPOW

De eerste RPOW-release was weliswaar nog erg ruw, maar Hal Finney had het voornemen het project in de loop van de tijd te verbeteren. Wellicht het belangrijkst, hij plande om het systeem te upgraden zodat het op meerdere, onafhankelijk van elkaar opererende, servers zou draaien. Zo zou het volledige RPOW-systeem niet onderuit gaan als zijn server om welke reden dan ook offline ging.

Ondertussen vond de Cypherpunk het ook leuk om te experimenteren en te sleutelen aan de RPOW-software. Zo heeft hij bijvoorbeeld een BitTorrent-client aangepast om samen te werken met zijn elektronische geldsysteem. Dit leek op het Mojo Nation concept en stelde gebruikers in staat om andere gebruikers te betalen als ze hun download wilden versnellen. In een even creatieve toepassing van de RPOW-technologie werkte hij aan een peer-to-peer pokerapplicatie. Hier konden gebruikers tegen elkaar spelen, waarbij de RPOW-tokens automatisch naar de digitale portemonnee van de winnaar werden overgemaakt.

Finney kreeg al snel hulp van een jongere ontwikkelaar genaamd Gregory Maxwell, die een actieve interesse toonde in het elektronische geldsysteem. Maxwell droeg bij aan het project met code, en overwoog om geavanceerde bestedingsvoorwaarden zoals escrow-betalingen te implementeren. Hij besprak met Finney ook mogelijke oplossingen voor sommige van de meer subtiele technische uitdagingen, zoals het instellen van vervaltermijnen voor tokens, of de relatief zwakke versleuteling die de veilige hardwarecomponent beveiligde.

Helaas voor Finney bleek Maxwell echter een zeldzame uitzondering. Omdat bijna niemand anders interesse toonde in het elektronische geldsysteem, lukte het RPOW niet om door te breken.

Dit was waarschijnlijk ten minste gedeeltelijk te wijten aan het feit dat RPOW geen heel goede vorm van geld was. Geconfronteerd met hetzelfde probleem als Adam Backs hashcash, een probleem dat Szabo en Dai geprobeerd hadden op een omslachtige manier op te lossen, zouden computationele verbeteringen het na verloop van tijd goedkoper maken om geldige hashes te genereren, wat suggereert dat de markt uiteindelijk zou worden overspoeld met RPOW-tokens. De verwachting van hoge inflatie werkte ontmoedigend om de RPOW-valuta-eenheden te bezitten.

'Het klopt dat als de Wet van Moore blijft gelden, de kosten voor het vervaardigen van een *proof-of-work*-token exponentieel zullen blijven dalen', gaf Finney toe op de website van het project. 'Maar onthou dat dit geen geld is en niet bedoeld is als een stabiel middel om waarde op te slaan. Het is eerder bedoeld als een gemakkelijk te ruilen representatie van computerrekenkracht.'[^254]

Inderdaad, het elektronische geldsysteem van Finney fungeerde niet zozeer als een breed geaccepteerde waardeopslag of rekeneenheid. Het werd vooral nuttig geacht als ruilmiddel op plaatsen waar hashcash zinvol kon zijn, bijvoorbeeld om te dienen als *postzegels* voor het beperken van spam.

Maar waarschijnlijk slaagde het elektronische geldsysteem er ook niet in om van de grond te komen omdat het de opstartuitdaging niet kon overwinnen. Geld is enkel nuttig als anderen het accepteren als betaalmiddel, maar zonder een economische stimulans om RPOW-tokens bij te houden, hadden de meeste mensen daar geen reden toe. En zonder dat er iemand was die de tokens als betaling accepteerde, was er ook niemand die ze wilde uitgegeven, wat betekende dat er nog minder reden was voor iemand om ze in eerste instantie te accepteren als betaling...

'Het had het probleem dat er min of meer niets was om het voor te gebruiken', concludeerde Maxwell ook, die jaren later terugkeek op het RPOW-project, 'wat het moeilijk maakte om de aandacht erop gericht te houden.'[^255]

Net als eCash en hashcash voorheen, leed ook RPOW aan een kip-en-ei-probleem.

## E-gold

Ondanks de beste bedoelingen van Hal Finney is RPOW halverwege de jaren 2000 geëindigd als nog een mislukte poging om elektronisch geld te creëren.

Het was op dit moment dat sommige techno-libertariërs wat nieuw perspectief vonden in een alternatieve vorm van internetgeld, die met een zeer verschillend ontwerp, succesvoller leek te zijn: e-gold.

Het project van Douglas Jackson, een digitale valuta gedekt door goud, groeide rond het midden van de jaren 2000 snel. Het voldeed aan verschillende van de eisen die de Cypherpunks hadden gesteld aan elektronisch geld: transacties konden met enige mate van anonimiteit worden uitgevoerd, het systeem ondersteunde microtransacties tot op één tienduizendste van een gram goud en, natuurlijk, goud zelf vertegenwoordigde onvervalsbare kostbaarheid. Naarmate de technologie van e-gold verbeterde, konden ontwikkelaars zelfs computerprogramma's in het systeem integreren via een Application Programming Interface (API), waardoor oplossingen die op slimme contracten leken mogelijk werden.

Er was natuurlijk één vereiste waaraan e-gold niet kon voldoen. De ervaring met DigiCash's Cyberbucks had de cypherpunks geleerd wat er kon gebeuren met een digitale munteenheid als het afhankelijk was van één enkel bedrijf, en de klanten van Douglas Jackson zouden deze les binnenkort ook leren. Met de arrestatie van de CEO en federale agenten die het kantoor van het bedrijf in 2006 binnenvielen, was er weer een internetvalutaproject mislukt. Szabo's stelling klonk nogmaals luid en duidelijk: *vertrouwde derde partijen zijn veiligheidslekken*.

Na meer dan twintig jaar van niet-gerealiseerde voorstellen, verlaten projecten en mislukte start-ups, bestond er nog steeds geen elektronisch geld.

Intussen werd de noodzaak om een alternatief voor fiatgeld te vinden steeds groter...

[^242]: Tim May, *My Departure, Moderation, and Ownership of the List*, oorspronkelijk verstuurd naar de Cypherpunk-mailinglijst, 2 februari 1997, [online](https://cypherpunks.venona.com/date/1997/02/msg02898.html)

[^243]: ​Mark Frauenfelder, *Homeless Cypherpunks Turn to Usenet*, *Wired*, 17 februari 1997, [online](https://www.wired.com/1997/02/homeless-cypherpunks-turn-to-usenet/)

[^244]: Declan McCullagh, *Digging Those Digicash Blues*, *Wired*, 14 juni 2001, [online](https://www.wired.com/2001/06/digging-those-digicash-blues/)

[^245]: Nicole Weinstock, *Member Profile: Hal Finney*, *Cryonics 40*, issue 2: 9.

[^246]: Hal Finney, *Re: Physical to digital cash, and back again*, oorspronkelijk verstuurd naar de Cypherpunk-mailinglijst, August 19, 1993, accessed via: [https://cypherpunks.venona.com/date/1993/08/msg00581.html]

[^247]: Hal Finney, *Why remailers...*, oorspronkelijk verstuurd naar de Cypherpunk-mailinglijst, 15 november 1992, [online](https://cypherpunks.venona.com/date/1993/08/msg00581.html)

[^248]: Hal Finney, *Re: Voluntary Governments?* oorspronkelijk verstuurd naar de Cypherpunk-mailinglijst, 4 augustus 1994, [online](https://cypherpunks.venona.com/date/1994/08/msg00239.html)

[^249]: Hal Finney, *POLI: Politics vs Technology*, oorspronkelijk verstuurd naar de Cypherpunk-mailinglijst, 2 januari 1994, [online](https://cypherpunks.venona.com/date/1994/01/msg00014.html)

[^250]: Hal Finney, *Re: Re: re: re: digital cash*, oorspronkelijk verstuurd naar de Cypherpunk-mailinglijst, 16 maart 1994, [online](https://cypherpunks.venona.com/date/1994/03/msg00694.html)

[^251]: Finney, *Re: Re: re: re: digital cash*

[^252]: Hal Finney, *Reusable Proofs of Work*, RPOW website index pagina, [online](https://web.archive.org/web/20090217090451/http://rpow.net/index.html)

[^253]: Hal Finney, *RPOW Theory*, RPOW website theorie pagina, [online](https://web.archive.org/web/20040815154951/http://rpow.net/theory.html)

[^254]: Hal Finney, *RPOW FAQs*, RPOW website FAQ pagina, [online](https://web.archive.org/web/20090217090439/http://rpow.net/faqs.html#inflation)

[^255]: Gregory Maxwell, IRC message to author, 13 augustus 2020.
