# Over dit boek {.unnumbered}

Bitcoin is niet uit het niets ontstaan. Gedurende tientallen jaren voorafgaand aan de uitvinding van Satoshi Nakamoto hebben diverse groepen computerwetenschappers, privacyactivisten en niet-traditionele economen geprobeerd een digitale vorm van geld te creëren die onafhankelijk van overheidscontrole kon opereren. Het Genesisboek vertelt het verhaal van de mensen en projecten die de uitvinding van 's werelds eerste succesvolle peer-to-peer elektronisch betaalsysteem inspireerden.

> "Het Genesisboek neemt je mee op een eeuwenlange reis door de minder bekende verhalen van visionairs, wiens inzichten en innovaties de basis vormden voor de revolutionaire creatie van Bitcoin. Van economen die de gevestigde orde uitdaagden tot cypherpunks die nieuwe wegen verkenden op het gebied van privacy, weeft Aaron van Wirdum zorgvuldig een verhaal met technologische overwinningen, tegenslagen en bijzondere doorbraken. De anekdotes over mensen die durfden te dromen buiten de gebaande paden en grenzen verlegden om de financiële wereld te veranderen, zullen je zeker fascineren."
> 
> **— Jameson Lopp**

> "Waarom verschilt Bitcoin zo van eerdere versies? Dit boek werpt licht op de *problemen* die slimme en hardwerkende mensen in de tijd vóór Bitcoin bezig hielden. Dit is de juiste manier om het verhaal van een technologie te vertellen. Alle belangrijke kwesties worden behandeld en ze zijn in een logische volgorde gepresenteerd. Dit is het beste boek over Bitcoin dat ooit geschreven is."
> 
> **— Paul Sztorc**

> "Tot nu toe waren er veel boeken over Bitcoin, maar geen enkel boek pakte de veelzijdige culturele achtergrond zo compleet, gestructureerd en elegant aan. Aaron van Wirdum, bekend om zijn talent om technische materie helder over te brengen naar een breder publiek, heeft dat nu gedaan. Dit is een must-read als je wilt begrijpen waar Bitcoin vandaan komt."
> 
> **— Giacomo Zucco**

> "Ik had al enige tijd het vermoeden dat Van Wirdum de beste historicus van Bitcoin is, en deze pageturner bevestigt dat.
> 
> Het is een indrukwekkend werk. Het Genesisboek biedt een toegankelijk en essentieel overzicht van de geschiedenis, en onthult de vele verbanden tussen het Weense klassiek liberalisme, de Anglo-Saksische cypherpunkbeweging en de opkomst van Bitcoin.
> 
> Waar andere boeken in de branche vaak de nadruk leggen op veelgeprezen ondernemers, heeft Van Wirdum de technische kennis om de belangrijke figuren te belichten die de fundamenten hebben gelegd waarop het Bitcoin-gebouw later is opgericht.
> 
> In zestien informatieve hoofdstukken biedt Het Genesisboek een combinatie van diepgaand onderzoek en filosofische inzichten die je alleen verwacht van een veteraan in de sector (Van Wirdum was een van de eerste schrijvers die in de Bitcoin-industrie aan de slag ging), met de aantrekkelijke schrijfstijl die je zoekt in een gerespecteerd tijdschrift.
> 
> Je kunt Bitcoin niet begrijpen zonder zijn bijzondere oorsprong te leren kennen, en ik ben blij dat dit boek bestaat om die kennis toegankelijk te maken voor een breed publiek."
> 
> **— Tuur Demeester**
