# Bibliografie {.unnumbered}

## Alfabetisch

American Banker. *Digicash Sends Signal by Hiring Visa Veteran.* American Banker. May 6, 1997. <https://www.americanbanker.com/news/digicash-sends-signal-by-hiring-visa-veteran>

Back, Adam. *\[ANNOUNCE\] hash cash postage implementation.* Oorspronkelijk verstuurd naar de Cypherpunk-mailinglijst. March 28, 1997. Beschikbaar op [https://cypherpunks.venona.com/date/1997/03/msg00774.html](https://cypherpunks.venona.com/date/1997/03/msg00774.html).

Back, Adam. *cypherpunks digicash bank?* Oorspronkelijk verstuurd naar de Cypherpunk-mailinglijst. October 7, 1995. Beschikbaar op <https://cypherpunks.venona.com/date/1995/10/msg00690.html>.

Back, Adam. *digital cc transactions, digital checks vs real digital cash.* Oorspronkelijk verstuurd naar de Cypherpunk-mailinglijst. May 2, 1997. Beschikbaar op <https://cypherpunks.venona.com/date/1997/05/msg00104.html>.

Back, Adam. *distributed virtual bank.* Oorspronkelijk verstuurd naar de Cypherpunk-mailinglijst. August 27, 1997. Beschikbaar op <https://cypherpunks.venona.com/date/1997/08/msg01289.html>.

Back, Adam. *no government regulation of the net (was Re: bulk postage fine).* Oorspronkelijk verstuurd naar de Cypherpunk-mailinglijst. August 3, 1997. Beschikbaar op <https://cypherpunks.venona.com/date/1997/08/msg00087.html>.

Back, Adam. *Re: 'why privacy' revisited.* Oorspronkelijk verstuurd naar de Cypherpunk-mailinglijst. March 22, 1997. Beschikbaar op <https://cypherpunks.venona.com/date/1997/03/msg00586.html>.

Back, Adam. *Re: bulk postage fine (was Re: non-censorous spam control).* Oorspronkelijk verstuurd naar de Cypherpunk-mailinglijst. August 3, 1997. Beschikbaar op <https://cypherpunks.venona.com/date/1997/08/msg00070.html>.

Back, Adam. *Re: Bypassing the Digicash Patents.* Oorspronkelijk verstuurd naar de Cypherpunk-mailinglijst. April 30, 1997. Beschikbaar op <https://cypherpunks.venona.com/date/1997/04/msg00822.html>.

Back, Adam. *Re: cypherpunks digicash bank?* Oorspronkelijk verstuurd naar de Cypherpunk-mailinglijst. October 8, 1995. Beschikbaar op <https://cypherpunks.venona.com/date/1995/10/msg00734.html>.

Back, Adam. *Re: Remailer problem solution?* March 23, 1997. Beschikbaar op <https://cypherpunks.venona.com/date/1997/03/msg00631.html>.

Back, Adam. *The Bitcoin Game #59: Dr. Adam Back.* Interview door Rob Mitchell. The Bitcoin Game, YouTube. October 25, 2018. <https://youtu.be/xxYsRjanphA?si=XVdLXPWGUk6oVPXg&t=647%2047:59>.

Barnes, Douglas. *Re: cypherpunks digicash bank?* Oorspronkelijk verstuurd naar de Cypherpunk-mailinglijst. October 8, 1995. Beschikbaar op <https://cypherpunks.venona.com/date/1995/10/msg00731.html>.

Bayer, Dave, Stuart Haber, and Scott W. Stornetta. *Improving the Efficiency and Reliability of Digital Time-Stamping.* Conference Paper, Sequences II: Methods in Communication, Security, and Computer Science (1993): 329--34. <https://www.math.columbia.edu/~bayer/papers/Timestamp_BHS93.pdf>.

BitTorrent. *BitTorrent and µTorrent Software Surpass 150 Million User Milestone; Announce New Consumer Electronics Partnerships.* BitTorrent.com. January 9, 2012. Geraadpleegd via <https://web.archive.org/web/20140326102305/http://www.bittorrent.com/intl/es/company/about/ces_2012_150m_users>

Black Unicorn. *DigiCash Announcement.* Oorspronkelijk verstuurd naar de Cypherpunk-mailinglijst. May 10, 1994. Beschikbaar op <https://cypherpunks.venona.com/date/1994/05/msg00616.html>.

Blaug, Mark. Economic Theory in Retrospect. 4th edition. Cambridge: Cambridge University Press, 1985.

Brafman, Ori and Rod A. Beckstrom. The Starfish and the Spider: The Unstoppable Power of Leaderless Organizations. New York: Portfolio, 2006.

Brimmer, Andrew F. *Remembering William McChesney Martin Jr.,* Federal Reserve Bank of Minneapolis. September 1, 1998. <https://www.minneapolisfed.org/article/1998/remembering-william-mcchesney-martin-jr>

Brunton, Finn. *Digital Cash: The Unknown History of the Anarchists, Utopians, and Technologists Who Built Cryptocurrency*. Princeton, NJ: Princeton University Press, 2019.

Butler, Eamonn. *Hayek: His Contribution to the Political and Economic Thought of Our Time*. New York: Universe Books, 2010.

Caldwell, Bruce and Hansjoerg Klausinger. *Hayek: A Life, 1899--1950*. Chicago: University of Chicago Press, 2022.

Casey, Michael J. *Bitcoin Foundation's Andresen on Working With Satoshi Nakamoto.* The Wall Street Journal. March 6, 2014. <https://www.wsj.com/articles/BL-MBB-17626>

Cave, Damien. *The Mojo solution.* Salon. October 9, 2000. <https://www.salon.com/2000/10/09/mojo_nation/>.

Chaum, David. *Achieving Electronic Privacy.* Scientific American 267, no. 2 (August 1992): 96--101. <https://www.jstor.org/stable/24939181>.

Chaum, David. *Blind Signatures for Untraceable Payments,* Advances in Cryptology: Proceedings of Crypto 82: 199--203. <https://doi.org/10.1007/978-1-4757-0602-4_18>.

Chaum, David. *Security Without Identification: Transaction Systems to Make Big Brother Obsolete.* Communications of the ACM 28, no. 10 (October 1985): 1030--1044. <https://dl.acm.org/doi/10.1145/4372.4373>.

Chaum, David. *Untraceable Electronic Mail, Return Addresses, and Digital Pseudonyms,* Communications of the ACM 24, 2 (February 1981): 84--90. <https://dl.acm.org/doi/10.1145/358549.358563>.

Dai, Wei. *Law vs Technology.* Oorspronkelijk verstuurd naar de Cypherpunk-mailinglijst. February 10, 1995. Beschikbaar op <https://cypherpunks.venona.com/date/1995/02/msg00508.html>.

Dai, Wei. *PipeNet 1.1 and b-money,* Oorspronkelijk verstuurd naar de Cypherpunk-mailinglijst, November 26, 1998, Beschikbaar op <https://cypherpunks.venona.com/date/1998/11/msg00941.html>.

Dai, Wei. *Re: alternative b-money creation.* Oorspronkelijk verstuurd naar de Cypherpunk-mailinglijst. December 11, 1998. Beschikbaar op <https://cypherpunks.venona.com/date/1998/12/msg00448.html>.

Dai, Wei. *Work on Security Instead of Friendliness?* GreaterWrong, July 21, 2012, <https://www.greaterwrong.com/posts/m8FjhuELdg7iv6boW/work-on-security-instead-of-friendliness>.

Dai, Wei. Comment in the discussion thread *AALWA: Ask any LessWronger anything.* LessWrong. 2014. <https://www.lesswrong.com/posts/YdfpDyRpNyypivgdu/aalwa-ask-any-lesswronger-anything>.

Dai, Wei. Untitled b-money description. 1998. Geraadpleegd via <https://web.archive.org/web/20090415130807/https:/www.weidai.com/bmoney.txt>.

Dawkins, Richard. *The Selfish Gene*. Oxford: Oxford University Press, 2016.

De Jong, Eduard. *Electronic Money: From Cryptography and Smart Cards to Bitcoin and Beyond,* Fraunhofer SmartCard Workshop 2017 (2017): 1--10.

Diffie, Whitfield and Martin E. Hellman. *Multiuser Cryptographic Techniques.* AFIPS '76: Proceedings of the June 7-10, 1976, national computer conference and exposition (June 1976): 109--112. <https://dl.acm.org/doi/10.1145/1499799.1499815>.

Diffie, Whitfield and Martin E. Hellman. *New Directions in Cryptography,* IEEE Transactions On Information Theory vol. IT-22, no. 6 (November 1976): 644--654. <https://ieeexplore.ieee.org/document/1055638>.

DigiCash, *Bank Austria and Den norske Bank to Issue ecash™ the Electronic Cash for the Internet.* DigiCash. April 14, 1997. Geraadpleegd via <https://web.archive.org/web/19970605025912/http:/www.digicash.com:80/publish/ec_pres8.html>.

DigiCash. *Advance Bank First to Provide DigiCash's ecash™ System in Australia.* DigiCash. October, 1996. Geraadpleegd via <https://web.archive.org/web/19961102121407/https:/www.digicash.com/publish/ec_pres6.html>.

DigiCash. *DigiCash's Ecash™ to be Issued by Deutsche Bank.* DigiCash. May 7, 1996. Geraadpleegd via <https://web.archive.org/web/19961102121355/https:/www.digicash.com/publish/ec_pres5.html>.

Dillinger, Ray. *Bitcoin P2P e-cash paper,* Oorspronkelijk verstuurd naar de Cryptografie-mailinglijst, November 6, 2008. Beschikbaar op <https://www.metzdowd.com/pipermail/cryptography/2008-November/014822.html>.

Dillinger, Ray. *Bitcoin P2P e-cash paper,* Oorspronkelijk verstuurd naar de Cryptografie-mailinglijst, November 14, 2008, Beschikbaar op <https://www.metzdowd.com/pipermail/cryptography/2008-November/014857.html>.

Dillinger, Ray. *Bitcoin P2P e-cash paper.* Oorspronkelijk verstuurd naar de Cryptografie-mailinglijst. November 15, 2008. Beschikbaar op https://www.metzdowd.com/pipermail/cryptography/2008-November/014859.html.

Dimsdale, Nicholas. *British Monetary Policy and the Exchange Rate 1920-1938.* Oxford Economic Papers 33, New Series (Jul. 1981): 307--49. <https://www.jstor.org/stable/2662793>.

Donald, James A. *Bitcoin P2P e-cash paper,* Oorspronkelijk verstuurd naar de Cryptografie-mailinglijst. November 9, 2008. Beschikbaar op <https://www.metzdowd.com/pipermail/cryptography/2008-November/014837.html>.

Donald, James A. *Bitcoin P2P e-cash paper.* Oorspronkelijk verstuurd naar de Cryptografie-mailinglijst. November 2, 2008. Beschikbaar op <https://www.metzdowd.com/pipermail/cryptography/2008-November/014814.html>.

Donald, James A. *Bitcoin P2P e-cash paper.* Oorspronkelijk verstuurd naar de Cryptografie-mailinglijst. November 3, 2008. Beschikbaar op <https://www.metzdowd.com/pipermail/cryptography/2008-November/014819.html>.

Donald, James A. *Bitcoin P2P e-cash paper.* Oorspronkelijk verstuurd naar de Cryptografie-mailinglijst. November 9, 2008. Beschikbaar op <https://www.metzdowd.com/pipermail/cryptography/2008-November/014841.html>.

Drexler, K. Eric. Engines of Creation. New York: Doubleday, 1986.

Dwork, Cynthia and Moni Naor, *Pricing via Processing or Combatting Junk Mail,* Advances in Cryptology---Crypto '92 (1992): 139--147. <https://dl.acm.org/doi/10.5555/646757.705669>.

Economist, The. *Why Don't Rising House Prices Count Towards Inflation?* The Economist. July 29, 2021. <https://www.economist.com/the-economist-explains/2021/07/29/why-dont-rising-house-prices-count-towards-inflation>

e-gold. *e-gold News.* December 1999, Geraadpleegd via <http://www.e-gold.com/news.html>

e-gold. *e-gold® Welcomes US Government Review of its Status as a Privately Issued Currency.* January 20, 2006. Geraadpleegd via <https://web.archive.org/web/20060322134922if_/https:/www.e-gold.com/letter2.html>

e-gold. *Transcript of sentence before the honorable Rosemary M. Collyer United States District Judge.* 114. November 20, 2008. <https://legalupdate.e-gold.com/2008/11/transcript-of-sentence-before-the-honorable-rosemary-m-collyer-united-states-district-judge.html.>

Energy Exploration & Exploitation. *World Oil Reserves 1948--2001: Annual Statistics and Analysis.* Energy Exploration & Exploitation 19, no. 2 & 3 (2001). <https://journals.sagepub.com/doi/pdf/10.1260/0144598011492561>

Federal Reserve Economic Data. *Consumer Price Index for All Urban Consumers (CPIAUCSL).* Beschikbaar op <https://fred.stlouisfed.org/series/CPIAUCSL>

Finney, Hal. *Bitcoin P2P e-cash paper.* Oorspronkelijk verstuurd naar de Cryptografie-mailinglijst. November 7, 2008. Beschikbaar op <https://www.metzdowd.com/pipermail/cryptography/2008-November/014827.html>.

Finney, Hal. *Bitcoin P2P e-cash paper.* Oorspronkelijk verstuurd naar de Cryptografie-mailinglijst. November 13, 2008. Beschikbaar op <https://www.metzdowd.com/pipermail/cryptography/2008-November/014848.html>.

Finney, Hal. *Bitcoin v0.1 released.* Oorspronkelijk verstuurd naar de Cryptografie-mailinglijst. January 10, 2009. Beschikbaar op <https://www.metzdowd.com/pipermail/cryptography/2009-January/015004.html>

Finney, Hal. *Chaum on the wrong foot?* Oorspronkelijk verstuurd naar de Cypherpunk-mailinglijst. August 22, 1993. Beschikbaar op <https://cypherpunks.venona.com/date/1993/08/msg00652.html.>

Finney, Hal. *Digital Gold, a bearer instrument?* Oorspronkelijk verstuurd naar de Cypherpunk-mailinglijst. August 26, 1993. Beschikbaar op <https://cypherpunks.venona.com/date/1993/08/msg00788.html.>

Finney, Hal. *POLI: Politics vs Technology.* Oorspronkelijk verstuurd naar de Cypherpunk-mailinglijst. January 2, 1994. Beschikbaar op <https://cypherpunks.venona.com/date/1994/01/msg00014.html>.

Finney, Hal. *Protecting Privacy with Electronic Cash.* Extropy 10 (Winter/Spring 1993): 8--14. <http://fennetic.net/irc/extropy/ext10_1.pdf>

Finney, Hal. *Re: Re: re: re: digital cash.* Oorspronkelijk verstuurd naar de Cypherpunk-mailinglijst. March 16, 1994. Beschikbaar op <https://cypherpunks.venona.com/date/1994/03/msg00694.html.>

Finney, Hal. *Re: Voluntary Governments?* Oorspronkelijk verstuurd naar de Cypherpunk-mailinglijst. August 4, 1994. Beschikbaar op <https://cypherpunks.venona.com/date/1994/08/msg00239.html>.

Finney, Hal. *Reusable Proofs of Work.* RPOW website index page. Beschikbaar op <https://web.archive.org/web/20090217090451/http:/rpow.net/index.html.>

Finney, Hal. *RPOW FAQs.* RPOW website FAQ page. Geraadpleegd via <https://nakamotoinstitute.org/rpow/>

Finney, Hal. *RPOW Theory,* RPOW website theory page. Geraadpleegd via <https://nakamotoinstitute.org/finney/rpow/theory.html>

Finney, Hal. *Why remailers...* Oorspronkelijk verstuurd naar de Cypherpunk-mailinglijst. November 15, 1992. Beschikbaar op <https://cypherpunks.venona.com/date/1992/11/msg00108.html>.

Finney, Hal. *Re: Physical to digital cash, and back again.* Oorspronkelijk verstuurd naar de Cypherpunk-mailinglijst, August 19, 1993. Beschikbaar op <https://cypherpunks.venona.com/date/1993/08/msg00581.html>.

Fisher, Irving. The Purchasing Power of Money. New York: The Macmillan Company, 1920.

Forste, Eric Watt. *The Theory of Free Banking (George A. Selgin),* Extropy 15 (2nd--3d Quarter 1995): 51--53. <https://archive.org/details/extropy-15/Extropy-15/>.

Frauenfelder, Mark. *Homeless Cypherpunks Turn to Usenet.* Wired. February 17, 1997. <https://www.wired.com/1997/02/homeless-cypherpunks-turn-to-usenet/>

Friedman, Milton and Anna Schwartz, A Monetary History of the United States. Princeton, NJ: Princeton University Press, 1963.

Gladstein, Alex. *Uncovering The Hidden Costs of the Petrodollar.* Bitcoin Magazine. April 28, 2021. <https://bitcoinmagazine.com/culture/the-hidden-costs-of-the-petrodollar>

GNU Operating System, *What is Free Software?* 1996. <https://www.gnu.org/philosophy/free-sw.en.html>

GNU Operating System. *The GNU Manifesto.* 1985, <https://www.gnu.org/gnu/manifesto.en.html>

Graeber, David. Debt: The First 5,000 Years. New York: Melville House, 2011.

Graetz, Michael J. and Olivia Briffault. *A 'Barbarous Relic': The French, Gold, and the Demise of Bretton Woods.* In The Bretton Woods Agreements, edited by Naomi Lamoreaux and Ian Shapiro, 121--142. New Haven: Yale University Press, 2019.

Grant, Mark. *Introduction to Digital Cash.* Extropy 15 (2nd--3d Quarter 1995): 14--16. <https://archive.org/details/extropy-15/Extropy-15/>

Haber, Stuart and Scott W. Stornetta, *How to Time-Stamp a Digital Document.* Journal of Cryptology 3 (1991): 99--111.

Haber, Stuart and Scott W. Stornetta, *Secure Names for Bit-strings.* CCS '97: Proceedings of the 4th ACM Conference on Computer and Communications Security, (April 1997): 28--35. <https://dl.acm.org/doi/10.1145/266420.266430>

Hayek, Friedrich A. *Can We Still Avoid Inflation?* in The Austrian Theory of the Trade Cycle and Other Essays, edited by Richard M. Ebeling, 93--110. New York: Center for Libertarian Studies, 1978.

Hayek, Friedrich A. *F. A. Hayek on Monetary Policy, the Gold Standard, Deficits, Inflation, and John Maynard Keynes.* Interview door James U. Blanchard III. Re-uploaded by Libertarianism.org on April 19, 2015. <https://youtu.be/EYhEDxFwFRU%2026:27.>

Hayek, Friedrich A. *Intertemporal Price Equilibrium and Movements in the Value of Money,* in The Collected Works of F.A. Hayek, Good Money: part I, edited by Stephen Kresge, 186--227. Indianapolis, IN: Liberty Fund, 2009.

Hayek, Friedrich A. *Monetary Nationalism and International Stability,* in The Collected Works of F.A. Hayek, Good Money: part II, edited by Stephen Kresge, 37--105. Indianapolis, IN: Liberty Fund, 2009.

Hayek, Friedrich A. *Monetary Policy in the United States after the Recovery from the Crisis of 1920,* in The Collected Works of F.A. Hayek, Good Money: part I, edited by Stephen Kresge, 71--152. Indianapolis, IN: Liberty Fund, 2009.

Hayek, Friedrich A. *The Gold Problem,* in The Collected Works of F.A. Hayek, Good Money: part I, edited by Stephen Kresge, 169--85. Indianapolis, IN: Liberty Fund, 2009.

Hayek, Friedrich A. *The Use of Knowledge in Society.* American Economic Review XXXV, no. 4 (1945): 519--530. <https://www.jstor.org/stable/1809376>

Hayek, Friedrich A. Choice in Currency: A Way to Stop Inflation. London: The Institute of Economic Affairs, 1976.

Hayek, Friedrich A. Denationalisation of Money: The Argument Refined. London: The Institute of Economic Affairs, 1990.

Hayek. Friedrich A. Denationalisation of Money. London: The Institute of Economic Affairs, 1976.

Hayek. Friedrich A. Prices and Production. New York: Augustus M. Kelly, Publishers, 1967.

Hettinga, Robert. *Re: Bypassing the Digicash Patents.* Oorspronkelijk verstuurd naar de Cypherpunk-mailinglijst, April 29, 1997. Beschikbaar op <https://cypherpunks.venona.com/date/1997/04/msg00811.html>.

Hettinga, Robert. *Re: digital cc transactions, digital checks vs real digital cash.* Oorspronkelijk verstuurd naar de Cypherpunk-mailinglijst. May 3, 1997. Beschikbaar op <https://cypherpunks.venona.com/date/1997/05/msg00147.html>.

Hill, Austin. Draft document from 2005 shared with author, March 30, 2022.

House of Representatives, *Deleting Commercial Pornography Sites From the Internet: The U.S. Financial Industry's Efforts to Combat This Problem.* Hearing Before the Subcommittee on Oversight and Investigations of the Committee on Energy and Commerce, One-Hundred-Ninth Congress, Second Session. September 21, 2006. <https://www.govinfo.gov/content/pkg/CHRG-109hhrg31467/html/CHRG-109hhrg31467.htm>.

Hughes, Eric. *A Cypherpunk's Manifesto.* Oorspronkelijk verstuurd naar de Cypherpunk-mailinglijst. March 17, 1993. Beschikbaar op <https://cypherpunks.venona.com/date/1993/03/msg00392.html>.

Hughes, Eric. *Kid Gloves or Megaphones.* Oorspronkelijk verstuurd naar de Cypherpunk-mailinglijst. March 14, 1996. Beschikbaar op <https://cypherpunks.venona.com/date/1996/03/msg00932.html>.

Hughes, Eric. *No digital coins (was: Chaum on the wrong foot?).* Oorspronkelijk verstuurd naar de Cypherpunk-mailinglijst. August 24, 1993. Beschikbaar op <https://cypherpunks.venona.com/date/1993/08/msg00690.html>.

Keynes, John Maynard. A Tract on Monetary Reform. London: Macmillan and Co, 1923.

Keynes, John Maynard. The General Theory of Employment, Interest and Money (London: Palgrave Macmillan, 1936).

Kresge, Stephen. The Collected Works of F.A. Hayek, Good Money: part I. Indianapolis, IN: Liberty Fund, 2009.

Kutler, Jeffrey. *Credit Suisse, Digicash in E-Commerce Test.* American Banker. June 16, 1998. <https://www.americanbanker.com/news/credit-suisse-digicash-in-e-commerce-test>

Lamport, Leslie, Robert Shostak, and Marshall Pease. *The Byzantine Generals Problem,* ACM Transactions on Programming Languages and Systems (July 1982): 382--401. <https://dl.acm.org/doi/10.1145/357172.357176>

Lavoie, Don, Howard Baetjer, and William Tulloh. *High-Tech Hayekians: Some Possible Research Topics in the Economics of Computation.* Market Process 8 (Spring 1990): 119--146.

Law, Laurie, Susan Sabett, and Jerry Solinas. *How To Make a Mint: The Cryptography of Anonymous Electronic Cash.* National Security Agency Office of Information Security Research and Technology, Cryptology Division. June 18, 1996. <https://groups.csail.mit.edu/mac/classes/6.805/articles/money/nsamint/nsamint.htm>

Levine, John. *Bitcoin P2P e-cash paper.* Oorspronkelijk verstuurd naar de Cryptografie-mailinglijst. November 3, 2008. Beschikbaar op <https://www.metzdowd.com/pipermail/cryptography/2008-November/014817.html>

Levy, Steven. *E-Money (That's What I Want).* Wired. December 1, 1994. <https://www.wired.com/1994/12/emoney/>

Levy, Steven. Crypto: How the Code Rebels Beat the Government--Saving Privacy in the Digital Age. New York: Viking, 2001.

Levy, Steven. Hackers: Heroes of the Computer Revolution. Sebastopol, CA: O'Reilly, 2010.

Lewis, Peter H. *Attention Internet Shoppers: E-Cash Is Here.* The New York Times. October 19, 1994. <https://www.nytimes.com/1994/10/19/business/attention-internet-shoppers-e-cash-is-here.html>

Lindenfors, Patrick, Andreas Wartel, and Johan Lind, *'Dunbar's Number' Deconstructed.* Biology Letters. May 5, 2021. <https://royalsocietypublishing.org/doi/10.1098/rsbl.2021.0158>

Martin, Douglas. *Futurist Known as FM-2030 Is Dead at 69.* The New York Times. July 11, 2000. <https://www.nytimes.com/2000/07/11/us/futurist-known-as-fm-2030-is-dead-at-69.html>

Mason, Edward S. and Robert E. Asher, The World Bank Since Bretton Woods: The Origins, Policies, Operations and Impact of the International Bank for Reconstruction. Washington, DC: Brookings Institution, 1973.

Maxwell, Gregory. IRC message to author, August 13, 2020.

May Tim. *What backs up digital money?* Oorspronkelijk verstuurd naar de Cypherpunk-mailinglijst. March 27, 1996. Beschikbaar op <https://cypherpunks.venona.com/date/1996/03/msg01576.html>

May, Tim. *'Stopping Crime' Necessarily Means Invasiveness.* Oorspronkelijk verstuurd naar de Cypherpunk-mailinglijst. October 17, 1996. Beschikbaar op <https://cypherpunks.venona.com/date/1996/10/msg01269.html>

May, Tim. *'Who shall speak for us?'* Oorspronkelijk verstuurd naar de Cypherpunk-mailinglijst. September 29, 1995. Beschikbaar op <https://cypherpunks.venona.com/date/1995/09/msg02189.html>

May, Tim. *Crypto Activism and Respectability.* Oorspronkelijk verstuurd naar de Cypherpunk-mailinglijst. April 21, 1993. Beschikbaar op <https://cypherpunks.venona.com/date/1993/04/msg00400.html>.

May, Tim. *Crypto Anarchy, the Government, and the National Information Infrastructure.* Oorspronkelijk verstuurd naar de Cypherpunk-mailinglijst. November 29, 1993, Beschikbaar op <https://cypherpunks.venona.com/date/1993/11/msg01106.html>.

May, Tim. *Cyberspace, Crypto Anarchy, and Pushing Limits.* Oorspronkelijk verstuurd naar de Cypherpunk-mailinglijst. April 3, 1994. Geraadpleegd via <https://cypherpunks.venona.com/date/1994/04/msg00096.html>.

May, Tim. *Degrees of Freedom.* Oorspronkelijk verstuurd naar de Cypherpunk-mailinglijst. February 8, 1996. Beschikbaar op <https://cypherpunks.venona.com/date/1996/02/msg00637.html>.

May, Tim. *DigiCash can use whatever currencies are valued* Oorspronkelijk verstuurd naar de Cypherpunk-mailinglijst. May 4, 1994. Beschikbaar op <https://cypherpunks.venona.com/date/1994/05/msg00243.html>.

May, Tim. *Hayek (was: Cato Institute conference on Net-regulation).* Oorspronkelijk verstuurd naar de Cypherpunk-mailinglijst. August 27, 1996. Geraadpleegd via <http://cypherpunks.venona.com/date/1996/08/msg02102.html>.

May, Tim. *Libertaria in Cyberspace.* Oorspronkelijk verstuurd naar de Cypherpunk-mailinglijst. August 9, 1993. Geraadpleegd via <https://cypherpunks.venona.com/date/1993/08/msg00168.html>.

May, Tim. *My Departure, Moderation, and \*Ownership of the List.* Oorspronkelijk verstuurd naar de Cypherpunk-mailinglijst. February 2, 1997. Beschikbaar op <https://cypherpunks.venona.com/date/1997/02/msg02898.html>.

May, Tim. *Opportunities in Cyberspace.* Oorspronkelijk verstuurd naar de Cypherpunk-mailinglijst. September 8, 1993. Beschikbaar op <https://cypherpunks.venona.com/date/1993/09/msg00140.html>.

May, Tim. *Re: alternative b-money creation.* Oorspronkelijk verstuurd naar de Cypherpunk-mailinglijst. December 11, 1998. Beschikbaar op <https://cypherpunks.venona.com/date/1998/12/msg00455.html>.

May, Tim. *Re: Hettinga's e\$yllogism.* Oorspronkelijk verstuurd naar de Cypherpunk-mailinglijst. June 28, 1997. Beschikbaar op <https://cypherpunks.venona.com/date/1997/06/msg01637.html>.

May, Tim. *Re: More on digital postage.* Oorspronkelijk verstuurd naar de Cypherpunk-mailinglijst. February 15, 1997. Beschikbaar op <https://cypherpunks.venona.com/date/1997/02/msg02295.html>.

May, Tim. *Re: Stalling the crypto legislation for 2-3 more years.* Oorspronkelijk verstuurd naar de Cypherpunk-mailinglijst. July 23, 1994. Beschikbaar op <https://cypherpunks.venona.com/date/1994/07/msg01245.html>.

May, Tim. *Re: The War on Some Money* <https://cypherpunks.venona.com/date/1995/12/msg01044.html>.

May, Tim. *Scenario for a Ban on Cash Transactions.* Oorspronkelijk verstuurd naar de Cypherpunk-mailinglijst. November 24, 1992. Beschikbaar op <https://cypherpunks.venona.com/date/1992/11/msg00211.html>.

May, Tim. *Software Patents are Freezing Evolution of Products.* Oorspronkelijk verstuurd naar de Cypherpunk-mailinglijst. October 7, 1995. Beschikbaar op <https://cypherpunks.venona.com/date/1995/10/msg00685.html>.

May, Tim. *The Crypto Anarchist Manifesto* Oorspronkelijk verstuurd naar de Cypherpunk-mailinglijst, November 22, 1992. Beschikbaar op <https://cypherpunks.venona.com/date/1992/11/msg00204.html>.

May, Tim. *The Cyphernomicon.* Oorspronkelijk verstuurd naar de Cypherpunk-mailinglijst. September 10, 1994. Beschikbaar op <https://nakamotoinstitute.org/static/docs/cyphernomicon.txt>.

May, Tim. *Untraceable Digital Cash, Information Markets, and BlackNet ('Governmental and Social Implications of Digital Money' panel at CFP '97).* The Computers Freedom & Privacy Conference (1997). Geraadpleegd via <https://web.archive.org/web/20130501134401/https:/osaka.law.miami.edu/~froomkin/articles/tcmay.htm>.

May, Tim. *Untraceable Payments, Extortion, and Other Bad Things.* Oorspronkelijk verstuurd naar de Cypherpunk-mailinglijst. December 21, 1996. Beschikbaar op <https://cypherpunks.venona.com/date/1996/12/msg01468.html>.

McCloskey, Deirdre N. *How to be Human -- Though an Economist*. Ann Arbor: The University of Michigan Press, 2000.

McCullagh, Declan. *Digging Those Digicash Blues.* Wired. June 14, 2001. <https://www.wired.com/2001/06/digging-those-digicash-blues/>.

Menger, Carl. *Untersuchungen über die Methode der Sozialwissenschaften und der Politischen Oekonomie insbesondere*. Leipzig: Dunker und Humblot, 1883.

Merkle, Ralph C. *A Certified Signature.* Advances in Cryptology---CRYPTO '89: Proceedings (1989): 218--238. <https://link.springer.com/chapter/10.1007/0-387-34805-0_21>.

Metzger, Perry E. *ADMIN: end of bitcoin discussion for now.* Oorspronkelijk verstuurd naar de Cryptografie-mailinglijst. November 17, 2008. Beschikbaar op <https://www.metzdowd.com/pipermail/cryptography/2008-November/014867.html>.

Metzger, Perry E. *Re: Virtual Cash.* Oorspronkelijk verstuurd naar de Cypherpunk-mailinglijst. May 3, 1994. Beschikbaar op <https://cypherpunks.venona.com/date/1994/05/msg00131.html>.

Mor, Federico. *Bank Rescues of 2007-09: Outcomes and Cost.* House of Commons Research Briefing. October 8, 2018. Beschikbaar op <https://commonslibrary.parliament.uk/research-briefings/sn05748/>.

More, Max. *Hayek's Denationalisation of Money.* Extropy 15 (2nd--3d Quarter 1995): 19--20. <https://archive.org/details/extropy-15/Extropy-15/>

More, Max. *The Extropian Principles: A Transhumanist Declaration.* maxmore.com, Geraadpleegd via <https://web.archive.org/web/20090130143449/https:/www.maxmore.com/extprn3.htm>

More, Max. *Transhumanism: Towards a Futurist Philosophy.* maxmore.com, Geraadpleegd via <https://web.archive.org/web/20051029125153/http:/www.maxmore.com/transhum.htm>

Nagy, Daniel A. comments in response to *The Mojo Nation Story---Part 2.* Financial Cryptography. October 12, 2005. <https://www.financialcryptography.com/mt/archives/000572.html>

Nakamoto, Satoshi. *Bitcoin: A Peer-to-Peer Electronic Cash System.* 2008. Beschikbaar op <https://bitcoin.org/bitcoin.pdf>

Nakamoto, Satoshi and Wei Dai. *Wei Dai/Satoshi Nakamot<https://gwern.net/doc/bitcoin/2008-nakamoto>

Nakamoto, Satoshi. *Bitcoin P2P e-cash paper.* Oorspronkelijk verstuurd naar de Cryptografie-mailinglijst. October 31, 2008. Beschikbaar op <https://www.metzdowd.com/pipermail/cryptography/2008-October/014810.html>

Nakamoto, Satoshi. *Bitcoin P2P e-cash paper.* Oorspronkelijk verstuurd naar de Cryptografie-mailinglijst. November 2, 2008. Beschikbaar op <https://www.metzdowd.com/pipermail/cryptography/2008-November/014815.html>

Nakamoto, Satoshi. *Bitcoin P2P e-cash paper.* Oorspronkelijk verstuurd naar de Cryptografie-mailinglijst. November 6, 2008. Beschikbaar op <https://www.metzdowd.com/pipermail/cryptography/2008-November/014823.html>

Nakamoto, Satoshi. *Bitcoin P2P e-cash paper.* Oorspronkelijk verstuurd naar de Cryptografie-mailinglijst. November 14, 2008. Beschikbaar op <https://www.metzdowd.com/pipermail/cryptography/2008-November/014853.html>

Nakamoto, Satoshi. *Bitcoin P2P e-cash paper.* Oorspronkelijk verstuurd naar de Cryptografie-mailinglijst. November 8, 2008. Beschikbaar op <https://www.metzdowd.com/pipermail/cryptography/2008-November/014832.html>

Nakamoto, Satoshi. *Bitcoin v0.1 released.* Oorspronkelijk verstuurd naar de Cryptografie-mailinglijst. January 8, 2009. Beschikbaar op <https://www.mail-archive.com/cryptography@metzdowd.com/msg10142.html>

Nakamoto, Satoshi. *Bitcoin v0.1 released.* Oorspronkelijk verstuurd naar de Cryptografie-mailinglijst. January 16, 2009. Beschikbaar op <https://www.metzdowd.com/pipermail/cryptography/2009-January/015014.html>

Nakamoto, Satoshi. *Bitcoin v0.1 released.* Oorspronkelijk verstuurd naar de Cryptografie-mailinglijst. January 16, 2009. Beschikbaar op <https://www.metzdowd.com/pipermail/cryptography/2009-January/015014.html>

Nash, Hadon. *Digital Gold,* Oorspronkelijk verstuurd naar de Cypherpunk-mailinglijst. August 24, 1993. Beschikbaar op <https://cypherpunks.venona.com/date/1993/08/msg00698.html>

Next! Magazine. *Hoe DigiCash alles verknalde.* Next! January 1999. Geraadpleegd via <https://web.archive.org/web/19990427142412/https:/www.nextmagazine.nl/ecash.htm>

Nixon, Richard. *Address to the Nation Outlining a New Economic Policy: 'The Challenge of Peace'.* August 15, 1971. Beschikbaar op The American Presidency Project. <https://www.presidency.ucsb.edu/documents/address-the-nation-outlining-new-economic-policy-the-challenge-peace>

Officer, Lawrence H. *Exchange Rates Between the United States Dollar and Forty-one Currencies,* MeasuringWorth, 2023. <https://www.measuringworth.com/datasets/exchangeglobal/>

Patel, Rupal and Jack Meaning. Can't We Just Print More Money? Economics in Ten Simple Questions. The Bank of England. London: Cornerstone Press, 2022.

Pitta, Julie. *Requiem for a Bright Idea,* Forbes. November 1, 1999. <https://www.forbes.com/forbes/1999/1101/6411390a.html>

Pr0duct Cypher. *Magic Money Digicash System.* Oorspronkelijk verstuurd naar de Cypherpunk-mailinglijst. February 4, 1994. Beschikbaar op <https://cypherpunks.venona.com/date/1994/02/msg00247.html>

Purdy, George B. *A High Security Log-in Procedure.* Communications of the ACM 17, no. 8 (August 1974): 442--445.

Quinn, Michelle. *The Cypherpunks Who Cracked Netscape,* San Francisco Chronicle. September 20, 1995. <https://people.eecs.berkeley.edu/~daw/press/iang/ian1.html>

Raymond. Eric S. The Cathedral & The Bazaar: Musings on Linux and Open Source by an Accidental Revolutionary. Sebastopol, CA: O'Reilly, 2001.

Regis, Ed. *Meet the Extropians.* Wired. October 1, 1994. <https://www.wired.com/1994/10/extropians/>

Richardson, Gary and Tim Sablik. *Banking Panics of the Gilded Age: 1863--1913.* Federal Reserve History. December 4, 2015. <https://www.federalreservehistory.org/essays/banking-panics-of-the-gilded-age>

Rickards, James. *Currency Wars: The Making of the Next Global Crisis*. New York: Portfolio 2012.

Roosevelt, Franklin D. *Relating to the Hoarding, Export, and Earmarking of Gold Coin, Bullion, or Currency and to Transactions in Foreign Exchange.* August 28, 1993. Beschikbaar op The American Presidency Project. <https://www.presidency.ucsb.edu/documents/executive-order-6260-relating-the-hoarding-export-and-earmarking-gold-coin-bullion-or.>

Salin, Phil. *Costs and Computers.* Release 1.0 (November 25, 1991): 5--18. <https://www.yumpu.com/en/document/read/17286753/25-november-1991-cdnoreillycom>

Salin, Phil. *The Ecology of Decisions, or 'An Inquiry into the Nature and Causes of the Wealth of Kitchens'.* Market Process 8 (Spring 1990): 91--114.

Schulze, Hendrik and Klaus Mochalski. *Internet Study 2008/2009.* Ipoque. 2009. <https://sites.cs.ucsb.edu/~almeroth/classes/W10.290F/papers/ipoque-internet-study-08-09.pdf>

Selgin, George. *The New Deal and Recovery, Part 15: The Keynesian Myth.* Cato Institute. March 16, 2022. <https://www.cato.org/blog/new-deal-recovery-part-15-keynesian-myth>

Stallman, Richard. *Free Software Is Even More Important Now.* gnu.org, <https://www.gnu.org/philosophy/free-software-even-more-important.en.html>

Stallman, Richard. *Free Unix!* September 27, 1983, <https://www.gnu.org/gnu/initial-announcement.en.html>

Stallman, Richard. *Richard Stallman: High School Misfit, Symbol of Free Software, MacArthur-Certified Genius.* Interview door Michael Gross, mgross.com, 1999. <https://www.mgross.com/writing/books/my-generation/bonus-chapters/richard-stallman-high-school-misfit-symbol-of-free-software-macarthur-certified-genius/>

Stallman, Richard. *RMS Berättar.* Linköping University, <http://www.lysator.liu.se/history/garb/txt/87-2-rms.txt>

Stallman, Richard. *Talking to the Mailman.* Interview door Rob Lucas, New Left Review, Sept--Oct 2018. <https://newleftreview.org/issues/ii113/articles/richard-stallman-talking-to-the-mailman>

Stornetta, Scott. *The Missing Link between Satoshi & Bitcoin: Cypherpunk Scott Stornetta.* Interview door Naomi Brockwell. NBTV, with Naomi Brockwell. YouTube, September 6, 2018, <https://youtu.be/fYr-keVOQ18,%2057:08>

Szabo, Nick. (@NickSzabo4), *Some of the most important books I've read.* X. January 31, 2016. <https://twitter.com/NickSzabo4/status/693682157525401601>

Szabo, Nick. *Bit Gold Markets.* Unenumerated. December 27, 2008. <https://unenumerated.blogspot.com/2008/04/bit-gold-markets.html>

Szabo, Nick. *Bit Gold.* Unenumerated. December 27, 2008. <https://unenumerated.blogspot.com/2005/12/bit-gold.html>

Szabo, Nick. *Bit Gold: Towards Trust-Independent Digital Money.* 1999. Geraadpleegd via <https://web.archive.org/web/20140406003811/http:/szabo.best.vwh.net/bitgold.html>

Szabo, Nick. *Nick Szabo on Cypherpunks, Money and Bitcoin.* Interview door Peter McCormack, What Bitcoin Did, November 1, 2019, <https://www.whatbitcoindid.com/podcast/nick-szabo-on-cypherpunks-money-and-bitcoin%201:39:37>

Szabo, Nick. *Nick Szabo---The Quiet Master of Cryptocurrency \| Co-Hosted by Naval Ravikant.* Interview door Tim Ferriss, The Tim Ferriss Show. YouTube. August 12, 2017. <https://youtu.be/3FA3UjA0igY%202:34:27>

Szabo, Nick. *Re: Crypto + Economics + AI = Digital Money Economies.* Oorspronkelijk verstuurd naar de Cypherpunk-mailinglijst. September 19, 1995. Beschikbaar op <https://cypherpunks.venona.com/date/1995/09/msg01303.html>

Szabo, Nick. *Re: Crypto + Economics + AI = Digital Money Economies.* Oorspronkelijk verstuurd naar de Cypherpunk-mailinglijst. September 19, 1995. Beschikbaar op <https://cypherpunks.venona.com/date/1995/09/msg01303.html>

Szabo, Nick. *Secure Property Titles with Owner Authority.* Satoshi Nakamoto Institute (1998). <https://nakamotoinstitute.org/secure-property-titles/>

Szabo, Nick. *Shelling Out: The Origins of Money.* Satoshi Nakamoto Institute (2002). <https://nakamotoinstitute.org/shelling-out/>

Szabo, Nick. *Smart Contracts: Building Blocks for Digital Free Markets.* Extropy 16 (1st Quarter of 1996): 50--64. <https://archive.org/details/extropy-16.>

Szabo, Nick. *Trusted Third Parties are Security Holes.* Satoshi Nakamoto Institute (2001), <https://nakamotoinstitute.org/trusted-third-parties/>

Szabo, Nick. *Why Cryptocurrency? Governments Abuse Their Power---Nick Szabo Interview Part 1.* Interview door Zulu Republic. Zulu Republic, YouTube. October 25, 2018. <https://youtu.be/LZw4LNLYUgc?si=_FilNeaFnWxpvv9U%201:02>.

Szabo, Nick. Personal correspondence, email to author, July 10, 2018.

US Department of Justice. *Digital Currency Business e-gold Pleads Guilty to Money Laundering and Illegal Money Transmitting Charges.* July 21, 2008. <https://www.justice.gov/archive/opa/pr/2008/July/08-crm-635.html>.

US Department of the Treasury. *Troubled Asset Relief Program (TARP)* Beschikbaar op <https://home.treasury.gov/data/troubled-asset-relief-program>.

von Mises, Ludwig. *Economic Calculation in the Socialist Commonwealth*. Auburn, AL: Ludwig von Mises Institute, 2012.

von Mises, Ludwig. *Human Action: A Treatise on Economics, The Scholar's Edition* (Auburn, AL: Ludwig von Mises Institute, 1998).

von Mises, Ludwig. *The Historical Setting of the Austrian School of Economics*. New Rochelle, NY: Arlington House, 1969.

von Mises, Ludwig. *The Theory of Money and Credit*, translated by J.E. Batson. New Haven, CT: Yale University Press, 1953.

Wang, Liang. *BitTorrent Mainline DHT Measurement.* MLDHT. 2013. Beschikbaar op <https://www.cl.cam.ac.uk/~lw525/MLDHT/>

Wapshott, Nicholas. Keynes *Hayek: The Clash That Defined Modern Economics*. New York: Norton, 2011.

Watercutter, Angela. *Why Free Software Is More Important Now Than Ever Before.* Wired. September 20, 2013. <https://www.wired.com/2013/09/why-free-software-is-more-important-now-than-ever-before/>

Weinstock, Nicole. *Member Profile: Hal Finney.* Cryonics 40, issue 2 (2nd Quarter 2019): 3--9. <https://cryonicsarchive.org/docs/cryonics-magazine-2019-02.pdf>

White, Lawrence H. *Thoughts on the Economics of 'Digital Currency'.* Extropy 15 (2nd--3d Quarter 1995): 16--19. <https://archive.org/details/extropy-15/Extropy-15/>.

White, Lawrence H. *The Troubling Suppression of Competition from Alternative Monies: The Cases of the Liberty Dollar and e-gold.* Cato Journal 34, no. 2 (2014): 281--301. <https://www.cato.org/sites/cato.org/files/serials/files/cato-journal/2014/5/cato-journal-v34n2-5.pdf>

Wilcox-O'Hearn, Bryce. *Experiences Deploying A Large-Scale Emergent Network.* Peer-to-Peer Systems (2002): 104--110. <https://dl.acm.org/doi/10.5555/646334.687811>

Wong, Andrea. *The Untold Story Behind Saudi Arabia's 41-Year U.S. Debt Secret.* Bloomberg. May 31, 2016. <https://www.bloomberg.com/news/features/2016-05-30/the-untold-story-behind-saudi-arabia-s-41-year-u-s-debt-secret#xj4y7vzkg>.

## Andere geraadpleegde werken

Ammous, Saifedean. *The Bitcoin Standard: The Decentralized Alternative to Central Banking*. Hoboken, NJ.: Wiley, 2018.

Assange, Julian. *Cypherpunks: Freedom and the Future of the Internet*. OR Books, 2012.

Back, Adam. *Adam Back Reflects on the Cypherpunk Movement, Inventing Hashcash, Satoshi & Bitcoin.* Interview door Cedric Youngelman. The Bitcoin Matrix 114, YouTube. July 11, 2022. <https://youtu.be/uCavLyzQMbk> 1:06:35.

Back, Adam. *Hashcash --- A Denial of Service Counter-Measure.* cypherspace.org. August 1, 2002. Beschikbaar op <https://archive.li/W7QWn>.

Back, Adam. *Hashcash information and documentation.* <http://www.hashcash.org/>.

Back, Adam. *who is this annoying Adam Back guy?,* Bitcoin Forum, June 4, 2013, <https://bitcointalk.org/index.php?topic=225463.0>

Back, Adam. *Why Dr Adam Back So Legendary.* Interview door Trace Mayer. Bitcoin Knowledge Podcast, YouTube. September 7, 2015. <https://youtu.be/0VboMe_2fnc>

Backhouse, Roger E. *Austrian Economics and the Mainstream: View From the Boundary.* The Quarterly Journal of Austrian Economics 3, no. 2 (Summer 2000): 31--43.

Barta, Silas and Robert B. Murphy. *Understanding Bitcoin: The Liberty Lover's Guide to the Mechanics and Economics of Crypto-Currencies*. 2017.

Birch, David and Neil McEvoy. *Downloadsamoney.* Demos Quarterly 8 (1996): 85--94.

Board of Governors of the Federal Reserve System. *Arthur F. Burns.* Federal Reserve Bank of St. Louis. <https://www.federalreservehistory.org/people/arthur-f-burns.>

Brands, Stefan. *An Efficient Off-line Electronic Cash System Based On The Representation Problem.* Computer Science/Department of Algorithmics and Architecture, Report CS-R9323 (1993). <https://ir.cwi.nl/pub/5303>

Chaum, David and Adam Back. *Why Bitcoin Now: David Chaum and Adam Back Reflect on the Crypto Wars.* Interview door Laura Shin. Unchained Podcast 186, YouTube. August 18, 2020. <https://youtu.be/ZVZxRMAeIdo>

Chaum, David and Stefan Brands. *'Minting' Electronic Cash.* IEEE Spectrum. January 4 1999. <https://spectrum.ieee.org/minting-electronic-cash>

Chaum, David, Amos Fiat, and Moni Naor. *Untraceable Electronic Cash.* Crypto 1988: Advances in Cryptology (1988), 319--27.

Chaum, David. *The Dining Cryptographers Problem: Unconditional Sender and Recipient Untraceability.* Journal of Cryptology 1 (1988): 65--75. <https://link.springer.com/article/10.1007/BF00206326>

Coulouris, George, Jean Dolllimore, and Tim Kindberg. *Low-Value electronic transactions: the Millicent protocol.* Distributed Systems, ed. 3 (2001): 303--306. <https://www.cdk5.net/security/Ed3/Millicent.pdf>

De Jong, Eduard, Nathaniel Tkacz, and Pablo Velasco. *'Live As Friends and Count as Enemies': On Digital Cash and the Media of Payment.* Moneylab Reader (2015): 258--267. <https://www.academia.edu/31349137/_You_Will_Live_as_Friends_and_Count_as_Enemies_On_Digital_Cash_and_the_Media_of_Payment>

Diffie, Whitfield. *Interview with Whitfield Diffie on the Development of Public Key Cryptography.* Interview door Franco Furger. January 16, 2002. <https://www.itas.kit.edu/pub/m/2002/wedi02a.htm>

Drexler, K. Eric. *Molecular engineering: An approach to the Development of General Capabilities for Molecular Manipulation.* Proceedings of the National Academy of Sciences 78, no. 9 (September 1981): 5275--5278.

Ebeling, Richard M. *The Austrian Theory of the Trade Cycle*. Auburn, AL.:Ludwig von Mises Institute, 1996.

Epstein, Jim. *Cypherpunks Write Code Series.* ReasonTV, YouTube. October 7-28, 2020. <https://www.youtube.com/playlist?list=PLBuns9Evn1w-T2RwqMhUnTZbTTe-M-g42>

Epstein, Jim. *How Will Bitcoin Lead to More Freedom?*, Reason. October 10, 2020. <https://reason.com/2020/10/16/how-will-bitcoin-lead-to-more-freedom/>

Finney, Hal. *Bitcoin and me (Hal Finney).* Bitcoin Forum. March 19, 2013. <https://bitcointalk.org/index.php?topic=155054.0>

Finney, Hal. *Hal Finney interview.* Interview door Scott Stilphen. Atari Compendium, <https://www.ataricompendium.com/archives/interviews/hal_finney/interview_hal_finney.html>

George Edward Durell Foundation. *Money and Banking: The American Experience*. George Mason University Press, 1995.

Gibson, William. *Neuromancer*. New York: Ace, 1984.

Greenberg, Andy. *Nakamoto's Neighbor: My Hunt For Bitcoin's Creator Led To a Paralyzed Crypto Genius.* Forbes. March 25, 2014. <https://www.forbes.com/sites/andygreenberg/2014/03/25/satoshi-nakamotos-neighbor-the-bitcoin-ghostwriter-who-wasnt/?sh=38f8f8854a37>

Greenberg, Andy. *This Machine Kills Secrets: How WikiLeakers, Hacktivists and Cypherpunks Aim to Free the World's Information*. London: Virgin Books, 2012.

Grigg, Ian. *A Quick History of Cryptocurrencies BBTC --- Before Bitcoin.* Bitcoin Magazine. April 16, 2014. <https://bitcoinmagazine.com/business/quick-history-cryptocurrencies-bbtc-bitcoin-1397682630>

Hayek, Friedrich A. *A Free-Market Monetary System.* Lecture delivered at the Gold and Monetary Conference, New Orleans. November 10, 1977. Republished by the Mises Institute, <https://mises.org/library/free-market-monetary-system>

Hayek, Friedrich A. *Choice in Currency: A Way to Stop Inflation*. London: The Institute of Economic Affairs, 1976.

Hayek, Friedrich A. *A Tiger by the Tail: The Keynesian Legacy of Inflation*, edited by Sudha R. Shenoy. The Institute of Economic Affairs and the Ludwig von Mises Institute, 2009.

Hellman, Dorothie and Martin Hellman. *A New Map for Relationships: Creating True Love at Home & Peace on the Planet*. New Map Publishing, 2016.

Jackson, Douglas. *The Story of egold.* Interview door Dustin. Did You Know Crypto 72. February 9, 2020. <https://didyouknowcrypto.com/ep72/>

Kawamoto, Dawn. *Compaq to license digital cash technology.* CNET. January 2, 2002. <https://www.cnet.com/tech/tech-industry/compaq-to-license-digital-cash-technology/>

Koblitz, Neal. *Elliptic Curve Cryptosystems,* Mathematics of Computation 48, no. 177 (January 1987): 203--9. <https://www.ams.org/journals/mcom/1987-48-177/S0025-5718-1987-0866109-5/S0025-5718-1987-0866109-5.pdf>

Kreling, Tom. *Douglas Jackson bedacht de eerste digitale valuta en werd veroordeeld voor witwassen.* de Volkskrant. January 13, 2018. <https://www.volkskrant.nl/economie/douglas-jackson-bedacht-de-eerste-digitale-valuta-en-werd-veroordeeld-voor-witwassen~b6ea3bcd/>

Lopp, Jameson. *Bitcoin and the Rise of the Cypherpunks.* CoinDesk. April 9, 2016. <https://www.coindesk.com/markets/2016/04/09/bitcoin-and-the-rise-of-the-cypherpunks/>

Lynch, Daniel C. and Leslie Lundquist. *Digital Money: The New Era of Internet Commerce*. Hoboken, NJ.: Wiley, 1996.

Massias, H., X. Serret Avila, and J.-J. Quisquater. *Design of a Secure Timestamping Service With Minimal Trust Requirement.* 20th Symposium in Information Theory in the Benelux. May 1999. Beschikbaar op Satoshi Nakamoto Institute: <https://nakamotoinstitute.org/static/docs/secure-timestamping-service.pdf>

Maxwell, Gregory. *SF Bitcoin Devs Seminar: Greg Maxwell.* SF Bitcoin Developers, YouTube. April 29, 2015. <https://youtu.be/Gs9lJTRZCDc> 1:23:12.

Merkle, Ralph C. *A Digital Signature Based on a Conventional Encryption Function* Crypto 1987: Advances in Cryptology (1987): 369--378. <https://people.eecs.berkeley.edu/~raluca/cs261-f15/readings/merkle.pdf>

Miller, Victor S. *Use of Elliptic Curves in Cryptography.* Crypto 1985: Advances in Cryptology (1985): 417--26. <https://dl.acm.org/doi/10.5555/646751.704566>

Möller, Niels, *Ncash --- An Experimental Digital Cash System* (1998). <https://www.lysator.liu.se/~nisse/NCash/>

More, Max and Natasha Vita-More. *Max More & Natasha Vita-More on the History of Transhumanism w/ Like Robert Mason.* Interview door Luke Robert Mason. Luke Robert Mason, YouTube. May 28, 2020. <https://youtu.be/ffEDNLRq6y8> 1:23:58.

More, Max. *Max More --- Transhumanism and the Singularity.* Science, Technology & the Future. YouTube. January 4, 2012. <https://youtu.be/1xIQgBXw9-o> 20:43.

Narayanan, Arvind and Jeremy Clark. *Bitcoin's Academic Pedigree: The concept of cryptocurrencies is built from forgotten ideas in research literature.* Queue 15, no. 4 (July--August 2017): 20--49. <https://dl.acm.org/doi/10.1145/3134434.3136559>

Okamoto, Tatsuaki and Kazuo Ohta. *Universal Electronic Cash.* Crypto 1991: Advances in Cryptology (1991): 324--337. <https://dl.acm.org/doi/abs/10.5555/646756.705374>

Orwell, George. *Nineteen Eighty-Four*. London: Penguin Books, 2003.

Pein, Corey. *Everybody Freeze!* The Baffler. March 2016. <https://thebaffler.com/salvos/everybody-freeze-pein>

Phillips, A. W. *The Relationship Between Unemployment and the rate of Change of Money Wage Rates in the United Kingdom, 1861--1957.* Economica 25: 283--99. <https://www.jstor.org/stable/2550759>

Popper, Nathaniel. *Digital Gold: The Untold Story of Bitcoin*. New York: Penguin Books, 2016.

Pritzker, Yan, *Inventing Bitcoin: The Technology Behind the First Truly Scarce and Decentralized Money Explained*. 2019.

Rivest, Ronald, Adi Shamir, and Leonard Adleman. *A Method for Obtaining Digital Signatures and Public-Key Cryptosystems.* Communications of the ACM 21, no. 2 (1978): 120--126. <https://web.williams.edu/Mathematics/lg5/302/RSA.pdf>

Rothbard, Murray N. *The End of Socialism and the Calculation Debate Revisited.* The Review of Austrian Economics 5, no. 2 (1991): 51--76.

Rothbard, Murray N. *The Mystery of Banking*. Auburn, AL.:Ludwig von Mises Institute, 2008.

Rothbard, Murray N. *What Has Government Done to Our Money?* Auburn, AL.: Ludwig von Mises Institute, 2010.

Salerno, Joseph T. *Hayek on the Business Cycle.* Mises Daily. October 8, 2008, <https://mises.org/library/hayek-business-cycle>

Schneier, Bruce. *Applied Cryptography*, Second Edition: Protocols, Algorithms, and Source Code in C. London: John Wiley & Sons, Inc. 1996.

Selgin, George A. *The Theory of Free Banking: Money Supply Under Competitive Note*. Issue. Totowa, NJ.: Rowman & Littlefield Publishers, 1988.

Skidelsky, Robert. *Keynes: The Return of the Master*. London: PublicAffairs, 2010.

Stephenson, Neal. *Snow Crash.* New York: Bantham Books, 1993.

Szabo, Nick, Adam Back and David Chaum. *The Godfathers of Bitcoin: Nick Szabo, Adam Back and David Chaum.* Interview door John Riggins. Bitcoin in Asia 29, YouTube. November 16, 2020, <https://youtu.be/D5LpgX-pkUM> 43:33.

Szabo, Nick. *Bitcoin, what took ye so long?* Unenumerated. May 28, 2011. <https://unenumerated.blogspot.com/2011/05/bitcoin-what-took-ye-so-long.html>

UK Parliament. *Small Change: Britain and the Gold Standard.* UK Parliament. <https://www.parliament.uk/business/publications/research/olympic-britain/the-economy/small-change/>

US Office of the Historian. *Nixon and the End of the Bretton Woods System, 1971--1973.* <https://history.state.gov/milestones/1969-1976/nixon-shock>

Vigna, Paul and Casey, Michael J. *Cryptocurrency: The Future of Money?* London: Vintage, 2016.

Vinge, Vernor. *A Fire Upon the Deep*. New York: Tor Books, 1992.

Vinge, Vernor. *True Names: and the Opening of the Cyberspace Frontier*. London: Penguin Books, 2016.

von Böhm-Bawerk, Eugen. *Capital and Interest: A Critical History of Economic Theory*. Translated by William Smart. London: Macmillan and Co., 1890.

Wayner, Peter. *Digital Cash: Commerce on the Net*. London: Academic Press Limited, 1996.

White, Lawrence H., *Banking without a Central Bank: Scotland before 1844 as a 'Free Banking' system.* In Unregulated Banking: Chaos or Order? Edited by F. Capie and G.E. Wood, 37--71. London: Palgrave Macmillan, 1991.

## Algemeen

Extropy magazines 1--17 (1988-1996).

eCash news archieven op Chaum.com, <https://chaum.com/ecash/>

Cypherpunks mailing list archieven, 1992--2000. Beschikbaar op <https://cypherpunks.venona.com/>

Cryptography mailing list archieven, October 2008--January 2009. Beschikbaar op <https://www.metzdowd.com/pipermail/cryptography/>
