# Inleiding {.unnumbered}

E-goud was in volle bloei. Tegen 2005 waren er op het innovatieve online betalingssysteem van Douglas Jackson meer dan een miljoen accounts aangemaakt, die samen verantwoordelijk waren voor bijna € 2 miljard aan transacties per jaar. De volledig gedekte digitale tokens die e-goudklanten gebruikten om al deze transacties uit te voeren, vertegenwoordigden 3,8 ton goud, opgeborgen in kluizen over de hele wereld. Als een van de eerste werkende implementaties van elektronisch geld, was e-goud in minder dan tien jaar tijd uitgegroeid tot de populairste digitale valuta op het internet.

Maar Jackson stond een onaangename verrassing te wachten.

In december 2005 voerde de Amerikaanse geheime dienst, net voor het einde van het jaar, een inval uit bij het bedrijf van Jackson en zijn woning in Melbourne, Florida. Ze namen boeken en administratieve gegevens mee, en federale agenten namen alles wat zelfs maar enigszins interessant leek in beslag: naast juridische documenten en zakelijke contracten, omvatte dit ook het adresboek van zijn vrouw, de paspoorten van hun kinderen en de creditcards van op het nachtkastje. Op datzelfde moment werden de servers van e-goud, in een AT&T-gebouw in Orlando, zo'n 110 kilometer verder naar het noordwesten, offline gehaald, en werden alle transactiegegevens in beslag genomen.

De Amerikaanse geheime dienst, bijgestaan door de IRS en de FBI, was van mening dat de betaalverwerker een broedplaats was geworden voor criminelen, die simpelweg met behulp van een emailadres e-goudaccounts konden aanmaken --- dus vrijwel anoniem. In een tijdperk waarin creditcardfraude op het internet hoogtij vierde, zou het betaalsysteem van Jackson als een magneet voor oplichters hebben gefunctioneerd. Erger nog, wetshandhavers vermoedden dat kinderpornografen en terroristen van de relatieve anonimiteit van e-goud misbruik maakten.

Jackson werd aangeklaagd en beschuldigd van het witwassen van geld en het runnen van een niet-gelicentieerde betaaldienst.[^1]

## Digitaal goud

Jackson had nooit beoogd dat e-goud misbruikt zou worden voor illegale doeleinden. Hij geloofde ook niet dat dit op een serieuze schaal gebeurde. Sterker nog, hij beweerde dat e-goud een beter fraudedetectiesysteem had dan elke andere betaalverwerker die er bestond. Daarnaast was hij altijd meer dan bereid om met politie samen te werken. E-goud was ook een van de oprichtende leden van het 'National Center for Missing & Exploited Children's Financial Coalition Against Child Pornography'. De gegevens die deze coalitie verzamelde, zo stelde Jackson, gaven aan dat e-goud vrijwel niet werd gebruikt voor dergelijke doeleinden.

In plaats daarvan was Jackson, als succesvol en onafhankelijk oncoloog en veteraan van het medisch korps van het Amerikaanse leger, in de jaren negentig al geïnteresseerd geraakt in het monetaire beleid en de invloed daarvan op de economie. Hij ontdekte dat moderne valuta's -- dollars, ponden, yen -- niet langer door iets gedekt werden, waardoor ze in feite, uit het niets, met een druk op de knop gecreëerd konden worden. Toen hij zich verder in dit onderwerp verdiepte, raakte hij ervan overtuigd dat dit de economie op zeer schadelijke manieren beïnvloedde.

Jackson was dus van plan om een alternatief aan te bieden.

Tijdens zijn onderzoek naar valuta's, ontwikkelde Jackson een hernieuwde waardering voor het 'klassieke geld' -- goud. Hij ontdekte dat mensen ten minste sinds de predynastieke Egyptische tijd waarde hechtten aan dit glanzende, gele metaal, en dat met goede reden: het natuurlijke element werd niet beïnvloed door de willekeur van mensen.

Echter, het pre-dynastieke Egypte was allang verdwenen en zelfs Jackson moest toegeven dat het kostbare metaal niet echt praktisch was voor dagelijkse transacties. Nu het nieuwe millennium naderde, besefte Jackson dat mensen niet zouden terugkeren naar de tijd waarin ze betaalden met gouden munten. Sterker nog, zelfs koperen munten en papiergeld zouden waarschijnlijk binnenkort ouderwets lijken.

Nee, de toekomst van geld moest digitaal zijn.

Met dat toekomstbeeld zag Jackson (heel letterlijk) een gouden kans. Hij bundelde de krachten met advocaat Barry Downey en richtte in 1996 'Gold & Silver Reserve Inc.' op, onder zijn leiderschap. De start-up zou een betalingssysteem voor de eenentwintigste eeuw runnen, maar dan wel gebaseerd op dat klassieke geld. Ze zouden een elektronisch equivalent voor goud leveren: *e-gold*.

Het basisidee was simpel. *Gold & Silver Reserve Inc.* huurde kluizen die ze vulden met het fysieke, gouden metaal zelf. Voor elk stuk goud in deze kluizen gaf het bedrijf een digitale 'token' uit --- in feite een nummer in een database. Deze tokens vertegenwoordigden een claim op het goud. Als iemand tokens had die gelijk stonden aan tien gram goud, was tien gram goud in een van de kluizen wettelijk van hen.

De belangrijkste innovatie was dat *Gold & Silver Reserve Inc.* ook een server in stand hield die een openbaar toegankelijk boekhoudsysteem voor de tokens huisvestte. Mensen van over de hele wereld konden inloggen op de server en een persoonlijke rekening aanmaken, waardoor ze tokens naar en van elke andere rekening konden sturen en ontvangen. Bij elke transactie heeft *Gold & Silver Reserve Inc.* de rekeningsaldi dienovereenkomstig bijgewerkt.

Dankzij de kracht van het internet, konden e-goud gebruikers elkaar dus in wezen over grote afstanden, direct, betalen tegen minimale kosten. Op de grenzeloze *informatiesnelweg* kon iedereen met een internetverbinding iemand anders betalen, zonder beperkingen met betrekking tot nationale grenzen of bankregels.

Jackson creëerde e-goud, zo zei hij vaak, als een instelling om het materiële welzijn van de mensheid te bevorderen door toegang te bieden tot wereldwijde markten.

'In tegenstelling tot andere, is e-goud een betalingssysteem dat mensen van elke regio of economische achtergrond wereldwijd laat opereren: een migrant kan gemakkelijk waarde naar huis sturen en een handelaar kan betalingen accepteren van iemand in een derdewereldland die misschien geen toegang heeft tot een creditcard of bankrekening.'[^2]

Bovendien beweerde Jackson dat e-goud de mogelijkheid bood om een soort geld te gebruiken dat bestand is tegen inflatie. Omdat het digitaal was, was e-goud eigenlijk voor veel mensen toegankelijker dan echt goud.

Op de lange termijn had e-goud zelfs het potentieel om de ruggengraat te worden van een geheel nieuw, financieel systeem, suggereerde Jackson optimistisch.

'Hoe vinden we een bankensysteem uit dat niet de oorzaak zal zijn van catastrofale verstoringen, dat zelf het minst waarschijnlijk is om schommelingen te introduceren en dat het meest waarschijnlijk de juiste aanpassingen zal maken... is het meest prangende, onopgeloste economische probleem van onze tijd', citeerde hij op een gegeven moment uit het boek '*The Rationale of Central Banking and the Free Banking Alternative*' van econome Vera Smith.

Toe te voegen: 'Een systeem en munteenheid zoals e-goud, vooral na opkomst en integratie in de financiële mainstream als een reserve-activum dat als betaalmiddel wordt gebruikt, kunnen dit probleem zeker en vast oplossen.'[^3]

## Juridische kwesties

Vroeg in de jaren 2000 was e-goud snel aan het groeien, en Jackson werkte onvermoeid om zijn dienst te verbeteren. Hij stelde meer soorten edelmetalen beschikbaar, en voegde tevens nieuwe betalingsfuncties toe, zoals geautomatiseerde, maandelijkse betalingen. Bovendien maakte hij toegang tot het systeem mogelijk via mobiele telefoons via het toen nieuwe WAP-protocol.[^4]

Maar Jackson was iets vergeten: hij had zijn bedrijf niet geregistreerd als betaaldienst. Daardoor voerde hij ook niet alle types van *Know-Your-Customer* (KYC) en *Anti-Money Laundering* (AML) controles uit die vereist zijn voor een betaaldienst. Hij was zich er niet van bewust dat hij dat moest doen.

Het was niet zo dat hij nonchalant was. Het werd pas een federale misdaad om zonder licentie als betaaldienst te opereren (voor elke staat die er een vereist) na de invoering van de *Patriot Act*, die in het leven werd geroepen als reactie op de terroristische aanslagen van 11 september 2001, enkele jaren na de lancering van e-goud. Nog belangrijker: het was niet duidelijk dat Jacksons onderneming überhaupt als een betaaldienst beschouwd zou worden: het e-goudsysteem verstuurde geen dollars of andere nationale valuta, waarvoor zulke regels doorgaans van toepassing waren.

Desondanks had Jackson geprobeerd meer duidelijkheid te krijgen over de kwestie. *Gold & Silver Reserve Inc.* had zelf aan de relevante overheidsinstanties voorgesteld dat e-goud gecategoriseerd kon worden als een valuta voor reguleringsdoeleinden, waardoor het bedrijf zich ook als een valutawisseldienst kon registreren. Maar als reactie hierop had het Amerikaanse ministerie van Financiën opnieuw bevestigd dat de definities van valuta niet van toepassingen waren op e-goud.

Bovendien had Jackson vrijwillig een conformiteitsonderzoek op de Bankgeheimwet gestart bij een agentschap van het ministerie van Financiën, puur om erachter te komen hoe zij dachten dat zijn bedrijf gereguleerd zou moeten worden.[^5]

Toen de invallen plaatsvonden, wachtte hij nog op een antwoord.

De daaropvolgende juridische procedures brachten ernstige schade toe aan de e-goudonderneming. Bankrekeningen werden bevroren en bedrijfsgelden in beslag genomen. De juridische strijd die zich ontvouwde tussen Jackson en de Amerikaanse regering duurde twee jaar en putte zijn middelen uit: de juridische kosten zouden uiteindelijk oplopen tot in de miljoenen. En voor zover het bedrijf van Jackson nog kon functioneren, moest dat nu gebeuren onder een zweem van verdenking.

Intussen had de Amerikaanse overheid beslagleggingsbevelen uitgevaardigd om achtenvijftig grote e-goudaccounts te sluiten op verdenking van witwassen. De doelwitten van de actie waren onafhankelijke e-goudbeurzen, waarvan sommige in het buitenland waren gevestigd. Door gebruik te maken van de *Racketeering Act* uit 1961 (een instrument voor handhaving van de wet, oorspronkelijk opgesteld om georganiseerde misdaad te bestrijden) werd 1.000 kilogram goud dat deze accounts ondersteunde (ongeveer een kwart van de totale voorraad van e-goud) in beslag genomen en geliquideerd.

Toen er in 2008 eindelijk een voorlopig vonnis kwam, bepaalde de rechter dat e-goud inderdaad een betaaldienst was, en verwierp daarmee Jacksons verzoek om de zaak te seponeren. Aangezien hij nu geconfronteerd werd met de mogelijkheid op een aanzienlijke gevangenisstraf en enorme boetes, besloot Jackson een schikking te treffen.[^6]

In een van de weinige positieve wendingen in het hele verhaal toonde de rechter enige mildheid in haar uiteindelijke vonnis. Ze stelde dat 'de intentie om illegale activiteiten te ondernemen er niet was'.[^7] Toch werd Jackson veroordeeld tot zesendertig maanden voorwaardelijke vrijlating (huisarrest), waarvan zes werden afgedwongen door middel van een enkelband. Hij moest ook 300 uur openbare dienstverlening uitvoeren en een boete van € 200 betalen. Zijn bedrijf kreeg ondertussen een boete van € 600.000. Twee van zijn werknemers -- mede-oprichters Barry Downey en Douglas' broer Reid Jackson -- werden veroordeeld tot zesendertig maanden voorwaardelijke vrijlating, 300 uur dienstverlening aan de gemeenschap en een boete van € 2.500 plus een boete van € 100.

En natuurlijk moest e-goud een licentie verkrijgen voor het opereren van een betaaldienst. Het enige probleem? Als veroordeelde misdadiger kwam Jackson niet langer in aanmerking voor zo'n licentie - iets wat hij niet onmiddellijk had beseft toen hij instemde met de schikking. Net toen hij dacht dat hij eindelijk de juridische strijd voor altijd kon achterlaten en zijn bedrijven op welke manier dan ook kon proberen te redden, ontdekte Jackson dat dit niet onder zijn leiding kon gebeuren.

Uiteindelijk heeft e-goud nooit opnieuw de deuren geopend.

Jackson had e-goud opgericht om het materiële welzijn van mensen te verbeteren door een alternatief te bieden voor conventionele, ongedekte valuta's zoals de Amerikaanse dollar. Opgesloten in zijn eigen huis, met meer dan een miljoen dollar aan juridische kosten op zijn naam, en zijn bedrijf noodgedwongen gesloten, had hij op de pijnlijke les geleerd dat het aanbieden van een dergelijk alternatief niet zonder slag of stoot ging.

## Satoshi Nakamoto

Het lot van Douglas Jackson en e-goud diende als een niet te miskennen waarschuwing voor iedereen met ambities om een alternatieve vorm van geld aan te bieden. Overheden (en met name de Amerikaanse overheid) konden besluiten hard op te treden, wat ernstige persoonlijke en financiële schade zou kunnen berokkenen. Voor de meesten was dit waarschijnlijk het risico niet waard.

Echter, dit hield een onbekend persoon of groep, alleen bekend als 'Satoshi Nakamoto', niet tegen. Rond dezelfde tijd dat Jackson zijn dagen thuis doorbracht met een enkelband om, was Nakamoto bezig met het voorbereiden van de lancering van een eigen elektronisch geldsysteem.

Het ontwerp van Nakamoto's digitale valutasysteem was echter zeer verschillend van e-goud. En hoewel er niet veel bekend is over de achtergrond of beweegredenen van Satoshi Nakamoto, is het duidelijk dat deze mysterieuze entiteit (de naam is vrijwel zeker een pseudoniem) zijn eigen systeem bewust zodanig ontwierp om een soortgelijk lot als e-goud te vermijden.

Dit ontwerp was waarschijnlijk ook niet het resultaat van een spontane ingeving. Al jaren, zelfs ruim voor Jackson e-goud lanceerde, probeerde een kleine maar toegewijde groep technici een digitale vorm van contant geld te creëren: ze wisselden ideeën uit, ontwikkelden technieken, en ontworpen diverse voorstellen. Dit alles in de hoop dichter bij een werkende oplossing te komen. Maar het succes bleef uit.

Totdat Nakamoto eindelijk de puzzelstukjes op hun plek wist te krijgen.

In dit boek gaan we terug naar de ideeën en technologieën die Satoshi Nakamoto (waarschijnlijk) hebben geïnspireerd in het ontwikkelen van dit elektronisch geldsysteem.

In Deel I onderzoekt het boek de gevarieerde oorsprong van sommige van deze grondleggende ideeën en technologieën die de basis vormden voor elektronisch geld. Deze lopen uiteen van heterodoxe zienswijzen over monetaire economie tot een opstandige revolutie in de cryptografie, en van de opkomst van de hackercultuur in de jaren '60 en '70 tot techno-utopische visies op ruimtekolonisatie, moleculaire nanotechnologie en eeuwig leven.

Deel II vertelt het verhaal van de Cypherpunks: een verzameling cryptografen, hackers en privacyactivisten die gedurende de jaren '90 privacyhulpmiddelen ontwikkelden en verspreidden voor het internet, en die probeerden een elektronische versie van contant geld te creëren. Dit deel van het boek focust ook op enkele specifieke pogingen om dergelijke elektronische betalingssystemen te ontwikkelen.

Tot slot beschrijft Deel III van het boek hoe Satoshi Nakamoto zijn elektronische geldsysteem ontwierp en ontwikkelde, wat de inspiratiebron was voor dit ontwerp, en hoe het zich verhoudt tot andere vormen van (digitaal) geld.

Samen vormen zij het verhaal van de monetaire hervormers, computerwetenschappers, activisten voor privacy, futurologen, ondernemers en andere pioniers die, elk op hun eigen manier, bijdroegen aan de opkomst van het eerste succesvolle peer-to-peer elektronische geldsysteem ter wereld: Bitcoin.

[^1]: ​Lawrence H. White, 'The Troubling Suppression of Competition from Alternative Monies: The Cases of the Liberty Dollar and e-gold', Cato Journal, 34, No. 2: 281--301.

[^2]: Huis van Afgevaardigden, 'Deleting Commercial Pornography Sites From the Internet: The U.S. Financial Industry's Efforts to Combat This Problem', Hearing Before the Subcommittee on Oversight and Investigations of the Committee on Energy and Commerce, One Hundred Ninth Congress, Second Session, September 21, 2006, [https://www.govinfo.gov/content/pkg/CHRG-109hhrg31467/html/CHRG-109hhrg31467.htm.]

[^3]: ​White, 'Troubling Suppression', 289.

[^4]: ​e-gold, 'e-gold News', December 1999, geraadpleegd via [https://web.archive.org/web/20001209053900fw...ttp://www.e-gold.com/news.html.]

[^5]: ​e-gold, 'e-gold Welcomes US Government Review of its Status as a Privately Issued Currency', 20 januari 2006, geraadpleegd via [https://web.archive.org/web/20060304203618if...ttp://www.e-gold.com:80/letter2.html.]

[^6]: ​US Department of Justice, 'Digital Currency Business e-gold Pleads Guilty to Money Laundering and Illegal Money Transmitting Charges', July 21, 2008, [https://www.justice.gov/archive/opa/pr/2008/July/08-crm-635.html.]

[^7]: ​e-gold 'Transcript of sentence before the honorable Rosemarie M. Collyer United States District Judge', 114, November 20, 2008, <https://legalupdate.e-gold.com/2008/11/transcript-of-sentence-before-the-honorable-rosemarie-m-collyer-united-states-district-judge.html>
