# De Cypherpunk-beweging

Tim May kon een glimp van de toekomst zien. Hij had een gave om het potentieel van nieuwe technologieën te herkennen en kon voorspellen hoe ze de samenleving zouden beïnvloeden voordat bijna iemand anders dat kon.

Het meest opvallend was dat May al vroeg inzag hoe belangrijk persoonlijke computers en het internet zouden worden. Zo vroeg als 1973 bemachtigde hij een primitieve DARPA-account op de campus van de UC Santa Barbara, waar hij natuurkunde studeerde. Een jaar later, op 22-jarige leeftijd, kreeg hij een baan bij Intel, waar hij zou werken in de Memory Products Division.

De jonge natuurkundige leverde een belangrijke bijdrage in de vroege geschiedenis van het bedrijf door het alfadeeltjesprobleem op te lossen: May ontdekte dat de geïntegreerde schakelingen van Intel onbetrouwbaar waren vanwege licht radioactief verpakkingsmateriaal. Dit zette hem op weg naar een geweldige carrière bij de snelgroeiende fabrikant van halfgeleiderchips.

Omdat hij een deel van zijn salaris in de vorm van aandelenopties ontving, had de natuurkundige van Intel ongeveer een decennium later, tegen midden jaren 80, een klein fortuin vergaard: op slechts vierendertigjarige leeftijd concludeerde May dat hij genoeg rijkdom had verzameld om de rest van zijn leven te onderhouden. Hij besloot vroegtijdig met pensioen te gaan en verhuisde naar Santa Cruz, een kustplaats zo'n dertig mijl ten zuiden van San Jose, Californië. Het grootste deel van het daaropvolgende jaar bracht hij door in een comfortabele strandstoel om boeken over economie, technische papers en cyberpunkromans te lezen.

Cyberpunkverhalen, een relatief nieuw genre in die tijd, speelden zich meestal af in high-tech dystopieën. De boeken schilderden over het algemeen een grimmige versie van de toekomst, maar eentje waarin het internet (of een geëvolueerde versie ervan) een toevluchtsoord bood voor hun vrijheidsgezinde hoofdpersonen. In *True Names* van Vernor Vinge, verbergen een groep hackers zich voor de sterke mannen van de regering door hun pseudonieme avatars vrijelijk te laten rondzwerven door een kleurrijke en driedimensionale representatie van het internet zelf. In *Snow Crash* van Neil Stephenson verloren naties grotendeels hun macht aan grote bedrijven en de maffia, terwijl mensen aan hun miezerig bestaan ontsnapten door alternatieve levens te leiden in een virtuele wereld. En *Neuromancer* van William Gibson presenteert evenzo een wereldwijd verbonden, virtuele realiteitsomgeving als een kleurrijk alternatief voor een vijandige onderwereldmaatschappij.

May was van plan om uiteindelijk zelf een cyberpunkroman te schrijven, gemodelleerd naar Ayn Rand's *Atlas Shrugged*. In Rand's verhaal, dat oorspronkelijk in 1957 werd gepubliceerd, omarmt een Amerika in verval socialistische doctrines, terwijl het Amerikaanse volk zich afkeert van de meest succesvolle ondernemers van het land. Sommige van deze ondernemers besluiten uiteindelijk om "in staking" te gaan: een kleine gemeenschap van doorgewinterde vernieuwers vestigt zich in een afgelegen bergketen genaamd "Galt's Gulch," en gebruiken een scherm van hittegolven en reflectoren om zich te verbergen voor de buitenwereld. De subtiele boodschap van het boek is dat Amerika's meest ijverige ondernemers niet gedemoniseerd, maar gekoesterd en gevierd zouden moeten worden.

Na het lezen van Rand's meesterwerk 'Atlas Shrugged' als tiener, had dit boek May op het spoor gezet om meer te leren over vrije markten en libertarisme. Uiteindelijk zou hij zich toeleggen op de studie van de Oostenrijkse economie, en in het bijzonder, op de theorieën van Friedrich Hayek.

Dit alles maakte dat de aspirant-schrijver zich als vanzelfsprekend thuis voelde in een niche subcultuur in Californië die in de jaren '80 opkwam. Via enkele van zijn lokale vrienden leerde May de Extropianen kennen en vond hij een ideologische thuis. Hoewel hij niet volledig mee was met enkele van de meer buitensporige toekomstvisies van de transhumanisten (ideeën zoals eeuwig leven, het uploaden van de hersenen of een AI singulariteit) was hij wel toegewijd aan vrijheid en technologische vooruitgang.

In deze context raakte Tim May bevriend met Phil Salin, de "high-tech Hayekiaan" die tevergeefs had geprobeerd om een privé ruimtetransportindustrie op te zetten met zijn startup Starstruck. May en Salin deelden een passie voor zowel de Oostenrijkse economie als technologie. Beiden geloofden dat de voormalige verder kon worden ontwikkeld door de laatste te benutten.

## BlackNet

May had ongeveer een jaar op het strand doorgebracht met boeken toen Salin hem vertelde over AMIX, het ambitieuze internetproject waar hij aan werkte.

AMIX, legde Salin aan zijn vriend uit, zou een online marktplaats zijn voor het kopen en verkopen van informatie. Hij vertelde May hoe dit de transactiekosten sterk zou kunnen verlagen, wat enorme voordelen zou opleveren voor de vrije markt. Hij vroeg May wat hij van het idee vond; Salin wilde graag de feedback van zijn vriend horen.

Het concept leek May inderdaad interessant. Maar na er even over na te denken, kwam hij tot de conclusie dat zijn interesse voor heel andere redenen werd gewekt dan die van Salin. May vertelde zijn vriend dat hij dacht dat deskundig advies of winkeltips, de soorten informatie waar Salin aan had gedacht, waarschijnlijk niet echt waardevol zouden zijn. Maar hij geloofde wel dat er een hoge vraag zou zijn naar een heel andere categorie van informatie.

Geheime informatie.

Mensen zouden bereid zijn om veel geld te betalen voor bedrijfsgeheimen, geclassificeerde overheidsdocumenten, militaire inlichtingen, kredietgegevens, medische dossiers, verboden religieus materiaal of illegale pornografie, stelde May voor.[^142] En belangrijk, sommige mensen die toegang hebben tot dit soort informatie zouden bijna zeker bereid zijn om het te verkopen voor de juiste prijs, als ze dat anoniem kunnen doen.

Natuurlijk wist May dat het kopen en verkopen van dit soort informatie in veel gevallen illegaal zou zijn. Als het op AMIX zou worden gezet, zou Salin naar alle waarschijnlijkheid gedwongen worden om de handel ervan te verbieden. Maar May voorzag dat dit uiteindelijk geen echt verschil zou maken. De ontwikkelingen op het gebied van cryptografie die hij in academische tijdschriften had gelezen, zouden uiteindelijk in handen van mensen komen, legde hij aan Salin uit, dus het was slechts een kwestie van tijd totdat er een volledig anonieme variant van AMIX zou ontstaan waar gebruikers alleen bekend zijn bij hun pseudoniemen, en aankopen werden gedaan met anoniem digitaal geld.

May gaf deze vorm van informatiemarkt de naam *BlackNet*.

In de maanden na zijn eerste gesprek met Salin, bleef May nadenken over de bredere implicaties die een dienst als BlackNet met zich mee zou brengen. Door zijn eigen ideeën verder uit te werken, kwam hij tot de conclusie dat anonieme informatiemarkten uiteindelijk het fundamenteel onveilig konden maken voor grote bedrijven om hun medewerkers überhaupt met gevoelige informatie te laten omgaan. Deze medewerkers zouden immers altijd in de verleiding kunnen komen om een extra zakcentje te verdienen door de data online te verkopen.

Volgens May zou dit een soort catch-22 situatie kunnen introduceren. Bedrijfsgeheimen zouden bedrijven vermoedelijk een voorsprong op hun concurrenten geven als ze op grote schaal binnen het bedrijf worden gebruikt, maar in dat geval zou het waarschijnlijk slechts een tijdelijke voorsprong zijn voordat de informatie naar de concurrenten lekte. Of, de bedrijfsgeheimen zouden op een zeer beperkte schaal gebruikt kunnen worden om lekken te voorkomen, in welk geval de voorsprong op de concurrenten ook niet zo groot zou zijn.

Mogelijk, zo stelde May voor, zou het simpele bestaan van een BlackNet de economische prikkels die grote bedrijven in de eerste plaats levensvatbaar maken, fundamenteel kunnen dooreen schudden. In plaats van miljardenbedrijven zouden we door radicale transparantie een meer verspreide en levendige economie kunnen zien, gekenmerkt door een veel diverser aanbod aan kleinere bedrijven.

En May realiseerde zich uiteindelijk dat deze dynamiek niet alleen grote bedrijven zou beïnvloeden. Het zou ook net zo goed regeringen en hun strijdkrachten kunnen beïnvloeden, evenals andere openbare instellingen die vertrouwelijke informatie verwerken. Een enkele corrupte overheidsmedewerker met financieel gewin als motief zou voldoende zijn om allerlei geclassificeerde dossiers te verspreiden naar de best betalende kopers op het internet. Niet in staat om gevoelige gegevens te beveiligen, zou de macht van de overheid aanzienlijk kunnen afzwakken. May was dol op dit idee.

En ook een andere lokale vriend van hem...

## Eric Hughes

Toen Eric Hughes in de late jaren 80, toen hij halfweg de twintig was, wiskunde studeerde aan Berkeley, had de cryptografische revolutie zijn weg al in het curriculum gevonden. Tegen de tijd dat hij afstudeerde, was hij goed op de hoogte van recente innovaties van mensen zoals Whitfield Diffie, Martin Hellman, Ralph Merkle en David Chaum. En net zoals zij, begreep Hughes intuïtief het veelbelovende potentieel van hun doorbraken in de context van een steeds meer gedigitaliseerde samenleving.

Hughes ontdekte dat fundamentele mensenrechten, zoals het recht op privacy, constant onder druk stonden van overheden. Zelfs al waren sommige van deze rechten juridisch gewaarborgd, leek het erop dat overheden altijd een manier vonden om inbreuk te maken als ze daartoe de mogelijkheid kregen.

Voor Hughes bood moderne cryptografie een methode om individuele privacy te beschermen, zonder te moeten vertrouwen op wetten, de interpretatie ervan door politici of rechters. Het recht op privécommunicatie kon in plaats daarvan gewaarborgd worden door technologieën zoals openbare sleutel-cryptografie en mixnetwerken.

Hughes besefte dat het niveau van privacy dat bereikt kon worden met sterke cryptografie, uiteindelijk volledige immuniteit tegen fysieke bedreigingen en dwang kon bieden. Zolang anonieme internetgebruikers hun werkelijke identiteit geheim konden houden, kon niets dat ze online zouden doen of zeggen hen mogelijk in fysiek gevaar brengen.

Toen de jonge wiskundige hoorde dat Chaum een bedrijf had opgericht in Nederland om een elektronisch geldsysteem te implementeren, besloot de afgestudeerde van Berkeley om er te solliciteren. Net als Chaum geloofde hij dat geld hoe dan ook digitaal zou worden, en een privacybehoudende vorm van valuta kon het verschil betekenen tussen een vrije samenleving en een totalitaire dystopie. Bovendien geloofde Hughes dat de cryptografische protocollen van Chaum het potentieel hadden om dat verschil te maken. Chaum, op zijn beurt, geloofde dat Hughes een goede aanvulling zou zijn voor zijn bedrijf; hij werd aangenomen.

Toen Hughes in 1991 in Amsterdam aankwam om zijn nieuwe avontuur te beginnen, raakte hij vrij snel gedesillusioneerd door wat hij in de kantoren van DigiCash aantrof. Hij ontdekte tot zijn ontsteltenis dat Chaum smartcards, de fraudebestendige creditcard-achtige computers speciaal ontworpen voor betalingen, tot hoeksteen van zijn ontwerp had gemaakt. In plaats van zich puur te richten op de kracht van wiskunde en het perfectioneren van de cryptografische protocollen die nodig waren om elektronisch geld voor het internet te implementeren, zag hij dat DigiCash zich concentreerde op dure en niet-controleerbare hardwareproducten om offline betalingen mogelijk te maken.

Hughes was van mening dat Chaum een ernstige strategische fout maakte door pragmatiek en kostenefficiëntie te onderschatten ten gunste van experimentele features. Uiteindelijk kwam de jonge wiskundige tot de conclusie dat DigiCash toch niet de plek voor hem was. Na slechts zes weken in Amsterdam vertrok hij bij de startup.

Eenmaal terug in Californië, overwoog Hughes op zoek te gaan naar een woning die iets dichter bij de zee lag. Hij besloot een paar dagen in Santa Cruz door te brengen om een huis te zoeken. Hij kon er verblijven bij een oude vriend die daar een paar jaar eerder naartoe was verhuisd: Tim May.

Toen Eric Hughes in 1991 in Santa Cruz aankwam, deelde May zijn visie voor anonieme informatie markten met hem. Hij legde uit hoe BlackNets gebruik zouden maken van het soort privacy tools die Hughes had bestudeerd en wilde bouwen, en hoe deze de macht van grote bedrijven en overheidsinstellingen konden verminderen, of zelfs volledig beperken.

Hoewel Hughes zichzelf niet zozeer als een libertariër van de vrije markt beschouwde zoals Tim May dat deed, intrigeerde het concept van anonieme informatiemarkten hem net zo goed. De komende paar dagen konden ze het alleen maar hebben over het enorme potentieel van moderne cryptografie. Terwijl ze filosofeerden over de implicaties van anonieme netwerken, de levensvatbaarheid van pseudonieme reputatiesystemen, en de vooruitzichten van grenzeloze betalingen, moest de huizenjacht even wachten.

Maar na enkele dagen te hebben gediscussieerd over mogelijk baanbrekende toepassingen voor publieke sleutel-encryptie, remailers en digitaal geld, leidden hun gesprekken steeds weer terug naar dezelfde knagende vraag.

*Waarom was er nog steeds geen software die deze protocollen implementeerden?*

Geen van de baanbrekende crypto-innovaties die sinds de jaren 70 werden voorgesteld, werden in de praktijk gebracht door echte mensen, omdat er geen computerprogramma's beschikbaar waren die deze protocollen implementeerden. Terwijl academische papers in detail uitlegden hoe Alice en Bob privé konden communiceren dankzij de Diffie-Hellman sleuteluitwisseling of RSA-encryptie, was dit aan het eind van de dag volledig nutteloos zolang er geen software bestond die deze taken voor Alice en Bob uitvoerde.

Toegegeven, er waren wel een paar projecten in ontwikkeling. In feite werkte Chaum aan een elektronisch betaalsysteem, hoewel hij dat niet helemaal ontwikkelde op de manier die Hughes graag zou zien. Daarnaast werkte een van May's collega-Extropianen, de lokale Bay Area computerwetenschapper en cryptograaf Phil Zimmermann, aan een op RSA-gebaseerde openbare sleutelencryptiesoftware genaamd *Pretty Good Privacy* (PGP).

Toch leken dit erg magere resultaten, als je bedenkt hoe groot de doorbraken waren die May en Hughes zo enthousiast maakten voor de toekomst. Hoewel de nieuwe golf van crypto zich ongeveer vijftien jaar door het academia had verspreid, en een serie succesvolle Crypto-conferenties een reeks baanbrekende concepten hadden voorgesteld, bleef de daadwerkelijke softwareontwikkeling ver achter.

## De vergadering

Eric Hughes verhuisde uiteindelijk niet naar Santa Cruz. Maar de reis was zeker niet verspild. Gedurende zijn bezoek aan het stadje aan het strand kwamen Hughes en May overeen dat het tijd was om het gat tussen de academische wereld en de echte wereld te dichten, en zij concludeerden dat zij zelf het initiatief moesten nemen om dit te laten gebeuren. May en Hughes zetten zich in voor het bijeenbrengen van een groep van enkele van de slimste en meest bekwame cryptografen en hackers uit de Bay Area, en gingen aan het werk.

De eerste persoon die ze bij hun plan betrokken was John Gilmore, een vroege medewerker van Sun Microsystems en medeoprichter van de digitale rechtenorganisatie *Electronic Frontier Foundation* (EFF). Hij had binnen lokale hackerskringen al geruime tijd gesproken over het brengen van cryptografie naar het grote publiek. De drie van hen (May, Hughes en Gilmore) begonnen vervolgens meer gelijkgestemde individuen uit te nodigen die volgens hen niet zouden terugdeinzen voor enige hands-on technologie activisme.

Een paar maanden verstreken, tot op een zaterdag in september een groep van ongeveer twee dozijn gelijkgestemde individuen zich verzamelde in Hughes' nieuwe en op dat moment nog ongemeubileerde appartement in Oakland. De meeste aanwezigen waren afkomstig uit de hacker-gemeenschap in de Bay Area, terwijl May ook een kleine Extropian-delegatie had geregeld. Dit zorgde voor een bijzonder technologiebewuste groep mensen.

May opende de bijeenkomst met een inleiding over cryptografie. Hij bracht de aanwezigen op de hoogte van het veelbelovende potentieel van openbare sleutel-cryptografie evenals enige van de innovatieve schema's die waren voorgesteld sinds de doorbraak van Diffie en Hellman. Hierna deelde hij een door hemzelf samengesteld boekje uit waarin de basisprincipes werden uitgelegd en belangrijke termen werden gedefinieerd. De groep begon vervolgens te discussiëren over de mogelijke gevolgen voor de samenleving als cryptografische hulpmiddelen op grote schaal beschikbaar zouden worden, maar daar tegenover ook de onrustbarende implicaties van een toekomst zonder dergelijke hulpmiddelen.

In de namiddag begon de hele bende, vanwege een gebrek aan meubels zittend op de vloer, op speelse wijze te experimenteren met analoge representaties van cryptoprotocollen. Ze creëerden het op papier gebaseerde "crypto-anarchie-spel", waarbij enveloppen fungeerden als een protocol voor het anonimiseren van berichten, een prikbord fungeerde als een informatiebeurs en Monopolie-geld werd rondgegeven alsof het digitale contanten waren. Op een leuke manier kreeg iedereen een gevoel van hoe deze systemen zouden functioneren.

De bijeenkomst was een succes. Aan het einde van een dag vol mini-seminars, brainstormsessies en spelletjes, was iedereen die het appartement van Hughes had bereikt voor deze speciale gelegenheid, aangestoken met hetzelfde gevoel van enthousiasme dat May, Hughes en Gilmore had aangezet om deze unieke groep mensen bij elkaar te brengen. Belangrijker nog, ze deelden nu de visie van de organisatoren dat de crypto-protocollen waarover ze hadden geleerd, geïmplementeerd moesten worden als werkende software en zo ver mogelijk verspreid moesten worden. Om de zaak verder te bevorderen, gingen ze ermee akkoord om de bijeenkomst een maandelijks evenement te maken.

Op dit moment concludeerde de groep ook dat ze een pakkende naam nodig hadden om zichzelf mee te omschrijven. Hughes had het tot dan toe de Cryptologie Amateurs voor Sociale Onverantwoordelijkheid (of kortweg CASO) genoemd, maar nu overwogen ze suggesties zoals "De Crypto Vrijheid Liga", "Privacy Hackers", en "De Crypto Cabal". Middenin al dit gepraat riep Hughes' vriendin van dat moment, hacker Jude Milhon, gekscherend uit: "Jullie zijn gewoon een stel cypherpunks!"[^143]

Met de slimme samentrekking van "cipher" en "cyberpunk," had de groep hun naam te pakken.

## De Cypherpunks

De bijeenkomsten die volgden, werden op wisselende locaties gehouden, vaak bij iemand thuis of in iemands werkruimte, en vormden een centraal punt voor het delen van informatie, discussie en projectcoördinatie. Natuurlijk bood het iedereen ook de kans om elkaar wat beter te leren kennen, terwijl nieuwe mensen welkom waren om zich aan te sluiten en meer te leren over het initiatief en hoe ze konden deelnemen.

De Cypherpunks schetsten tijdens deze vroege bijeenkomsten toekomstige doelen en werkten hun strategieën uit om deze doelen te bereiken.

Allereerst hadden de Cypherpunks zich tot dusverre tot doel gesteld om een dystopische toekomst te voorkomen, een toekomst waarin digitale communicatie kan worden gemonitord, geanalyseerd en uiteindelijk misbruikt. Net zoals de cryptografen die hen inspireerden, waren ze bezorgd dat zo'n verlies aan privacy despoten en tirannen zou kunnen versterken, ten koste van de individuele vrijheden: May kondigde op een gegeven moment half-grappend aan dat George Orwell's *1984* verplichte lectuur was voor iedereen binnen de groep.

Maar de Cypherpunks waren niet alleen van plan om privacy te promoten of te eisen. Ze zouden zich niet beperken tot het lobbyen bij verkozen ambtenaren, of werken via het politieke en juridische proces, zoals sommige bestaande belangenorganisaties (zoals de EFF) al deden.

Een belangrijk onderdeel van hun strategie was dat de Cypherpunks zelf de behoeder van hun privacy gingen worden.[^144]

"We moeten onze eigen privacy verdedigen als we verwachten er nog enige te hebben," schreef Hughes in "Het Manifest van de Cypherpunk," dat de mede-oprichter van de groep hardop voorlas tijdens een Cypherpunk-bijeenkomst begin 1993. "We moeten samenkomen en systemen creëren die anonieme transacties mogelijk maken. Mensen hebben eeuwenlang hun eigen privacy verdedigd met gefluister, duisternis, enveloppen, gesloten deuren, geheime handdrukken en koeriers. De technologieën van het verleden boden geen sterke privacy, maar elektronische technologieën doen dat wel."

Ze hadden plannen om deze elektronische technologieën te ontwikkelen en deze als gratis software te verspreiden. In overeenstemming met de hacker-ethiek, hadden ze niet de intentie om iemand om toestemming te vragen om dit te doen.

"Cypherpunks schrijven code", verklaarde Hughes. "We weten dat iemand software moet schrijven om privacy te verdedigen, en wij gaan dat doen."[^145]

"Cypherpunks schrijven code". Dit werd de informele strijdkreet van de groep.

## De mailinglijst

De maandelijkse bijeenkomsten van de Cypherpunks waren vrij en open van aard. Naast de vaste kern van reguliere deelnemers, kwamen er ook nieuwsgierige nieuwkomers om een indruk te krijgen van wat er gaande was. Om de coördinatie hiervan te vergemakkelijken, richtte Hughes een e-maillijst op, gehost op de computer van Gilmore, waar hij aankomende evenementen aankondigde. Elke abonnee ontving handig een bericht in hun inbox met daarin de datum en locatie.

Maar de mailinglijst van de Cypherpunks zou al snel een groter doel gaan dienen. Het duurde niet lang voordat de lijst werd gebruikt om discussies van de fysieke vergaderingen voort te zetten. Niet veel later werden er volledig nieuwe onderwerpen op de mailinglijst geïntroduceerd, die niets te maken hadden met wat er besproken was tijdens de persoonlijke bijeenkomsten. Toen het aantal berichten toenam, begon de mailinglijst van de Cypherpunks een eigen leven te leiden.

E-mail had natuurlijk als extra voordeel dat iedereen kon deelnemen, ongeacht de geografische afstand, en vanuit het comfort van hun eigen huis. Vrij voorspelbaar, groeide de Cypherpunks mailinglijst snel en overtrof die de aantallen van de feitelijke Cypherpunk evenementen. Slechts weken na de lancering had de lijst al 100 abonnees, beduidend meer dan de paar dozijn hackers en cryptografen die de maandelijkse bijeenkomsten bijwoonden.

En de populariteit van de mailinglijst explodeerde pas echt toen het technologietijdschrift Wired in mei 1993 zijn cover-verhaal wijdde aan de Cypherpunks. "Rebellen met een doel (jouw privacy)" stond er op de cover, net boven een foto van drie gemaskerde mannen die de Amerikaanse vlag vasthielden (De uitdrukkingsloze witte maskers met computercodecode erop gekrabbeld verborgen de gezichten van May, Hughes en Gilmore). Dankzij dit cover-verhaal had nu vrijwel iedereen met interesse in computers gehoord van de groep privacy-activisten en door hun wereldwijde bereik, stroomden honderden mensen van over heel de Verenigde Staten en de rest van de wereld toe om zich aan te melden voor hun e-maillijst.

In de daaropvolgende jaren werd de Cypherpunks mailinglijst een klein fenomeen op het vroege internet. Met tot wel 2.000 abonnees en soms bijna evenveel e-mails per maand, bespraken de Cypherpunks een breed scala aan onderwerpen: van cryptoprotocollen, tot overheidsbeleid, tot implementaties van software, en tips voor boeken of films, evenals periodieke klaagzangen en verhitte discussies. De lijst bood een platform voor publieke discussie tussen enkele van de meest getalenteerde hackers op de planeet, terwijl Silicon Valley's CEO's en mainstream journalisten ook graag meelazen.

Tim May onderscheidde zich op de mailinglijst dankzij zijn vele mails: niemand was actiever dan hij, en niemand leverde een groter aanbod aan bijdragen. Hij schetste toekomstscenario's, deelde ideeën, nam deel aan discussies, gaf technische uiteenzettingen, stelde strategieën voor, gaf commentaar op actuele gebeurtenissen, linkte naar relevante artikelen en deelde regelmatig "snel geschreven" essays, soms zelfs verscheidene op een dag.

Maar hij onderscheidde zich ook door zijn unieke gevoel voor humor. Soms voerde hij sarcastisch het woord tegen de Cypherpunk-agenda vanuit het perspectief van een Ingsociaanse overheid en kafferde hij andere deelnemers aan de lijst uit als "burgereenheden". Andere keren maakte hij opzettelijk politiek incorrecte grappen om de grenzen uit te dagen van wat als sociaal acceptabel werd beschouwd. Zo veranderde hij op een gegeven moment bijvoorbeeld zijn e-mailhandtekening in "een bijbeltekst in afwachting van beoordeling onder de Communications Decency Act", waarbij de begeleidende tekst een incestueuze orgie beschrijft.[^146] Of misschien overschreed hij de sociaal aanvaardbare grenzen ronduit, afhankelijk van wie je het zou vragen. May leek er hoe dan ook niet veel om te geven.

En zijn aanwezigheid op de mailinglijst diende ook nog een ander waardevolle doel. Hoewel de lijst volledig ongemodereerd was, speelde May vaak de rol van een onofficiële moderator, en begeleidde gesprekken waar nodig. Als een discussie dreigde te ontsporen, had hij de gewoonte om zijn kenmerkende analytische perspectief in te brengen, waarbij hij uitlegde waarom hij geloofde dat bepaalde opmerkingen of onderwerpen al dan niet geschikt waren voor de lijst, maar zonder daadwerkelijk iets te verbieden; hij wilde niet dat iemand die macht had, zelfs hijzelf niet. In plaats van anderen op te leggen hoe ze zich moeten gedragen, had May een manier om het voortouw te nemen door voorbeeld, en wanneer andere abonnees klaagden over de inhoud op de mailinglijst, moedigde hij hen ook aan om het voortouw te nemen door voorbeeld.

Voor veel van zijn abonnees was May in de maanden en jaren dat de lijst actief was waarschijnlijk de belichaming van wat de Cypherpunk-filosofie voorstelde. Door zijn sterke aanwezigheid, zowel qua inhoud als in zijn sturende rol, was hij een leidende en kenmerkende stem van de beweging geworden.

May zelf, daarentegen, benadrukte vaak dat hij niet de hele Cypherpunk-gemeenschap vertegenwoordigde. Net zoals hij geen enkele moderator in controle wilde hebben over de mailinglijst, verwierp hij ten stelligste het idee dat hij, of wie dan ook, als een formele leider of woordvoerder van de beweging beschouwd moest worden. Hij stond erop dat hij slechts één stem was van de velen.

"Hoewel ieder van ons wellicht zijn of haar persoonlijke (hiërarchische) rangorde van anderen heeft, is het belangrijk dat we nooit hebben geprobeerd deze rangordes te formaliseren of erover te 'stemmen'. Of te stemmen om een Grote Leider te kiezen", betoogde May op een gegeven moment. "Onze kracht zit in onze aantallen en in onze ideeën, niet in de man die we op een kantoor in Washington hebben geïnstalleerd zodat hij persconferenties kan geven en *oneliners* kan leveren voor journalisten. Onze kracht zit in ons meerkoppige (durf ik 'Medusa' te zeggen?), multinationale, informeel gebrek aan structuur."[^147]

Inderdaad, de Cypherpunks waren geen organisatie in de traditionele zin van het woord. Het was een bewust informele, ongestructureerde en open groep. De Cypherpunks hadden geen stemprocedure, geen vertegenwoordigers, en ze gaven zelfs geen gezamenlijke verklaringen. Iedereen kon een Cypherpunk worden, maar alle Cypherpunks zetten zich uiteindelijk in als individuen. Ze hadden geen specifieke taken of regels, noch kon iemand anderen verantwoordelijk houden voor hun eigen acties.

Toch werd actie aangemoedigd. Als iemand vond dat de Cypherpunks een specifieke technologie moesten ontwikkelen, aan een bepaald evenement moesten deelnemen of op een andere manier tot de zaak konden bijdragen, was het aan die persoon om het initiatief te nemen en te kijken of anderen ook wilden helpen.

In feite werkte de Cypherpunk-beweging niet alleen aan een ander type toekomst. Voor May vertegenwoordigde het die toekomst al. Hij zag de open, toestemmingloze en non-hiërarchische manier waarop de Cypherpunks en hun e-maillijst opereerden als een model voor een opkomende *crypto-anarchistische* samenleving.

## Crypto-anarchie

De Extropians speculeerden soms over het creëren van vrije gebieden om te ondermijnen, zich te verbergen, of te ontsnappen aan staatscontrole over hun levens. Sommigen van hen stelden voor om steden te bouwen op grote drijvende eilanden in de zee -- het zogenaamde *seasteading* -- als de weg voorwaarts. Anderen geloofden dat het misschien mogelijk zou zijn om een klein eiland op te kopen om er een libertaire samenleving te stichten. Weer anderen suggereerden dat ze allemaal naar een specifieke jurisdictie moesten verhuizen en proberen lokale politieke structuren te beïnvloeden om zoveel mogelijk wetten en regulaties aan de kant te zetten.

Maar Tim May had eigenlijk niet echt zin om te verhuizen. Hij had een beter idee.

Sinds May de stukjes bij elkaar had gevoegd om het ontwrichtende potentieel van anonieme informatiemarkten te zien, was hij een toekomst gaan visualiseren die leek op de werelden uit zijn cyberpunk boeken, terwijl hij tegelijkertijd analogieën maakte met *Atlas Shrugged*. Hij besefte dat het soort samenleving dat hij wilde beschrijven in zijn aankomende roman, werkelijkheid kon worden.

In de roman van Rand maken de productieve ondernemers hun ontsnapping mogelijk met behulp van futuristische technologie. Hoewel May erkende dat warmtestralingsschermen nog steeds tot het domein van de sciencefiction behoorden, was de medeoprichter van de Cypherpunk-beweging gaan inzien dat het internet en sterke cryptografie uiteindelijk een vergelijkbare ontsnapping uit de macht van de staat konden faciliteren, net als in de verhalen van de cyberpunk-genre.

May schetste deze visie in "Het Crypto-anarchistisch manifest".[^148] Hij schreef het oorspronkelijk voor de editie van de Crypto-conferentie in 1988, las het korte manifest voor tijdens de allereerste bijeenkomst van de Cypherpunks in Hughes's appartement en deelde het later ook via hun mailinglijst.

"Een spook waart rond in de moderne wereld, het spook van de crypto-anarchie", begon het manifest met een knipoog naar het Communistisch Manifest van Karl Marx en Friedrich Engels, voordat het voorspelde dat computertechnologie en cryptografische protocollen "de aard van de overheidsregulering volledig zullen veranderen, het vermogen om de economische interacties te belasten en te controlen, het vermogen om informatie geheim te houden, en zelfs de aard van vertrouwen en reputatie zullen veranderen."

Om een paar paragrafen verder te concluderen:

"Net zoals de technologie van drukken de macht van de middeleeuwse gilden en de sociale machtsstructuur heeft veranderd en verminderd, zo zullen cryptologische methoden de aard van bedrijven en de inmenging van de overheid in economische transacties fundamenteel veranderen."[^149]

Het internet was nog niet getransformeerd naar de kleurrijke 3D-wereld zoals die in de romans van Vinge, Stephenson en Gibson werd voorgesteld. Maar als je deze verhalen meer als metaforische representaties van online domeinen beschouwde, had May ze toch als visionair leren waarderen. Terwijl het internet verder zijn onvermijdelijke pad naar massa-adoptie vervolgde, en mensen stapje voor stapje zouden leren om zichzelf online te organiseren, geloofde May dat de instellingen van de reële wereld uiteindelijk zouden worden vervangen door hun cyber-equivalenten. Het internet zou in toenemende mate dienen als facilitator voor een parallelle, digitale samenleving, met eigen gemeenschappen, ondernemingen en uiteindelijk ook eigen economieën.

"Dit maakt snelle experimentatie, zelfselectie en evolutie mogelijk", stelde May voor op de Cypherpunks mailinglijst. "Als mensen een bepaalde virtuele gemeenschap beu raken, kunnen ze deze verlaten. De cryptografische aspecten zorgen ervoor dat hun lidmaatschap van een bepaalde gemeenschap onbekend blijft voor anderen (vis-a-vis de fysieke of buitenwereld, oftewel, hun 'echte namen') en fysieke dwang vermindert."

Verdergaand: "De elektronische wereld is geenszins volledig, aangezien we nog steeds een groot deel van ons leven in de fysieke wereld zullen doorbrengen. Maar de economische activiteit in het domein van het Net neemt sterk toe en deze ideeën van 'crypto-anarchie' zullen de macht van fysieke staten om inwoners te belasten en te dwingen verder ondermijnen."[^150]

Dit alles werd mogelijk gemaakt door de kracht van cryptografie. Niet alleen zouden crypto-middelen gebruikers helpen hun echte identiteit te beschermen, waardoor ze beschermd werden tegen fysiek geweld, maar zouden dezelfde middelen ook toestaan dat twee personen zaken konden doen zonder dat een van hen ooit wist met wie ze te maken hadden.

"[...] sterke cryptografie is het 'bouwmateriaal' van cyberspace", schreef May aan zijn mede-Cypherpunks, "de mortel, de bakstenen, de steunbalken, de muren. Niets anders kan de 'permanentie' bieden... zonder crypto zijn de muren bij de eerste aanraking door een kwaadwillend persoon of organisatie onderhevig aan instorting. Met crypto kan zelfs een 100 megaton waterstombom de muren niet doorbreken."[^151]

May voorzag dat Cypherpunk-tools mensen zouden helpen om hun economische activiteit voor de staat te verbergen en zo een "Galt's Gulch in cyberspace" zouden creëren. Hij keek uit naar een toekomst waarin dit uiteindelijk zou leiden tot de volledige ineenstorting van regeringen. Zonder gedwongen herverdeling van welvaart, zou deze toekomstige economie zichzelf organiseren rondom vrijwillige interactie en vrije markten. Er zou een *spontane orde* ontstaan via het internet.

"In feite heeft Hayek héél véél met de Cypherpunks te maken!" schreef May op de Cypherpunk mailinglijst. "Van 'The Road to Serfdom' tot 'Law, Legislation, and Liberty', zijn werken hebben diepgaande invloed op mij gehad en op vele anderen. [...] Ik zou zelfs zeggen dat Hayek een kandidaat zou zijn geweest om op de cover van 'Wired' te staan... natuurlijk ervan uitgaande dat hij 60 jaar jonger was, sommige van zijn lichaamsdelen had gepiercet, en beter nog, een Netchick was."[^152]

## Code

Tim May was er zich goed van bewust dat de crypto-anarchistische ideeën die hij verspreidde niet precies aantrekkelijk waren voor een breed publiek; niet iedereen hoopt op een ineenstorting van regeringen. Waarschijnlijk zou het nog erger worden als men erachter zou komen dat onkraakbare encryptie en anonieme mixnetwerken grootschalige verspreiding van kinderpornografie mogelijk maakten en veilige communicatie voor terroristische cellen faciliteerden. Veel mensen zouden deze nieuwe instrumenten waarschijnlijk met angst en woede bekijken.

Maar May weigerde de risico's die deze nieuwe technologieën introduceerden te bagatelliseren.

"Privacy heeft zijn prijs", betoogde hij simpelweg. "Het vermogen van mensen om achter gesloten deuren misdaden te beramen en te plegen is evident, en toch eisen we geen verborgen camera's in woningen, appartementen en hotelkamers!"[^153]

Voor May was crypto-anarchie bovendien geen verre utopie die brede steun voor zijn ideeën vereiste: integendeel, hij beschouwde het bijna als een voldongen feit. Hij begreep dat de weg ernaartoe bezaaid kon zijn met tegenslagen en onderdrukkende wetten, gerechtvaardigd door beleidsmakers die angst inboezemden over de "Vier Ruiters van de Infocalyps": terroristen, pedofielen, witwassers en pornografen. Maar cypherpunk tools waren goedkoop te verspreiden, makkelijk te gebruiken en konden niet on-uitgevonden worden. Op de lange termijn, geloofde May, was succes vrijwel gegarandeerd.

Dit betekende niet dat elke Cypherpunk Mays nogal radicale visie deelde, noch hoefden ze dat te doen. Vaker wel dan niet waren Cypherpunks libertariërs, maar velen onderschreven ook een gematigder wereldbeeld dan May. Sommige Cypherpunks waren zelfs helemaal geen libertariërs, met meerdere van hen die zichzelf identificeerden als socialist.

"Ik ben geen libertariër, en het is onwaarschijnlijk dat ik dat ooit zal zijn", schreef Hughes aan de mailinglijst. "Het streven naar privacy staat los van de meeste partijpolitieke standpunten. Zo sterk als de libertarische aanwezigheid op deze lijst is, is het geenszins de enige visie. Juist omdat cypherpunk kwesties dwars door het politieke spectrum snijden, zijn ze zo krachtig."[^154]

Wat van belang was, stemden May en Hughes mee in, was dat de Cypherpunks ongeacht hun politieke overtuiging konden werken aan een gezamenlijk doel: het ontwikkelen en verspreiden van tools voor privacy. *Cypherpunks schrijven code*.

Inderdaad, de groep was nauwelijks gestart toen Hughes een vroege versie ontwikkelde van de eerste remailer ooit, gebaseerd op het mixnetwerkvoorstel van David Chaum. De eerste uitvoering van deze remailer zou emails accepteren, details die naar de afzender verwezen verwijderen en vervolgens doorsturen naar, of de volgende remailer, of naar de bedoelde ontvanger van de email. Deze uitvoering van Hughes omvatte echter nog geen encryptietools; het was nog altijd in ontwikkeling.

Gelukkig kreeg Hughes al snel hulp van een andere Cypherpunk. Hal Finney, een van de Extropianen die zich bij Tim May hadden aangesloten voor de Cypherpunk-bijeenkomsten, was net begonnen met het bijdragen aan de implementatie van Phil Zimmermann's PGP. Met zijn nieuw verworven kennis van publieke sleutel-cryptografie duurde het niet lang voordat Finney PGP integreerde in de remailer-code van Hughes.

Slechts enkele weken na de eerste samenkomst hadden de Cypherpunks al een volledig werkende remailer ontwikkeld. En die gingen ze ook zelf gebruiken. Finney en een aantal andere Cypherpunks namen het initiatief om de remailer-programma's uit te voeren, en ze verspreidden software en beginnershandleidingen zodat anderen zich bij hen konden aansluiten. Op deze manier werden remailers operationeel. Tegen het einde van 1992 kon iedereen met een computer en internetverbinding e-mails versturen zonder hun metadata te onthullen.

Zo rond diezelfde tijd was Zimmermann van plan om PGP 2.0 te lanceren. De bijdragen van Finney aan deze nieuwe versie hadden geleid tot aanzienlijke verbeteringen ten opzichte van de eerste versie, en de software beschikte nu over een *web-of-trust* systeem. Dit stelt gebruikers in staat om cryptografisch te garanderen dat een publieke sleutel werkelijk aan een bepaald persoon toebehoort.

Met de gloednieuwe remailer-software van Hughes en de verbeterde encryptietool van Zimmermann, gingen de Cypherpunks goed van start.

Maar het zou niet lang duren voordat ze in het defensief gedwongen werden...

## De crypto-oorlogen

Toen Bill Clinton in januari 1993 het ambt van de 42e President van de Verenigde Staten op zich nam, waren er door zijn nieuwe administratie snel zorgen geuit omtrent het mogelijk onheilspellende gebruik van persoonlijke computers en het internet. Ze kondigden aan dat wetshandhavingsinstanties nieuwe tools nodig zouden hebben om mee te kunnen gaan met het recente tempo van technologische vernieuwing.

Dit bleek een voorbode te zijn van de crypto-oorlogen van de jaren negentig: de Amerikaanse overheid zou proberen het gebruik van cryptografie te beperken.

De eerste klap viel toen Zimmermann het onderwerp werd van een strafrechtelijk onderzoek. In deze periode werden cryptografische protocollen die sleutels gebruikten die groter waren dan 40 bits in de Verenigde Staten geclassificeerd als munitie onder de definitie van de *Arms Export Control Act*. Het verzenden of meenemen van een sterk cryptosysteem naar het buitenland vereiste een vergunning, vergelijkbaar met de vergunning die nodig is voor internationaal vervoer van vuurwapens, munitie of explosieven.

Zimmermann bezat geen dergelijke licentie, maar hij verspreidde zijn gratis software wel via het internet. Omdat het internet geen landsgrenzen kent, insinueerde de overheid dat Zimmermann zijn software en de daarin opgenomen cryptoprotocollen illegaal geëxporteerd had.

En toen was er de Clipper-chip, een chipset ontwikkeld door de NSA en ondersteund door de regering Clinton. De Clipper-chip gebruikte cryptografie met openbare sleutels om data te versleutelen, maar de NSA had een speciale ontcijfersleutel toegevoegd aan het protocol. Het plan was dat telecombedrijven zoals AT&T de chipset zouden adopteren, zodat gebruikers hun telefoongesprekken konden versleutelen. De telecombedrijven zouden echter een ontcijfersleutel bewaren, die op verzoek aan de regering kon worden overhandigd. Dergelijke *sleutelbewaring* was noodzakelijk voor nationale veiligheidsredenen, stond de regering Clinton erop: de autoriteiten moesten in staat zijn om de telefoongesprekken van potentiële en verdachte terroristen te beluisteren.

De Clipper-chip werd tegengewerkt door voorstanders van privacy en belangenorganisaties voor burgerlijke vrijheden in het hele land, waaronder de Electronic Frontier Foundation (EFF), het Electronic Privacy Information Center (EPIC) en de American Civil Liberties Union (ACLU). Ook technologietijdschriften zoals *Wired*, cryptografie-startups zoals RSA van Ron Rivest, Adi Shamir en Leonard Adleman, en enkele politici (zowel Democraten als Republikeinen) voerden oppositie. Critici waren van mening dat de zogenaamde sleutelbewaring de kans vergrootte dat burgers onderworpen zouden worden aan verhoogde en mogelijk onwettige overheidssurveillance.

Uiteraard wezen de Cypherpunks de Clipper-chip ook af. De weerstand tegen de NSA-chip werd een van de eerste regelmatig terugkerende onderwerpen op de mailinglijst. Het was duidelijk dat het overhandigen van decryptiesleutels aan telecombedrijven (en, in verlengde daarvan, aan overheidsdiensten die de telecoms reguleren) deze cryptografische protocollen bijna nutteloos zou maken.

Voor de Cypherpunks betekende privacy in grote mate vrijheid van overheidsinmenging. Aalen zo konden ze een Orwelliaanse toekomst voorkomen. Uiteraard zou de crypto-anarchistische visie waarschijnlijk niet ver komen met hun eigen 'Galt's Gulch' in cyberspace als de cryptografische bouwstenen die hen beschermden tegen de staat poreus bleken te zijn.

Tegelijkertijd stelden de Cypherpunks dat het verplichten van het gebruik van gecompromitteerde of zwakke encryptieprotocollen de wereld in geen enkele zin betekenisvol veiliger zou maken. Kwaadwillende actoren zouden nog steeds degelijke encryptie kunnen gebruiken onder de zwakke laag van Clipper-chip encryptie om de inhoud van hun communicatie te verbergen. Dus zelfs als overheidsagenten hun toegewezen decryptiesleutel zouden gebruiken, zouden ze enkel meer versleutelde tekst tegenkomen.

Tim May was van mening dat de Cypherpunks een cruciale rol konden spelen in de naderende cryptografische conflicten. In tegenstelling tot gevestigde belangengroepen die beter georganiseerd, beter gefinancierd en beter in contact stonden met beleidsmakers en toezichthouders, zag May in het anarchistische organisatiemodel van de Cypherpunks juist een sterkte. Verspreid over de Verenigde Staten en daarbuiten, en zonder formeel leiderschap of organisatiestructuur, waren de Cypherpunks niet te coöpteren. Terwijl organisaties zoals EFF, EPIC en ACLU bereid waren tot zachtaardige onderhandelingen, weigerden de Cypherpunks elke vorm van gematigdheid te adopteren.

"Op een bepaalde manier vervullen de Cypherpunks een belangrijke ecologische niche door het voeren van de radicale, buitensporige oppositie... misschien een beetje zoals de rol die de Zwarte Panters, Yippies en Weather Underground een generatie geleden speelden", schreef May. [^155]

Inderdaad, het verzet van de Cypherpunks nam allerlei vormen aan: juist omdat ze geen formele organisatie hadden, handelden de Cypherpunks uiteindelijk uit eigen beweging. Sommigen van hen verspreidden flyers met informatie over de Clipper-chip in lokale winkelcentra. Anderen analyseerden hoe de chip werkte om te proberen fouten in het ontwerp te vinden. En natuurlijk was het schrijven van code de voornaamste strategie van de Cypherpunks.

"Potentiële inbreuk in de echte wereld zou het volledig verbieden van sterke crypto kunnen zijn, waarbij ciphers goedgekeurd moeten worden door de overheid", opperde May in zijn denken over verdere escalatie van de crypto-oorlogen. "Zo'n verbod zal een zwaar en verwoestend effect hebben op onze privacy, op ons vermogen om cyberspace-werelden op te bouwen die ik heb beschreven, en over het algemeen op computer-gemedieerde markten."

Hij concludeerde: "Ons onmiddellijke doel moet zijn om ervoor te zorgen dat de 'geest uit de fles is', dat voldoende crypto-tools en kennis wijdverspreid zijn zodat zo'n overheidsverbod zinloos wordt."[^156]

## Sucessen

De Cypherpunks waren gemotiveerd en gedreven, maar stonden tegenover de volle kracht van de Amerikaanse overheid. Weinigen hadden verwacht dat ze als overwinnaars uit de crypto-oorlogen zouden komen.

Toch boekten ze het ene succes na het andere.

Een van de meest opmerkelijke overwinningen kan worden toegeschreven aan Matt Blaze, een beveiligingsonderzoeker bij Bell Labs en een frequente deelnemer aan de Cypherpunks mailgroep. In 1994, deelde Blaze een pijnlijke klap uit aan de Clipper-chip door een paper te publiceren die een fout aantoonde in het ontwerp van de chip, die gebruikers toestond om de speciale decryptiesleutel uit te schakelen. Terwijl de reputatieschade van de Clipper-chip al groeide door de hevige tegenstand die het te verduren had, blijkt nu dat de Clipper-chip zelfs niet deed waarvoor hij verondersteld werd ontworpen te zijn.

Het was voldoende om telecombedrijven ervan te overtuigen de NSA technologie niet te adopteren. Het project zou geheel ter ziele gaan tegen 1996.

Zo wisten Cypherpunks Ian Goldberg en David Wagner in 1995 ook de gesloten broncode, en *export-grade* encryptiestandaard van Netscape te kraken. Dit deden ze in het kader van een wedstrijd, ontworpen door Hal Finney, en ze hadden hier slechts enkele uren voor nodig. Het schaadde het imago van een van de vooraanstaande bedrijven van Silicon Valley.

Als reactie op de inbreuk, beweerde Netscape dat ze wettelijk verhinderd waren om sterkere encryptiestandaarden aan te bieden in het buitenland. Hoewel dit maar een deel van het probleem was, bood het weinig geruststelling aan potentiële klanten buiten de VS. Het incident benadrukte ook een ander probleem als gevolg van de classificatie van encryptie als munitie: Amerikaanse technologiebedrijven liepen het risico marktaandeel te verliezen aan buitenlandse concurrenten.[^157]

Weer een andere Cypherpunk, Brad Huntting, kwam in 1994 met een slim idee om de exportrestricties op dergelijke crypto-protocollen uit te dagen: hij publiceerde code in fysieke vorm om aan te tonen dat verboden op software-distributies in strijd zijn met fundamentele rechten.

"Het recht op vrije meningsuiting wordt beschermd door de Amerikaanse grondwet. We hoeven alleen maar aan te tonen dat encryptiesoftware gelijk staat aan spraak", schreef hij aan de mailinglijst. "Dit zou niet te moeilijk moeten zijn (misschien een beetje pijnlijk, maar niet moeilijk). De daad zou een gepubliceerd werk moeten betreffen (bij voorkeur in de gedrukte zin)."[^158]

Ongeveer een jaar later publiceerde Zimmermann '*PGP: Broncode en Interne Werking*': hij had de volledige PGP-broncode in een boek afgedrukt. Zoals Huntting inderdaad had aangegeven, vallen boeken (inclusief de export ervan) in de VS onder de bescherming van het Eerste Amendement. Door dezelfde informatie die hem onderwerp van een strafrechtelijk onderzoek had gemaakt, vrij en legaal in harde kaft te verspreiden, legde Zimmermann de absurditeit van de regelgeving rondom crypto-export bloot.

Hoewel het nooit werd bevestigd dat het iets te maken had met de publicatie van zijn boek, liet de Amerikaanse overheid Zimmermann's zaak vroeg in 1996 vallen.

Bovendien zouden de exportverboden tegen het einde van dat jaar volledig worden opgeheven. Een combinatie van juridische uitdagingen, economisch schadelijke beperkingen op de Amerikaanse technologie-industrie, en de onomkeerbaar wijdverbreide verspreiding van crypto-protocollen buiten de Verenigde Staten bewoog de Clinton administratie om commerciële encryptie volledig van de Munitielijst te schrappen.

De Cypherpunks hadden dit niet alleen gedaan: de beweging om cryptografie tijdens de crypto-oorlogen te verdedigen was breder dan enkel zij. Maar, zij hadden onmiskenbaar een belangrijke rol gespeeld. Het losse collectief van hackers en cryptografen, verenigd door weinig meer dan een mailinglijst op het internet, was de strijd aangegaan met de Amerikaanse overheid, en had gewonnen.


[141]: More, "Hayek's Denationalisation of Money," 20.

[142]: Tim May, "Untraceable Digital Cash, Information Markets, and BlackNet ," The Computers Freedom & Privacy Conference , accessed via [https://web.archive.org/web/20130501134401/https://osaka.law.miami.edu/...oomkin/articles/tcmay.htm.]

[143]: Tim May, "The Cyphernomicon," originally distributed through the Cypherpunks mailing list, September 10, 1994, available via [https://nakamotoinstitute.org/static/docs/cyphernomicon.txt.]

[144]: Hal Finney, "Chaum on the wrong foot?" originally sent to the Cypherpunks mailing list, August 22, 1993 available via [https://cypherpunks.venona.com/date/1993/08/msg00652.html.]

[145]: Eric Hughes, "A Cypherpunk's Manifesto," originally sent to the Cypherpunks mailing list, March 17, 1993, available via [https://cypherpunks.venona.com/date/1993/03/msg00392.html.]

[146]: Tim May, "Degrees of Freedom," originally sent to the Cypherpunks mailing list, February 8, 1996, available via [https://cypherpunks.venona.com/date/1996/02/msg00637.html.]

[147]: Tim May, "'Who shall speak for us?'," originally sent to the Cypherpunks mailing list, Available via [https://cypherpunks.venona.com/date/1995/09/msg02189.html.]

[148]: The title and text was a bit of a parody of Karl Marx's and Friedrich Engels's Communist Manifesto, while the term crypto-anarchy is something of a pun referring to crypto-fascism, the secret support for fascism.

[149]: Tim May, "The Crypto Anarchist Manifesto," originally sent to the Cypherpunks mailing list, November 22, 1992, available via [https://cypherpunks.venona.com/date/1992/11/msg00204.html.]

[150]: Tim May, "Libertaria in Cyberspace," originally sent to the Cypherpunks mailing list, August 9, 1993, accessed via [https://cypherpunks.venona.com/date/1993/08/msg00168.html.]

[151]: Tim May, "Cyberspace, Crypto Anarchy, and Pushing Limits," originally sent to the Cypherpunks mailing list, April 3, 1994, accessed via [https://cypherpunks.venona.com/date/1994/04/msg00096.html.]

[152]: Tim May, "Hayek ," originally sent to the Cypherpunks mailing list, August 27, 1996, Accessed via [http://cypherpunks.venona.com/date/1996/08/msg02102.html.] As a funny aside, Tim May concluded a different email with a compliment to one of his fellow Cypherpunks: "I just want to end on a positive note before leaving for the holidays ." See: Tim May, "Re: The War on Some Money long," originally sent to the Cypherpunks mailing list, December 21, 1995, accessed via [https://cypherpunks.venona.com/date/1995/12/msg01044.html.]

[153]: Tim May, "'Stopping Crime' Necessarily Means Invasiveness," originally sent to the Cypherpunks mailing list, October 17, 1996, accessed via: [https://cypherpunks.venona.com/date/1996/10/msg01269.html.]

[154]: Eric Hughes, "No digital coins ," originally sent to the Cypherpunks mailing list, August 24, 1993, accessed via: [https://cypherpunks.venona.com/date/1993/08/msg00690.html.]

[155]: Tim May, "Crypto Activism and Respectability," originally sent to the Cypherpunks mailing list, April 21, 1993, accessed via: [https://cypherpunks.venona.com/date/1993/04/msg00400.html.]

[156]: Tim May, "Opportunities in Cyberspace," originally sent to the Cypherpunks mailing list, September 8, 1993, accessed via: [https://cypherpunks.venona.com/date/1993/09/msg00140.html.]

[157]: Michelle Quinn, "The Cypherpunks Who Cracked Netscape," San Francisco Chronicle, September 20, 1995, [https://people.eecs.berkeley.edu/...w/press/iang/ian1.html.]

[158]: Tim May, "Re: Stalling the crypto legislation for 2-3 more years," originally sent to the Cypherpunks mailing list, July 23, 1994, accessed via: [https://cypherpunks.venona.com/date/1994/07/msg01245.html.]