# B-geld (en BitTorrent)

Niet lang nadat Bit Gold had laten zien hoe proof-of-work in overdraagbaar elektronisch geld kon worden omgezet, werd er een enigszins vergelijkbaar voorstel voor digitale valuta ingediend bij de Cypherpunk mailinglijst. De auteur, Wei Dai, was een bekende naam binnen de Cypherpunk gemeenschap, maar dan alleen bij naam.

Inderdaad, privacy was het oprichtingsbeginsel van de Cypherpunks, maar het lukte weinigen om deze principes zo effectief uit te voeren als Wei Dai. Hoewel zijn betrokkenheid bij de Extropians het vermoeden wekte dat hij in de Bay Area woonde, verscheen Dai nooit bij de persoonlijke bijeenkomsten van de Cypherpunks. Gedurende enige tijd waren de leden van de mailinglijst niet eens zeker of ze correspondentie voerden met een man of een vrouw. Hun onzekerheid ging zo ver dat de Cypherpunks zich zelfs afvroegen of Dai wel echt bestond, speculerend dat de naam wellicht een pseudoniem was; sommigen vermoedden dat het eigenlijk een alter-ego van Nick Szabo was.

In werkelijkheid was Wei Dai, een hij, een jonge informaticus die toevallig enkele jaren jonger was dan Szabo aan de Universiteit van Washington, hoewel de twee elkaar nooit op de campus hebben ontmoet. Als liefhebber van cyberpunk boeken, had Dai als student een interesse ontwikkeld in cryptografie omdat hij geloofde dat het de mensheid kon helpen beschermen tegen toekomstige entiteiten zoals de Blight, een kunstmatige super-intelligentie die diende als de voornaamste antagonist in Vernor Vinge's roman 'A Fire Upon the Deep'.[^221]

Zijn interesse in cryptografie leidde Dai uiteindelijk naar de Cypherpunk mailinglijst, waar hij kennis maakte met de talrijke bijdragen van Tim May. Terwijl hij zich verdiepte in Mays visie op de toekomst van de samenleving, raakte de jonge informaticus nog meer gefascineerd door het transformatieve potentieel van cryptografie, nu met een sterke nadruk op privacy en vrijheid van overheidsinmenging.

Dai, wiens naam aangeeft dat hij van Chinese afkomst is, begon zich uiteindelijk te mengen in de gesprekken op de mailinglijst. In het midden van de jaren '90 betrok Dai zichzelf bij discussies over allerlei onderwerpen, variërend van de economie van digitale reputatiesystemen tot de toepassing van speltheorie op het gebied van cryptografie, voorstellen om traceerbare betalingssystemen om te zetten in anonieme, en nog veel meer.

Gedurende die tijd nam Dai de filosofie en missie van de Cypherpunks als zijn eigen aan.

"Er heeft nooit een regering bestaan die niet vroeg of laat probeerde de vrijheid van haar onderdanen te verminderen en meer controle over hen te verkrijgen, en waarschijnlijk zal er nooit een dergelijke regering zijn" vat Dai op een bepaald moment samen wat hij beschouwt als de bindende ethos van de beweging. "Daarom zullen we, in plaats van te proberen onze huidige regering te overtuigen om het niet te proberen, de technologie (bijvoorbeeld, remailers en elektronisch geld) ontwikkelen die het voor de regering onmogelijk zal maken om te slagen." [^222]

*Cypherpunks schrijven code.*

Ook Wei Dai ontwikkelde een aantal tools om de Cypherpunk-zaak te bevorderen. Dit bevatte een versleuteld tunneling-protocol (dat de overdracht van data van het ene netwerk naar het andere mogelijk maakte), een veilig systeem om bestanden te delen en de Crypto++ softwarebibliotheek (die vrij beschikbare cryptografische algoritmen bevat geschreven in de programmeertaal C++). Door zijn werk in codering en zijn doorgaans intelligente en inzichtelijke e-mails, verdiende Dai's bijdragen hem een reputatie als een van de meest productieve en waardevolle deelnemers aan de mailinglijst van de Cypherpunks, ondanks zijn meer ongrijpbare persoonlijkheid.

Hoewel het op het eerste gezicht vreemd kan lijken, is het niet zo ongelooflijk dat sommigen vermoeden dat Nick Szabo en Wei Dai eigenlijk dezelfde persoon zijn: de twee hadden veel gemeen. Naast het volgen van dezelfde universitaire studies en dat ze beiden deel uitmaakten van zowel de Cypherpunk als de Extropian gemeenschappen, hadden Szabo en Dai een bijzondere interesse in elektronisch geld, en om vele van dezelfde redenen. Ze wilden helpen om Tim May's "Galt's Gulch in cyberspace" te realiseren, en beiden begrepen het belang van digitale contracten in deze context.

In november 1998, net na zijn afstuderen aan de universiteit, kondigde Wei Dai informeel zijn eigen elektronisch geld aan. Dit voorstel werd bijna terloops aangekondigd in een mail waarin hij ook een geüpdatete versie van zijn anoniem communicatieprotocol, bekend als PipeNet, bekendmaakte. Het gebeurde slechts weken nadat Szabo voor het eerst zijn digitale munteenheid besprak op de Libtech mailinglijst. Dai, die ook actief was op deze lijst, had b-geld gecreëerd.

"Ik ben gefascineerd door Tim May's crypto-anarchie", legde Dai zijn motivatie uit in het voorstel. "In tegenstelling tot de gemeenschappen die traditioneel geassocieerd worden met het woord 'anarchie', wordt in een crypto-anarchie de regering niet tijdelijk vernietigd, maar permanent verboden en overbodig. Het is een gemeenschap waar de dreiging van geweld machteloos is omdat geweld onmogelijk is, en geweld onmogelijk is omdat de deelnemers niet in verband kunnen worden gebracht met hun daadwerkelijke namen of fysieke locaties."

Hij concludeerde:

"Het protocol dat in dit artikel wordt voorgesteld, maakt het voor ontraceerbare pseudonieme entiteiten mogelijk om efficiënter samen te werken, door hen te voorzien van een ruilmiddel en een manier om contracten af te dwingen. [...] Ik hoop dat dit een stap is in de richting van het praktisch mogelijk maken van crypto-anarchie, naast de theoretische mogelijkheid."[^224]

## B-geld

B-geld leek in belangrijke opzichten op Bit Gold, hoewel het op andere punten verschilde.

Net als Bit Gold, zou b-geld in principe bestaan op een grootboek (wat Szabo een "register" noemde). Dit grootboek zou publieke sleutels vermelden, en het aantal toegeschreven munteenheden aan elke publieke sleutel aangeven. Om het elektronische contant geld te verplaatsen, ondertekenden gebruikers cryptografisch een bericht dat aangeeft hoeveel munteenheden er worden uitgegeven van de bijbehorende publieke sleutel, en naar welke publieke sleutel ze werden uitgegeven. Als de transactie geldig was (de publieke sleutel had voldoende geld en de handtekening klopte), zou het grootboek dienovereenkomstig worden bijgewerkt.

Net zoals Szabo, legde Dai een sterke nadruk op het belang van contracten. B-geld was ontworpen om de uitvoering van contracten te vergemakkelijken, en een significant deel van het voorstel was gewijd aan het uitleggen van de taken van bemiddelaars in geschillenoplossing (hoewel het niet helemaal de autonome slimme contracten waren die Szabo oorspronkelijk in gedachten had, waren er enige cryptografische veiligheidsmaatregelen opgesteld om bepaalde vormen van fraude te voorkomen).

Szabo was er ook in geslaagd om Wei Dai ervan te overtuigen dat het minimaliseren van vertrouwen essentieel was. *Vertrouwde derde partijen zijn beveiligingsrisico's*, gaf Dai toe, en hij kwam tot de conclusie dat een elektronisch geldsysteem niet mocht staan of vallen met één enkele entiteit om de saldo's van gebruikers bij te houden, transacties mogelijk te maken of dubbele uitgaven te voorkomen.

In plaats daarvan bedacht Dai twee alternatieve oplossingen.

De eerste variant van b-geld was met name zeer ambitieus. In deze variant was er geen centrale instantie, maar onderhield *elke* gebruiker van het systeem zijn eigen exemplaar van het grootboek. Bij elke nieuwe b-geldtransactie zou iedere gebruiker afzonderlijk de geldigheid ervan controleren en hun eigen versie van het grootboek bijwerken als de transactie in orde bleek. Zolang iedereen actueel bleef, zouden de grootboeken gesynchroniseerd blijven onder alle gebruikers.

In theorie is het grote voordeel van zo'n gedistribueerd systeem dat corruptie onmogelijk zou zijn. Als iemand bijvoorbeeld te veel geld toeschrijft aan zijn eigen publieke sleutels, zou dit geen enkel effect hebben op iemand anders: alle andere grootboeken zouden onveranderd blijven. Als de bedrieger probeerde zijn vervalste geld uit te geven, zou niemand anders die transactie als geldig zien. Net zoals bij de tijdstempeloplossing van Scott Stornetta en Stuart Haber zou iedereen ervoor zorgen dat alle anderen eerlijk zou blijven.

Het leek een ideale oplossing om het grootboek over alle gebruikers te verspreiden --- in theorie.

Helaas wist Wei Dai dat het in de praktijk niet haalbaar zou zijn. Om dubbele uitgaven te voorkomen, vereiste het systeem een "synchroon en onverstoorbaar anoniem uitzendkanaal".[^225] Alleen als alle gebruikers zeker konden zijn dat zij allemaal dezelfde transacties in precies dezelfde volgorde ontvingen, kon iedereen er vertrouwen in hebben dat hun grootboeken gesynchroniseerd waren en dat een betaling die zij zouden ontvangen ook door alle anderen zou worden geregistreerd. Dit leek onwerkbaar: dubbele uitgavetransacties konden tegelijkertijd naar verschillende delen van het netwerk worden gestuurd, terwijl onbetrouwbare deelnemers eenvoudigweg konden liegen over de volgorde van de transacties die ze hadden ontvangen.

O in technische termen: Wei Dai's eerste oplossing negeerde het Byzantijnse Generaalsprobleem.

Dit is waarom Dai in hetzelfde voorstel met een tweede oplossing kwam.

In deze tweede versie van het b-geld systeem, zou niet iedereen een versie van het hoofdregister bijhouden, maar zou het systeem bestaan uit twee soorten deelnemers: reguliere gebruikers en "servers". Net zoals de "eigendomsclub" in Szabo's Bit Gold voorstel, zouden alleen deze servers de b-geld hoofdregisters bijhouden. Om er zeker van te zijn dat een transactie werd voltooid, moesten reguliere gebruikers checken bij een willekeurige subset van servers, en een betaling pas als finaal beschouwen als die servers de transactie erkenden.

Dit introduceerde natuurlijk wel weer wat vertrouwde partijen in het systeem. De servers konden samenwerken om overdrachten te blokkeren, transacties dubbel uit te geven, mogelijk fondsen te stelen of zelfs regelrecht geld voor zichzelf te creëren.

Wei Dai stelde daarom een manier voor om de servers eerlijk te houden.

"Hij stelde voor dat elke server verplicht is om een bepaald bedrag op een speciale rekening te storten, die zou worden gebruikt als potentiële boetes of beloningen voor bewijzen van wangedrag", stelde hij voor. "Ook moet elke server periodiek zijn huidige database van geldcreatie en geldbezit publiceren en zich daaraan binden. Elke deelnemer moet controleren of zijn eigen rekeningsaldi kloppen en dat de som van de rekeningsaldi niet groter is dan het totale bedrag aan gecreëerd geld."

Echter, het b-geld voorstel ging niet in detail in op een van deze oplossingen. Wellicht het meest problematisch was dat Dai niet uitlegde wie zou bepalen of er wangedrag plaatsvond, als dit niet werd bepaald door de (samenzwerende) servers zelf, of hoe de boetes konden worden afgedwongen. Net zoals Bit Gold geen oplossing had geboden om conflicten tussen servers te beslechten, had b-geld dat ook niet gedaan.

## Monetaire beleid van b-geld

Net als Bit Gold zou b-geld een zuiver digitale munteenheid zijn. Er zou geen bank of bedrijf zijn die de digitale eenheden dekte met dollars of goud, en geen garantie dat iemand de munteenheid zou accepteren voor betaling.

Maar net zoals Szabo, dacht Dai niet dat dit een probleem zou zijn.

"Denk er op deze manier over na", betoogde hij op de mailinglijst van de Cypherpunks. "In het geval van goederengeld, wordt de waarde deels bepaald door de industriële/esthetische waarde van het goed en deels door het nut van het goederengeld als ruilmiddel. In het geval van fiatgeld en b-geld, komt alle waarde voort uit zijn nut als ruilmiddel."[^226]

In tegenstelling tot Szabo, wilde Dai zijn valuta echter voorzien van een gericht monetair beleid. Waar de koopkracht van Bit Gold overgelaten werd aan de markt, met geldige proof-of-work hashes die vrij verhandeld worden voor wat kopers en verkopers bereid zijn te accepteren, was b-geld specifiek ontworpen om een voorspelbare koopkracht te bieden.

Net als Irving Fisher en de Vereniging voor Stabiel Geld ongeveer 80 jaar eerder, stelde Dai voor om de koopkracht van zijn munteenheid te koppelen aan een consumentenprijsindex. Hij wilde dat dezelfde hoeveelheid b-geld-eenheden op elk moment een gelijk aandeel van deze index kon kopen. Met andere woorden, de gemiddelde prijs van goederen en diensten, uitgedrukt in b-geld, moest stabiel blijven.

Als we het breder bekijken, zou het creëren van valuta in b-geld vergelijkbaar werken met Bit Gold: iedereen zou nieuwe valuta-eenheden kunnen genereren door middel van een proof-of-work door een geldige hash te produceren, vermoedelijk ook gebaseerd op een bepaalde kandidaat-string. Wie de hash creëerde, mocht deze houden (of misschien zouden ze een equivalent in b-geld-eenheden krijgen; een geldig proof-of-work zou heel goed op de grootboek kunnen worden weerspiegeld als 100 digitale "munten".).

Het belangrijkste verschil met Bit Gold, was echter dat de moeilijkheidsgraad om een geldig proof-of-work te genereren, kon veranderen.

Alle gebruikers van het systeem (b-geld versie 1) of de servers (b-geld versie 2) zouden voortdurend moeten bepalen hoeveel een mandje goederen zou kosten in verhouding tot de productie van een geldige hash. Dat wil zeggen, als het creëren van een hash goedkoper wordt (door verbeteringen in computerhardware) in verhouding tot de prijsindex, dan zou de moeilijkheidsgraad om een geldige hash te produceren naar boven moeten worden bijgesteld: de hash zou met meer nullen moeten beginnen. Een nieuwe hash zou dan alleen aan het grootboek worden toegevoegd als aan de meest recente drempelwaarde was voldaan.

Wei Dai vermeldde in de bijlage van zijn voorstel ook een alternatieve benadering om een vergelijkbaar resultaat te bereiken. Het aanmaken van geld kon gebeuren via een veiling. In dit geval zouden alle gebruikers (b-geld versie 1) of de servers (b-geld versie 2) eerst de optimale uitbreiding van de geldvoorraad bepalen, waarna deze nieuwe eenheden b-geld geveild zouden worden aan degene die bereid en in staat was om het met het meeste proof-of-work te betalen.

Een grote voordeel van deze benaderingen was dat alle b-geld hashes, ongeacht wanneer ze werden gecreëerd, dezelfde waarde moesten hebben: ze zouden fungibel zijn. Dit elimineerde de noodzaak om een hele andere bankenlaag te ontwerpen bovenop de basislaag van de valuta, zoals Szabo had voorgesteld voor Bit Gold.

Het was een innovatieve aanpak, maar opnieuw bleef er veel ongespecificeerd. Zowel voor de aanpassingsmethode van de moeilijkheidsgraad als het veilingmodel, bleef het in het voorstel van b-geld onduidelijk hoe gebruikers (of servers) zouden beslissen over de volgende moeilijkheidsgraad voor proof-of-work, of de optimale toename van de geldvoorraad... en hoe geschillen in dit deel van het proces zouden kunnen worden opgelost (het Byzantijnse Generaalsprobleem bleef de kop opsteken).

"B-geld was nog geen volledig ontwerp om in de praktijk te brengen", erkende Dai later.[^227] Het voorstel bood een ruwe schets van hoe een elektronisch geldsysteem eruit kon zien, maar er waren nog meerdere problemen die moesten worden opgelost voordat het als een daadwerkelijke digitale valuta zou kunnen functioneren.

Dai zelf besloot echter dat hij niet degene zou zijn die deze problemen zou oplossen.

## Ontgoocheling

In zijn voorstel voor b-geld leek Wei Dai nog altijd optimistisch over de mogelijkheden en het potentieel van Tim May's crypto-anarchistische visie. Maar in werkelijkheid was de ongrijpbare informaticus de droom van de Cypherpunks aan het opgeven.

"Ik ben niet verder gegaan met het ontwerpen omdat ik, tegen de tijd dat ik klaar was met het opschrijven van b-geld, eigenlijk al wat gedesillusioneerd was geraakt door crypto-anarchie", herinnerde Dai zich later. "Ik had niet voorzien dat zo'n systeem, eenmaal geïmplementeerd, zoveel aandacht en gebruik zou aantrekken buiten een kleine groep van *hardcore* cypherpunks."[^228]

Dai's ontgoocheling weerspiegelde een groeiend sentiment binnen de Cypherpunk-gemeenschap tegen het einde van de jaren 90. Het internet was inmiddels echt mainstream geworden, maar de Cypherpunks ontdekten dat het grote publiek nogal onverschillig was over online privacy. Het leek erop dat de meeste mensen er geen probleem mee waren om betalingsverwerkers volledig inzicht te geven in hun uitgavenpatroon, en ze leken er ook geen probleem mee te hebben om een ​​spoor van hun andere online activiteiten achter te laten. De gemiddelde internetgebruiker dacht zelfs niet eens aan het versleutelen van hun e-mails.

Sinds de Cypherpunks voor het eerst bijeen kwamen in het ongemeubileerde appartement van Eric Hughes, hadden ze bijna tien jaar besteed aan het transformeren van revolutionaire crypto-protocollen in werkende software. Tot hun grote teleurstelling bleek dat bijna niemand hierin geïnteresseerd was. Het doorzettingsvermogen in hun activisme voor privacy had hen weliswaar geholpen de crypto-oorlogen te winnen, maar dit leek nu een tamelijk nutteloze inspanning te zijn geweest. De meeste internetgebruikers bleken namelijk perfect op hun gemak met het opgeven van zowat al hun persoonlijke informatie in ruil voor iets meer gemak.

Hughes had zich inmiddels vrijwel volledig teruggetrokken uit de gemeenschap en de mailinglijst. Maar niet voordat hij zijn nuchtere herbeoordeling van de "cypherpunks schrijven code"-filosofie had aangeboden, kenmerkend voor de recente desillusie van Wei Dai, hemzelf en andere Cypherpunks.

"Misschien het belangrijkste wat ik van de cypherpunks heb geleerd is dat alleen code niet voldoende is. Niet alleen code, niet wijdverspreide code, zelfs niet veelgebruikte code", schreef Hughes zich richtend tot de Cypherpunk mailinglijst. "Voor langdurig succes is een zekere mate van tolerantie in de samenleving nodig voor activiteiten die in privé worden ondernomen. Niet alleen gemakkelijk of makkelijker, maar noodzakelijk."[^229]

Hughes was tot het inzicht gekomen dat het essentieel was dat het grote publiek zou begrijpen waarom privacy belangrijk was. Code was uiteraard ook nog steeds nodig --- code maakte privacy in eerste instantie mogelijk. Maar hij geloofde nu dat code uiteindelijk alleen maar nuttig was als er een brede publieke consensus bestond dat mensen daadwerkelijk het recht zouden moeten hebben om hun privacy te beschermen. Zonder zo'n publieke consensus zou het gebruik van cryptografie kunnen worden gemarginaliseerd en wellicht zelfs verboden, met als risico dat de overblijvende gebruikers mogelijk zouden worden geviseerd en vervolgd.

"Hetzelfde geldt voor anonieme transacties", schreef Hughes. "Tenzij er een soortgelijke consensus bestaat, zullen we weer te maken krijgen met een marginale activiteit. Ik beschouw dit als een verlies."[^230]

Het optimisme en de assertiviteit die de beweging in de begindagen kenmerkten, werden steeds meer overschaduwd door een gevoel van somberheid en verlatenheid.

In plaats daarvan kwamen sommige van de meer hoopvolle impulsen voor de Cypherpunk-missie in de late jaren '90 van relatieve buitenstaanders van de gemeenschap.

## Zero-Knowledge Systems

De Canadese broers Austin en Hamnett Hill waren nog maar halverwege de twintig toen ze TotalNet, de internetprovider die ze hadden opgericht en die de derde grootste van hun land werd, verkochten. Met wat geld in hun zak en de tijd om het uit te geven, zochten de twee naar hun volgende project toen ze op de Cypherpunk-mailinglijst stuitten. Ze raakten volledig in de ban van het techno-libertarische ethos van de beweging.

In 1997 besloten de twee broers, samen met hun vader Hammie Hill, om hun middelen, connecties, en zakelijke talenten in te zetten, en richtten ze *Zero-Knowledge Systems* op. Het nieuwe bedrijf nam zich voor om de visie van de Cypherpunks werkelijkheid te laten worden, en om er tegelijkertijd ook wat geld mee te verdienen.

De kernactiviteit van de startup was een privacy-netwerk dat ze *Freedom* noemden. Freedom was gebaseerd op Wei Dai's PipeNet, het anonieme communicatieprotocol waarvan een bijgewerkte versie zou worden aangekondigd in dezelfde Cypherpunks-mailinglijstpost die b-geld introduceerde. Net als PipeNet, werden in Freedom's verhullingstechnieken een geavanceerdere variant van David Chaum's originele remailer-protocol ingebed, maar waar remailers alleen e-mails anonimiseerden, paste Freedom de mix-technologie toe om alle soorten internetgegevens te verhullen: e-mails, surfen, tekst-chat en meer.

Gebruikers van Freedom konden in wezen op het internet "inloggen" onder verschillende identiteiten: misschien een reguliere identiteit voor professioneel werk, een pseudonieme identiteit voor politieke betrokkenheid, en nog een pseudoniem voor seksueel getinte webactiviteiten. Niemand, zelfs Zero-Knowledge Systems niet, zou in staat zijn de pseudonieme online identiteiten te koppelen aan een echte identiteit, of aan andere pseudoniemen.

De start-up wekte behoorlijk wat interesse op binnen de Cypherpunk-gemeenschap en, belangrijker nog, de oprichters van Zero-Knowledge Systems wisten de durfkapitalisten uit te leggen waarom ze de kans niet mochten missen om te investeren in *de toekomst van privacy*. Binnen een paar jaar slaagde de start-up erin om tientallen miljoenen dollars op te halen.

Waarschijnlijk konden de Hills beter verkopen dan de meeste Cypherpunks. Ze wisten ook op een goede manier de ambitieuze doelen van Zero-Knowledge Systems aan het grote publiek te presenteren. Er verschenen aantrekkelijke printadvertenties in bekende tijdschriften zoals *Wired, Forbes en Fortune*, met teksten als "Ik ben geen stuk van je inventaris", "Ik ben een individu en je zult mijn privacy respecteren" en "Op het net heb ik de controle". Bijzonder scherpe lezers konden ook een verborgen boodschap ontrafelen uit een binaire code op de pagina's, die zich vertaalde naar "Wie is John Galt?" --- een beroemde zin uit Ayn Rand's *Atlas Shrugged*.

En wellicht nog het belangrijkst van alles, Zero-Knowledge Systems wist het beste talent in de privacy-sector aan te trekken. Enkele van de bekendste cryptografen en computerwetenschappers op de Cypherpunk-mailinglijst besloten zich bij de start-up te voegen, waaronder Ian Goldberg -- die tijdens de crypto-oorlogen het SSL crypto-protocol van Netscape had gebroken en het bedrijf als 'Hoofdwetenschapper en Hoofd Cypherpunk' zou dienen -- en Adam Back. Stefan Brands, de uitvinder van Brands Cash, werd ook aangenomen en zijn patenten op elektronisch geld werden eveneens door de start-up gekocht.

De Hills waren zeker niet kort van ambitie. Freedom was het hoofdproject van het bedrijf, maar Zero-Knowledge Systems wilde uiteindelijk de idealen van Cypherpunks breed realiseren. Het onderzoeks- en ontwikkelingsteam van de start-up, ook wel de "Kwaadaardige Genieën" genoemd, kreeg de taak om aanvullende producten te ontwerpen. Dit omvatte onder andere een elektronisch geldsysteem gebaseerd op het ontwerp van Brands, met de codenaam Zorkmid (een verwijzing naar de munteenheid van een vroeg online spel).

Oondanks alles, leek één probleem echter aan te houden. De meeste internetgebruikers gaven gewoon niet veel om privacy.

Zero Knowledge Systems had het plan om tegen 2000 zo'n 2,5 miljoen gebruikers van Freedom aan te kunnen. Maar hoewel de 250 medewerkers zich flink hebben ingezet om dit mogelijk te maken, waren er rond de eeuwwisseling slechts iets meer dan twaalfduizend actieve gebruikers op het netwerk, of minder dan een procent van het oorspronkelijke doel.

Deels kwam dit doordat veel mensen moeite hadden met het installeren van de software, maar zelfs degenen die erin slaagden Freedom operationeel te krijgen, ontdekten dat hun internetsnelheid aanzienlijk afnam bij het gebruik van de service. Buiten een relatief technisch onderlegde kern van gebruikers (voornamelijk mannen tussen de 25 en 35 jaar) waren weinig mensen bereid dit voor lief te nemen, en daarnaast nog de jaarlijkse vergoeding van € 50 aan Zero-Knowledge Systems te betalen. Aan het einde van de rit zagen mensen gewoonweg geen reden om Freedom te gebruiken: de voordelen voor de privacy waren voor hen onzichtbaar.

"Of in de woorden van Austin Hill, een paar jaar later: "Iedereen beweert te geven om privacy, maar men zou zo een DNA-staal afstaan voor een 'gratis' Big Mac."[^231]"

Om het bedrijf te redden, heeft Zero Knowledge Systems uiteindelijk haar strategie veranderd. In plaats van op de algemene internetgebruiker te focussen, zou de startup vanaf 2001 haar inspanningen richten op gevestigde bedrijven, zoals financiële instellingen en telecombedrijven. Ze boden hen beveiligde database- en communicatiesystemen aan. Tot grote ontsteltenis van zijn kleine, maar toegewijde gebruikersbasis werd Freedom stopgezet.

Hiermee liet de startup het Cypherpunk-ethos grotendeels achter zich, en personen zoals Back en Brands vertrokken kort daarna. Toen het bedrijf uiteindelijk zijn naam veranderde in Radialpoint, was Zero Knowledge Systems in alle opzichten vervangen door een totaal ander IT-bedrijf.

Ondanks een hoopvol begin, was dit een nieuwe tegenslag voor het doel van de Cypherpunks.

## Mojo Nation

Een andere positieve impuls kwam van twee tot dusver onbekende tieners die een compleet ander deel van de cyberspace ontregelden: Met de lancering van Napster in 1999 gooiden Shawn Fanning en Sean Parker, achttien en negentien jaar oud respectievelijk, de digitale variant van een handgranaat recht in het hart van de muziekindustrie.

Napster was een krachtig idee om één specifieke, technische reden. In tegenstelling tot de meeste internetdiensten tot dat moment, die vertrouwden op een centrale server om gebruikers te voorzien van wat ze nodig hadden, was Napster ontworpen als een *peer-to-peer* (P2P) netwerk. De peers (Napster-gebruikers) op het Napster-netwerk fungeerden als gelijken, ze hielpen elkaar waar nodig: specifieker, ze deelden hun eigen muziekbestanden met elkaar. Omdat Napster zelf geen muziekbestanden verspreidde, dachten Fanning en Parker dat ze claims wegens inbreuk op auteursrechten konden omzeilen, terwijl gebruikers nog steeds gratis nummers konden downloaden.

Maar toen de populariteit van Napster ontplofte, lanceerde de muziekindustrie een succesvolle tegenaanval. Fanning en Parker deelden misschien zelf geen muziek, maar artiesten en platenmaatschappijen beweerden dat de service desondanks actief inbreuk maakte op het auteursrecht: Napster bood gebruikers een platform, het beheerde en bewaarde de indexen om alle muziekbestanden te vinden, en de service koppelde peers dienovereenkomstig. Al snel bezweken Fanning en Parker onder de enorme juridische druk, en in juli 2001 haalden ze Napster offline.

Uiteindelijk was Napster een kortstondig project. Maar in een paar jaar tijd populariseerden ze de P2P-technologie, die een hele nieuwe klasse van vernieuwers inspireerden. Alternatieve diensten om bestanden te delen zoals Kazaa en eDonkey doken al snel op, elk van hen ontworpen om nog decentraler te zijn dan de creatie van Fanning en Parker. Gedurende de volgende paar jaar waren de makers van deze nieuwe protocollen betrokken bij een hoogtechnologisch kat-en-muis-spel met de platenlabels die probeerden hun projecten lam te leggen.[^232]

De eenendertigjarige Cypherpunk, Jim McCoy, besloot dat hij ook wilde meespelen. Begin 2000 nam hij ontslag bij Yahoo -- "Ik werd het zat om niets revolutionairs te doen"[^233] -- en samen met verschillende andere Cypherpunks, waaronder DigiCash-alumnus Bryce "Zooko" Wilcox, richtte McCoy Autonomous Zone Industries op.

De naam van het bedrijf was geïnspireerd op "tijdelijke autonome zones", een term die voor het eerst werd gebruikt in 1991 door anarchist Hakim Bey om niet-permanente, lokale samenlevingen te beschrijven die vrij zijn van de overheid. De startup zou een ambitieus open-source softwareproject genaamd Mojo Nation ontwikkelen. Net als Napster was Mojo Nation in essentie een P2P *file sharing system*. Maar McCoy, als ervaren Cypherpunk, had een paar extra tools in zijn crypto-gereedschapskist om het ontwerp van Fanning en Parker te verbeteren.

Een van Mojo Nation's meest interessante innovaties was dat alle bestanden op het netwerk in kleine stukjes werden opgedeeld, gecodeerd en strategisch gekopieerd en verspreid over het netwerk. Als iemand een bestand ging downloaden, downloadden ze in feite al deze kleine gecodeerde stukjes van verschillende gebruikers over het netwerk, om uiteindelijk deze puzzelstukjes bij elkaar te brengen en in één keer het volledige bestand te decoderen. Omdat alle uploaders slechts een beetje bandbreedte nodig hadden om hun stukje te delen, kon de downloadsnelheid worden verhoogd. Dit stelde Mojo Nation-gebruikers in staat om grotere bestanden te delen dan de typische MP3's. Bovendien bood het meer privacy: gebruikers die de gecodeerde stukjes deelden, wisten vaak niet wat voor soort inhoud ze deelden (of deze inhoud al dan niet auteursrechtelijk beschermd was).

Daarnaast werden sommige taken die Napster nog steeds als een centrale coördinator uitvoerde, in Mojo Nation overgedragen aan de gebruikers. Gebruikers die als contenttrackers fungeerden zouden bijvoorbeeld de indexen van bestanden die op het netwerk werden gehost bijhouden, terwijl andere gebruikers, die als zoekagenten fungeerde, zoekopdrachten via deze indexen zouden aanbieden. Door dergelijke verantwoordelijkheden in de handen van gebruikers te leggen, geloofde McCoy dat Mojo Nation niet vatbaar zou zijn voor het soort rechtszaken waarmee Napster te maken had gehad. In plaats daarvan zouden de gebruikers zelf verantwoordelijk zijn als ze wetten van hun jurisdictie overtraden --- maar al deze individuele mensen waren natuurlijk veel moeilijker te vinden dan Fanning en Parker.

Wat dit alles liet draaien was wellicht het meest interessante element van Mojo Nation: een digitale valuta genaamd *Mojo*.

## Mojo

Mojo is ontworpen als een ongedekte digitale valuta die eigenlijk alleen nuttig was binnen de context van het bestandsuitwisselingsnetwerk.

Specifiek had Mojo de taak om een markt voor bestandsdeling en andere taken mogelijk te maken. Waar Napster-gebruikers hun eigen bestanden gratis deelden, konden Mojo Nation-gebruikers elkaar betalen voor de service, en de prijzen zouden worden bepaald door vraag en aanbod. Iemand zou bijvoorbeeld kunnen aanbieden om 1.000 Mojo te betalen voor elk gecodeerd deel van een bestand dat weer in elkaar gezet kan worden als een DVD-rip van *The Matrix*: wie een of meerdere van deze gecodeerde delen had, kon het aanbod accepteren als ze dachten dat het hun tijd, moeite en bandbreedte waard zou zijn om ze te uploaden. De verdiende Mojo's konden vervolgens worden gebruikt om andere diensten op het netwerk te kopen, of misschien in te ruilen voor dollars op een speciale Mojo-handelsbeurs.[^234]

"De mensen die betaald krijgen, zijn degenen die de diensten uitvoeren. Dus die agenten die je hebben geholpen om dat blok [bestand] te vinden, worden betaald", legde McCoy uit. "De verspreide zoekagenten krijgen betaald. Alle verschillende blokservers waar je blokken van hebt gekocht krijgen betaald, en als de gebruiker via een *relay-server* werkte, hetzij omdat ze achter een firewall zaten of omdat ze hun privacy wilden beschermen, zou de persoon die berichten doorgaf ook een deel van de betaling ontvangen."[^235]

McCoy's visie was dat heel Mojo Nation zou worden gestuurd door marktprocessen, waarbij de ene gebruiker's probleem de volgende gebruiker's gelegenheid was om wat geld te verdienen door het op te lossen. Dit zou het Mojo Nation-netwerk quasi-autonoom laten functioneren, hoopte de Cypherpunk, met zeer weinig dagelijkse betrokkenheid van Autonomous Zone Industries.

Een opvallende uitzondering op deze regel bestond echter wel. De munteenheid van Mojo Nation werd beheerd door Autonomous Zone Industries *zelf*, via een speciale tokenserver die de rekeningsaldi bijhield en dubbele uitgaven voorkwam. Bovendien functioneerde de server als een gecentraliseerde muntfabriek: het kon nieuwe Mojo uitgeven wanneer McCoy en zijn collega's geloofden dat dit nodig was, zonder technische beperking op hoeveel ervan gecreëerd kon worden.

Het resulteerde uiteindelijk in de vernietiging van de munteenheid. Toen sommige gebruikers slimmigheidjes ontdekten om anderen te bedriegen om hun munten naar hen te sturen, besloot het team van Mojo Nation de slachtoffers te compenseren met nieuw geld. Dit leidde uiteindelijk tot de uitgifte van zoveel Mojo dat het uiteindelijk resulteerde in hyperinflatie. Mojo was afhankelijk geweest van een vertrouwde derde partij -- de muntfabriek -- en dat vertrouwen was geschonden.

Om iets als Mojo Nation echt te laten werken, had het waarschijnlijk een onafhankelijke digitale munteenheid nodig.

" [...] we bestudeerden MojoNation kritisch, omdat ons hoofddoel een werkende gemeenschapsmunt voor p2p-diensten was, en tot op zekere hoogte nog steeds is", schreef informaticus Daniel A. Nagy kort na het einde van Mojo Nation aan Jim McCoy. "Als reden voor het falen, wezen we hyperinflatie aan. MN had geen inflatiebeperkende maatregelen en op den duur leidde dit ertoe dat de Mojo geheel werd geïnflateerd." Hij voegde eraan toe dat "Ik geloof in de visie dat de wereld dringend behoefte heeft aan een p2p-cashsysteem. Zonder zo'n systeem zal e-commerce een grote PITA blijven." [^236]

Dat gezegd zijnde, was het vertrouwen op een gecentraliseerd digitaal valutasysteem niet het enige probleem waarmee Mojo Nation te kampen had. Hoewel de software door meer dan 100.000 mensen werd gedownload en gebruikt,[^237] bleken meerdere onderdelen van het systeem erg moeilijk om draaiende te krijgen (en te houden). Met problemen variërend van netwerkinstabiliteit tot ontbrekende bestandsfracties en een gebrek aan vertrouwen tussen gebruikers,[^238] was de dienst waarschijnlijk te ambitieus voor het bescheiden budget van Autonomous Zone Industries: het bedrijf zat binnen een paar jaar door zijn geld heen en de negatieve publiciteit rond Napster maakte het moeilijk om meer financiering te verkrijgen.

In 2002 zag McCoy zich gedwongen om de meeste werknemers te ontslaan.

## BitTorrent

Hoewel Mojo Nation ten onder ging, waren er enkele ontwikkelaars bij de startup die hun vooruitstrevende technologieën niet wilden laten vergaan. Zo besloot Wilcox bijvoorbeeld de code van Mojo Nation te kopiëren (forken) om een versie van het protocol genaamd Mnet uit te brengen. Daarnaast bracht ook een andere medewerker van Autonomous Zone Industries, de 28-jarige softwareontwikkelaar en Cypherpunk Bram Cohen, zijn eigen op Mojo Nation geïnspireerde bestandsuitwisselingsnetwerk uit.

Hij noemde het: BitTorrent.

Cohen had Mojo Nation in feite tot op de bot gestript. BitTorrent nam sommige van McCoy's ideeën over, zoals het opdelen van bestanden in kleinere fracties. Maar verder was het protocol vrij eenvoudig: er waren geen ingebouwde contenttrackers (indexen, torrent-bestanden genoemd, werden buiten het protocol onderhouden en verspreid), er waren geen zoekagenten (gewone websites, opnieuw buiten het protocol, konden gebruikers helpen specifieke torrent-bestanden te vinden), en er was geen eigen valuta.

BitTorrent had geen eigen munteenheid nodig, omdat niemand hoefde te betalen voor bestanden. In plaats daarvan uploaden gebruikers, die de verschillende delen van een bestand downloaden, deze delen gelijktijdig naar andere downloaders. Dit betekende dat bestanden technisch gezien altruïstisch gedeeld werden, maar op zo'n manier dat de last op hulpbronnen voornamelijk werd gedragen door degenen die ook profiteerden van de bestandsoverdrachten.

En zo had Cohen een echt peer-to-peer en volledig gedistribueerd bestandsoverdrachtprotocol ontworpen. Waar Napster's P2P-netwerk effectief kon worden uitgeschakeld door juridische druk uit te oefenen op het bedrijf erachter en zelfs het veel ambitieuzere Mojo Nation niet kon functioneren zonder dat de Autonomous Zone Industries een valutasysteem voor het netwerk onderhield, was BitTorrent niet van enige betrouwbare derde partij afhankelijk.

Vanuit een juridisch oogpunt waren gebruikers nu voor het eerst volledig verantwoordelijk voor hun eigen file sharing activiteiten. Net als e-mail (SMTP) of zelfs het internet zelf (IP), was BitTorrent in wezen slechts een internetprotocol. Bram Cohen was op geen enkele wijze aansprakelijk voor hoe mensen het protocol gebruikten, zelfs al werd er op grootschalige wijze illegaal auteursrechtelijk beschermde bestanden uitgewisseld via BitTorrent.

Bovendien, als Cohen om welke reden dan ook legale druk zou ondervinden, zouden noch hijzelf, noch het later door hem opgerichte BitTorrent-bedrijf op technisch niveau controle over het BitTorrent-netwerk kunnen uitoefenen. Hoewel Cohen de software initieel creëerde, werd deze bediend door mensen over de hele wereld. Het netwerk werd al snel bijna onmogelijk om te censureren en zo goed als onstopbaar --- zelfs de maker kon dit niet veranderen.

BitTorrent zou zich in de volgende jaren vestigen als de standaard voor bestandsoverdrachten. Ongeveer een decennium na Cohen's eerste software-release, in het begin van de jaren 2010, had het protocol op elk moment van de dag minstens vijftien miljoen gelijktijdige gebruikers,[^239] en in een typische maand waren er wereldwijd zo'n 150 miljoen mensen verbonden met het netwerk.[^240] Alles bij elkaar opgeteld, werd geschat dat BitTorrent-gebruikers verantwoordelijk waren voor zo'n 25 tot 30 procent van al het internetverkeer in de wereld, wat meer was dan enig ander protocol in die tijd.[^241]

Zonder een centrale entiteit die ze nog konden aanklagen, hadden muziekartiesten en platenmaatschappijen weinig andere keuze dan zich ook aanpassen aan de nieuwe realiteit. In plaats van te proberen hun muziek van het internet te verwijderen, verschoven ze uiteindelijk hun inspanningen om te concurreren met diensten om bestanden te delen door hun nummers gemakkelijk beschikbaar te maken via handige softwaretoepassingen (zoals Apple's iTunes) en later, streamingdiensten. Slechts een paar jaar na de introductie van BitTorrent zou het kopen van een fysieke cd (of zelfs het bezit van muziek in het algemeen) ouderwets lijken.

Misschien had deze kennis de doorgewinterde Cypherpunks aan het einde van de jaren 1990 enige hoop kunnen bieden. Een van "hun" technologieën zou niet alleen de wereld veroveren, maar, nog relevanter: Cohen's code revolutioneerde hoe mensen het internet gebruikten en ernaar keken. Dit dwong uiteindelijk een volledige transformatie van de entertainmentindustrie af.

Waar Wei Dai, Eric Hughes, en andere Cypherpunks dachten dat elektronisch geld en andere crypto-tools alleen succesvol zouden zijn als het publieke bewustzijn over het belang van online privacy toenam, zou BitTorrent jaren later aantonen dat het ook andersom kon werken: een krachtige genoeg technologie kon, op zichzelf, helpen de heersende cultuur te veranderen.


[221]: Wei Dai, "Work on Security Instead of Friendliness?" GreaterWrong, July 21, 2012, [https://www.greaterwrong.com/posts/m8FjhuELdg7iv6boW/work-on-security-instead-of-friendliness.]

[222]: Wei Dai, "Law vs Technology," originally sent to the Cypherpunks mailing list, February 10, 1995, accessed via: [https://cypherpunks.venona.com/date/1995/02/msg00508.html.]

[223]: Wei Dai, "PipeNet 1.1 and b-money," originally sent to the Cypherpunks mailing list, November 26, 1998, accessed via: [https://cypherpunks.venona.com/date/1998/11/msg00941.html.]

[224]: Wei Dai, untitled b-money description, 1998, accessed via [https://web.archive.org/web/20090415130807/https://www.weidai.com/bmoney.txt.]

[225]: Dai, untitled b-money description.

[226]: Wei Dai, "Re: alternative b-money creation," originally sent to the Cypherpunks mailing list, December 11, 1998, accessed via: [https://cypherpunks.venona.com/date/1998/12/msg00448.html.]

[227]: Wei Dai, comment in the discussion thread "AALWA: Ask any LessWronger anything," LessWrong, 2014, [https://www.lesswrong.com/posts/YdfpDyRpNyypivgdu/aalwa-ask-any-lesswronger-anything.]

[228]: Dai, comment.

[229]: Eric Hughes, "Kid Gloves or Megaphones," originally sent to the Cypherpunks mailing list, March 14, 1996, accessed via: [https://cypherpunks.venona.com/date/1996/03/msg00932.html.]

[230]: Hughes, "Kid Gloves."

[231]: Austin Hill, draft document from 2005 shared with author, March 30, 2022.

[232]: Ori Brafman and Rod A. Beckstrom, The Starfish and the Spider: The Unstoppable Power of Leaderless Organizations , 22--27.

[233]: Damien Cave, "The Mojo solution," Salon, October 9, 2000, [https://www.salon.com/2000/10/09/mojo_nation/.]

[234]: As a mildly interesting detail, most Mojo transactions were actually only recorded between two peers at first, each building up credit or debit with the other peer, to only settle the debt using an actual Mojo token when a certain threshold was met.

[235]: Cave, "The Mojo solution."

[236]: Daniel A. Nagy, comments in response to "The Mojo Nation Story---Part 2," Financial Cryptography, October 12, 2005, <https://www.financialcryptography.com/mt/archives/000572.html>

[237]: Bryce Wilcox-O'Hearn, "Experiences Deploying A Large-Scale Emergent Network," Peer-to-Peer Systems : 104--110.

[238]: Wilcox-O'Hearn, "Large-Scale Emergent Network."

[239]: Liang Wang, "BitTorrent Mainline DHT Measurement," MLDHT, 2013, accessed via: [https://www.cl.cam.ac.uk/...525/MLDHT/.]

[240]: BitTorrent, "BitTorrent and µTorrent Software Surpass 150 Million User Milestone; Announce New Consumer Electronics Partnerships," BitTorrent.com, January 9, 2012, accessed via [https://web.archive.org/web/20140326102305/http://www.bittorrent.com/intl/es/company/about/ces_2012_150m_users.]

[241]: Hendrik Schulze and Klaus Mochalski, "Internet Study 2008/2009," ipoque .