# Fiat in de 21ste eeuw

Voor het grootste deel van zijn leven voelde Friedrich Hayek dat zijn ideeën waren gemarginaliseerd. Spontane orde van onderaf moest het onderspit delven voor de economische staatsinterventie van John Maynard Keynes, die van bovenaf functioneert. In plaats van rentetarieven die bepaald werden door de markt, hadden centrale banken het goud vaarwel gezegd om het manipuleren van de rente nog gemakkelijker te maken. En geld, verre van gedenationaliseerd, was een strategisch instrument geworden op het globale geopolitieke schaakbord.

Weinig schaakspelers waren zo sluw als de Amerikaanse president Richard Nixon.

Door in 1971 effectief het Bretton Woodssysteem te ontbinden, had Nixon een liquiditeitscrisis weten te voorkomen toen landen hun dollarreserves opnieuw naar goud begonnen om te zetten. Maar dat zou natuurlijk uit zichzelf de problemen die veroorzaakt werden door het begrotingstekort van Amerika niet oplossen. Het vertrouwen in de dollar begon te dalen nu die niet langer werd gedekt door edelmetaal, en het begon erop te lijken dat de Verenigde Staten hun dominante positie in het internationale financiële systeem mogelijks zouden verliezen.

Nixon zou een oplossing vinden tijdens een wereldwijde oliecrisis.

In 1973 riepen olieproducerende Arabische landen, verenigd in de Organisatie van de Olie-Exporterende Landen (OPEC), bestaande uit meerdere overheden, een olie-embargo uit over landen die Israël steunden tijdens de Oktoberoorlog tussen de joodse staat en Egypte. De landen voor wie de handel verboden werd, waren Amerika, het Verenigd Koninkrijk en vele andere westerse landen. Het veroorzaakte een scherpe stijging in de olieprijs, met verstrekkende negatieve gevolgen voor de gehele wereldeconomie.

Als reactie hierop werd in 1973 de nieuwbenoemde Amerikaanse minister van Financiën, William Simon, naar Saudi-Arabië gestuurd, een lidstaat van de OPEC. Zijn taak was om olie als economisch wapen te neutraliseren, het vestigen van een stevige greep van de Sovjet-Unie in de regio te voorkomen en bovendien een oplossing voor de dollarcrisis te vinden; al met al geen gemakkelijke klus. Maar Simon ging de onderhandelingen in met een sterk drukkingsmiddel: het Amerikaanse leger.

De overeenkomst die Simon wist te sluiten met de Saoedische koninklijke familie zou het geopolitieke landschap voor de komende decennia vormgeven. Kort samengevat, zouden Saudi-Arabië en andere OPEC-landen hun olie exclusief voor Amerikaanse dollars verkopen, ongeacht welk land petroleum wilde kopen. Landen die olie exporteren zouden alleen de Amerikaanse valuta accepteren als betaling. Deze dollars zouden op hun beurt grotendeels gebruikt worden om Amerikaanse staatsobligaties te kopen en zo de Amerikaanse uitgaven te financieren. In ruil hiervoor zou het Amerikaanse leger hulp en uitrustingen verstrekken om de Saoedische olievelden te beschermen en de veiligheid van de koninklijke familie te waarborgen.[^256]

Deze deal bezorgde de Verenigde Staten een aanhoudende vraag naar hun dollars: iedereen die olie wilde kopen van OPEC-landen, die samen meer dan twee derde van de wereldreserves controleerden,[^257] moest eerst Amerikaanse dollars verkrijgen. Gezien het centrale belang van olie in de wereldeconomie, garandeerde dit dat de dollar in feite de wereldreservevaluta bleef. Deze onofficiële overeenkomst zou bekend komen te staan als het petrodollarsysteem (kort nadat deze regeling was ingevoerd, op 30 december 1974, werd het privébezit van goud opnieuw gelegaliseerd in de Verenigde Staten).

Het petrodollarsysteem was een geweldige overeenkomst voor de Amerikanen - maar niet zo geweldig voor het merendeel van de rest van de wereld. Om dollars te verkrijgen om olie te kunnen kopen, moesten de meeste landen goederen of diensten naar de VS exporteren, of dollars kopen op de buitenlandse valutamarkten ... terwijl de VS simpelweg dollars konden drukken, zonder zich zorgen te maken over een gouddekkingverhouding. Als en wanneer ze dat deden, betaalden andere landen echt de prijs, omdat de waarde van hun dollarreserves daalde.

Het petrodollarsysteem implementeerde in feite het Cantillon-effect op wereldwijde schaal, met de Amerikaanse regering en Amerikaanse financiële instellingen in het hart van dit monetaire paradigma.[^258]

## De Hayekiaanse heropleving

Intussen had stagflatie de economische wereld tot wanorde gebracht, aangezien de Keynesiaanse assumptie dat inflatie werkloosheid zou tegengaan, onjuist bleek. Als het gebruik van inflatie om de economie te stimuleren verslavend was, zoals Hayek had betoogd, waren de positieve effecten van deze drug nu uitgewerkt en ondervond de samenleving de pijnlijke ontwenningsverschijnselen. Na een bestuur van veertig jaar bevond het Keynesianisme zich in een existentiële crisis.

Het was in deze context dat Hayeks ideeën werden herontdekt om de basis te vormen voor een heropleving van klassieke economische ideeën.

Deze *neoliberale* herleving begon in het Verenigd Koninkrijk, waar Margaret Thatcher in 1975 de leiding nam over de Conservatieve Partij. Nadat ze als student *The Road to Serfdom* had gelezen, werd ze een aanhanger van het werk van Hayek en een sterke voorstander van vrije markten en een kleine overheid. Thatcher verwierp de gewoonte van de Conservatieve Partij om een compromis te sluiten over deze idealen om de centristische stem te winnen, en koos in plaats daarvan voor de harde aanpak. Op een gegeven moment, tijdens een vergadering met de onderzoeksafdeling van haar partij, haalde ze op beroemde wijze zelfs Hayeks boek *The Constitution of Liberty* uit haar tas en sloeg het neer op tafel. 'Dit is waar we in geloven!' verklaarde ze.[^259]

Het plan had succes. De Iron Lady, zoals Thatcher vaak werd genoemd, werd in 1979 verkozen tot de eerste vrouwelijke premier van het Verenigd Koninkrijk. Eenmaal in functie voerde ze haar plannen uit om de omvang van de overheid te beperken en de vrije markt meer ruimte te geven. Ze deed dit door belastingen te verlagen, regulerende obstakels weg te nemen en een nationale golf van privatisering door staatsbedrijven te verkopen. Dit beleid leverde haar in de daaropvolgende jaren meerdere herverkiezingen op. Uiteindelijk werd Thatcher hierdoor de langstzittende Britse premier van de twintigste eeuw.

Het succes van Thatcher in het VK diende als inspiratie voor een geestverwant in de Verenigde Staten. De Republikeinse kandidaat voor de presidentsverkiezingen van 1980, Ronald Reagan, beloofde eveneens een vermindering van de overheidsuitgaven. Zijn campagneslogan, 'We kunnen de overheid van onze ruggen halen, uit onze zakken', sloeg aan bij de Amerikaanse kiezers. De voormalige filmster versloeg de zittende president Jimmy Carter met een grandioze overwinning.

Als president verlaagde Reagan inderdaad de belastingen en zette hij de sociale programma's stop. Om zijn economische beleid verder te ontwikkelen, dat later bekend kwam te staan als 'Reaganomics', creëerde de president een nieuwe Economische Beleidsadviesraad. Hierin benoemde hij economen die een sterke voorkeur hadden voor de vrije markt, waaronder opmerkelijk Milton Friedman, een vroege bewonderaar van Hayek.[^260]

Decennia eerder, in 1947, nodigde Hayek Friedman, die net was begonnen als economieprofessor aan de Universiteit van Chicago, uit voor een tiendaagse conferentie in Zwitserland. Ongeveer 60 toonaangevende voorstanders van de vrije markt, bekende libertaire denkers en andere invloedrijke vrijdenkende personen, hadden hier tien dagen besteed aan het bespreken hoe een vrije samenleving kan worden behouden en hoe te voorkomen dat het Westen zou terugvallen naar fascisme of afglijden naar socialisme. Voor Hayek vertegenwoordigde de topbijeenkomst (die een jaarlijks terugkerend evenement zou worden) 'de wedergeboorte van een liberale beweging in Europa'.[^261]

Friedman had zich in de decennia na die reis naar Zwitserland weten te vestigen als een van de meest invloedrijke economen van de twintigste eeuw. Net als Hayek verwierp Friedman de destijds dominante Keynesiaanse doctrine van staatsinterventie en overheidsuitgaven. Naarmate hij beroemder werd, werd hij in veel opzichten een meer effectief voorvechter van Hayeks ideeën over markten en het prijssysteem dan Hayek zelf ooit was geweest.

Echter, op bepaalde punten zouden Friedmans gedachten ook afwijken van de inzichten van Hayek. Zijn bijdragen op het gebied van economie hielpen bij het vormgeven van een aparte denkrichting die bekend staat als de 'Chicago School of Economics'.

De Chicago School verschilt op een aantal belangrijke punten van de Oostenrijkse School.

Een fundamenteel verschil was de methodologie van de Chicago School. Waar Carl Menger de basis had gelegd voor de Oostenrijkse school van economie in praxeologie, de methode gebaseerd op logica, redenering en basisprincipes, koos de Chicago School voor een meer traditioneel empirisme, waarin hypotheses worden geformuleerd en getoetst aan de hand van reële wereldgegevens en statistieken.

Het tweede grote verschil was bijna net zo fundamenteel als het eerste: de Chicago School was het niet eens met de Oostenrijkers over het onderwerp geld.

## Monetarisme

Hoewel Friedman een grote voorvechter was van Hayeks ideeën over markt en prijzen, omvatte dit niet Hayeks perspectief op de stadia van productie, of hoe rentetarieven en het intertemporele prijssysteem de toewijzing van middelen door de tijd heen konden sturen. Friedman was zeker geen voorstander van Hayeks voorstel om geld te denationaliseren. In plaats daarvan pleitte Friedman voor strikte overheidsregulatie van geld.

Friedman heeft, samen met econome Anna Schwartz, een onderzoek uitgevoerd naar economische hoogte- en dieptepunten in de Verenigde Staten. [^262] Hun studie bestreek de periode vanaf het midden van de negentiende eeuw tot het midden van de twintigste eeuw, met extra aandacht voor de Grote Depressie van de jaren 1930. Friedman en Schwartz kwamen tot de conclusie dat elke economische recessie voorafging aan een afname van de geldvoorraad, of op z'n minst een vertraging in haar groei.

Volgens economen, inclusief Hayek, kan de geldvoorraad het duidelijkst stijgen en dalen door het wijdverspreide gebruik van fractioneel bankieren. Telkens wanneer iemand bij een fractionele reservebank een lening afsluit, brengt de bank nieuw geld in omloop (als krediet), wat de geldvoorraad vergroot. En vice versa: elke keer dat iemand een lening terugbetaalt bij een fractionele reservebank, wordt er geld uit de omloop genomen, waardoor de geldvoorraad afneemt.

Friedman en Schwartz legden uit dat toen de Federal Reserve de rentetarieven in 1928 had verhoogd, de bereidheid van mensen om leningen af te sluiten vanzelfsprekend verminderde. Maar naarmate oude leningen werden afbetaald en geld daardoor uit de omloop werd gehaald, terwijl er niet zoveel nieuwe leningen werden uitgegeven om dit te compenseren, nam de totale geldvoorraad af. Dit zette, zoals Hayek ook had uitgelegd, een deflatoire schuldenspiraal in gang.

Maar Friedman nam Hayeks uitleg van hoe rentemanipulatie deze deflatoire schuldenspiraal had ingeleid niet over, en hij was vooral het niet eens met Hayeks voorstel om deze schuldenspiraal zijn gang te laten gaan. In plaats daarvan stelde hij een oplossing voor die veel meer leek op wat Irving Fisher en de stabilisatoren in de jaren 1920 hadden voorgesteld (maar waarvan hij geloofde dat het niet goed was uitgevoerd in de jaren 1930).

De econoom van de Chicago School redeneerde dat de geldvoorraad op een gestage en voorspelbare manier zou moeten groeien, zodat de economie meegroeit en het geaggregeerde prijsniveau stabiel kan blijven of misschien heel langzaam kan stijgen. Zolang de prijzen stabiel werden gehouden, kon de markt voor de rest zorgen. *Monetarisme*, zoals deze monetaire doctrine werd genoemd, werd een fundamenteel onderdeel van de Chicago School van Economie.

De voorgestelde hulpmiddelen om de geldvoorraad te beheren waren dezelfde als die van Fischer: de consumentenprijsindex zou fungeren als de maatstaf voor stabiliteit en rentetarieven konden worden gereguleerd om de geldvoorraad te verhogen of te verlagen. Als de prijzen zouden dalen, wilden monetaristen dat centrale banken de rentetarieven zouden verlagen om zo de kredietverlening aan te wakkeren, uitgaven te stimuleren, en opwaartse druk op de prijzen te zetten. Als de prijzen te snel zouden stijgen, wilden monetaristen dat centrale banken de rentetarieven zouden verhogen. Als de prijzen stabiel bleven, zou de hoeveelheid geld in de economie gestaag groeien samen met de economie zelf, en was de rente precies goed ingesteld.

Monetaristen waren het grotendeels oneens met Keynesianen over de rol van de overheid. Zij waren niet van mening dat regeringen lage rentetarieven zouden moeten gebruiken om de uitgaven te verhogen, maar in plaats daarvan geloofden zij dat overheidsuitgaven uitsluitend gefinancierd zouden moeten worden door middel van fiscaal beleid, met andere woorden, belastingen. Hoewel monetaristen het erover eens waren dat geaggregeerde uitgaven essentieel waren om een economische neergang te vermijden, beweerden zij dat de particuliere sector de uitgaven even goed kon doen, en in feite de uitgaven zou doen als mensen goedkoop genoeg geld konden lenen. Op een bepaalde manier combineerden monetaristen ideeën van zowel Oostenrijkers als Keynesianen in een nieuwe benadering.

De theorie overtuigde Hayek echter niet, om veel van dezelfde redenen dat de stabilisatoren hem voorheen nooit overtuigd hadden: hij geloofde dat het manipuleren van rentetarieven de spontane orde door de tijd heen verstoorde, en geloofde niet in het monetaristische idee van stabiliteit. (Eerder in zijn carrière had hij aangehaald dat stabiele prijzen eigenlijk niet stabiel zijn, aangezien deflatie juist de natuurlijke staat is van een gezonde economie, terwijl hij later in zijn carrière toevoegde dat de vrije markt, en niet een centraal geleid overheidscomité, zou moeten bepalen wat stabiel is.)

Hoewel Hayeks ideeën over markten en het prijssysteem in de jaren tachtig een heropleving genoten, bleven zijn ideeën over geld grotendeels onopgemerkt. Geld bleef onder staatscontrole en zelfs de nieuwe stroom vrije markteconomen in Chicago geloofde niet dat hier verandering in moest komen.

## Spaargeld en leningen

In 1987 benoemde president Reagan een ander lid van zijn Economische Beleidsadviesraad tot de nieuwe voorzitter van de Federal Reserve, met name Alan Greenspan. Net zoals Friedman was ook Greenspan een fervent monetarist. Toen de Amerikaanse Senaat kort daarna de nominatie bevestigde, stond de monetaire theorie van de Chicago School op het punt om voor het eerst in de praktijk te worden gebracht.

Nauwelijks in zijn nieuwe functie benoemd, werd Greenspan vrijwel meteen geconfronteerd met de ergste bankencrisis sinds 1929. In een economie met zowel hoge inflatie als hoge rentetarieven om de inflatie te dempen, hadden de spaarbanken het moeilijk. Veel van deze samenwerkende bankachtige financiële instellingen, die langlopende leningen zoals hypotheken verstrekten met een vaste rente, hadden nu moeite om voldoende geld aan te trekken om aan alle opnameverzoeken van spaarders te voldoen. Uiteindelijk dwong dit veel spaar- en leenverenigingen om in gebreke te blijven en faillissement aan te vragen.

Toen de bezorgdheid bij economen en beleidsmakers toenam dat deze faillissementen een domino-effect op de Amerikaanse economie konden hebben, verlaagde Greenspan in 1989 de rentetarieven. Hierdoor werd het goedkoper voor de spaar- en leenverenigingen om geld te verkrijgen, terwijl tegelijkertijd de eerste tekenen van een economische neergang werden tegengegaan en beheerst.

Desondanks moest de Federal Savings and Loan Insurance Corporation (FSLIC) uiteindelijk ingrijpen om de mislopende sector te redden, waarbij spaarders in totaal 125 miljard dollar werd terugbetaald. De FSLIC, alsook de Federal Deposit Insurance Corporation (FDIC), waren tijdens de crisis van de jaren 1930 (Great Depression) in het leven geroepen om het vertrouwen van het volk in de banken te herstellen: deze overheidsinstellingen garandeerden dat bankklanten hun deposito's (tot een zekere limiet) terugbetaald kregen in geval van een bankfaillissement. Aangezien de Federal Reserve in haar rol als kredietverstrekker in uiterste nood tijdens de economische crisis van de jaren 1930 had gefaald, gaf het deposanten een tweede reden om zich geen zorgen te maken over fractioneel reservebankieren.

Het klopt dat de reddingsacties de omvang van de spaar- en leencrisis beperkten en veel persoonlijke drama's voorkwamen. Maar dit ging gepaard met aanzienlijke kosten: de 125 miljard dollar moest worden betaald door de overheid, dus in werkelijkheid door de Amerikaanse belastingbetaler. Zelfs de Amerikanen die zorgvuldig en voorzichtig waren met hun spaargeld, moesten indirect een deel van de last dragen, terwijl de spaar- en leningverenigingen en hun klanten er relatief makkelijk vanaf kwamen.

Aan het begin van zijn carrière had Hayek al zijn zorgen uitgesproken over het morele risico dat centrale banken in de economie introduceerden. Dit werd met de FDIC en FSLIC alleen maar explicieter. Tijdens de spaar- en leencrisis werd het duidelijk dat financiële instellingen grote risico's konden nemen; de Amerikaanse overheid zou de rekening betalen als het fout liep.

## Dot-Com

Ongeveer tien jaar na de crisis van de spaar- en leenverenigingen, tegen het einde van de jaren 1990, deden de aandeelmarkten het enorm goed.

Dit kwam deels door een algemeen gevoel van optimisme in de westerse wereld: eerder in dat decennium was de Sovjet-Unie eindelijk ingestort. Hoewel Ludwig von Mises al in 1973 overleden was, leek zijn economische rekenprobleem eindelijk bevestigd te zijn. Nu de dwaasheid van centrale planning eindelijk bevestigd leek, omarmden voormalige Sovjetlanden de vrije markteconomie.

Bovenop dit alles werden de Verenigde Staten overmand door een enorme tech-euforie, wat het duidelijkst weerspiegeld werd op de Nasdaq -aandelenbeurs. Door bedrijven uit Silicon Valley, zoals Netscape, die openbaar werden met waarderingen van meerdere miljarden dollars, schoten technologieaandelen over de hele linie omhoog. Zelfs internetstart-ups, die vaak niet meer dan een domeinnaam hadden, werden in sommige gevallen gewaardeerd op tientallen, of zelfs honderden, miljoenen dollars. Het internet was de toekomst en iedereen wilde er een stuk van hebben.

Maar studenten van Hayeks werk hadden reden om te denken dat er ook iets anders aan de hand was. De Federal Reserve onder Greenspan had namelijk in de nasleep van de spaar- en leencrisis de rentetarieven verlaagd naar de laagste niveaus sinds de jaren 1960. Net zoals in de jaren 1920, was geld goedkoop en mensen waren maar al te blij om te lenen en te investeren in de aandelenmarkt. Kunstmatig lage rentetarieven waren de drijvende kracht achter de economische boom.

En, deze leerlingen van Hayek zouden weten dat de economische realiteit vroeg of laat een inhaalslag ging maken. En dat deed ze uiteindelijk. Net voor de eeuwwisseling, besloot Greenspan om de rentetarieven te verhogen, en plofte de dot-com-bubbel, en de Nasdaq stortte naar beneden. De razernij was voorbij.

Als Hayek nog in leven was geweest, dan had hij waarschijnlijk betoogd dat de beste weg voorwaarts zou zijn om op de tanden te bijten en de markt te laten normaliseren. De economie zou door een pijnlijke recessie moeten gaan naarmate onrendabele bedrijven zouden sneuvelen, en middelen langzaam maar zeker herverdeeld konden worden naar meer duurzame inspanningen.

Maar Greenspan had een ander idee. De monetarist was vastbesloten een deflatoire schuldenspiraal te voorkomen, dus besloot hij opnieuw de rente te verlagen. Deze keer liet hij ze ver onder het niveau van de jaren 1990 zakken, waardoor krediet in de vroege jaren 2000 zelfs goedkoper was dan het tijdens de opmars van de dot-com-bubbel was.

Op het eerste zicht leek het te werken. In de daaropvolgende jaren begon de aandelenmarkt langzaam te herstellen. Voor veel economische commentatoren diende dit als een bevestiging dat het monetarisme naar behoren had gewerkt. Greenspan had de Amerikaanse economie met minimale schade door de dot-com-crash geloodst, wat hem zelfs een nieuwe bijnaam opleverde: 'de Maestro'.

Eén sector in het bijzonder beleefde in het midden van de jaren 2000 niets minder dan een volledige economische opleving: de huizenmarkt.

## 'Te groot om te falen'

Deze bloei in de huizenmarkt baarde Greenspan, met het oog op monetaire stabiliteit, nauwelijks zorgen. Hoewel sommige afgeleide prijzen, zoals de kosten van woninghuur en onderhoud, in acht werden genomen, waren de werkelijke huizenprijzen zelf niet opgenomen in de CPI (Consumentenprijsindex); ze waren in 1983 uit de index gehaald. Vastgoed wordt sindsdien grotendeels beschouwd als een vorm van investering, hetgeen bijzonder handig was omdat politici in die tijd de inflatiecijfers wilden verlagen.[^263]

Desalniettemin kon de bloei in grote mate worden toegeschreven aan het beleid van Greenspan. Lage rentetarieven hadden in het begin van de jaren 2000 de hypotheekrente naar ongekende dieptepunten gestuurd, en de Amerikaanse woningmarkt floreerde als direct gevolg hiervan. De prijs van een nieuw huis steeg jaar na jaar, aangezien iedereen leek te willen profiteren van de kans om goedkoop in te stappen.

En er was nog een andere, verborgen reden voor deze bloei. Financiële instellingen hadden, voornamelijk sinds de late jaren 1980, complexe soorten van hypotheekgedekte effecten gebruikt, namelijk gedekte schuldobligaties. Dit stelde hen in staat om hypotheekschulden in stukken te hakken en door te verkopen; in plaats van de bank die het uitgaf, waren de hypotheekschulden steeds meer eigendom van investeerders, waardoor ook andere financiële instellingen zoals banken, verzekeringsmaatschappijen en pensioenfondsen betrokken raakten.

Het probleem was echter dat elke hypotheekschuld kon worden voorgesteld als een praktisch risicovrij activum. Daarom waren sommige financiële instellingen die hypotheken verstrekten maar al te graag bereid nieuwe hypotheken te verstrekken aan vrijwel iedereen die er een aanvroeg. Controles op inkomen, baanzekerheid of kredietwaardigheid werden grotendeels over het hoofd gezien. De risico's die inherent waren aan deze hypotheken werden verhuld om ze opnieuw te kunnen verkopen.

Maar de risico's konden niet eeuwig verborgen blijven. Midden jaren 2000 begon Alan Greenspan, de toenmalige voorzitter van de Federal Reserve, de rente weer te verhogen, en zijn opvolger in 2006, Ben Bernanke, volgde zijn voorbeeld. Nogmaals voor degenen die het werk van Hayek hadden bestudeerd: wat er vervolgens gebeurde kwam niet als een verrassing.

Toen het duurder werd om te lenen, begon de huizenmarkt op te drogen, terwijl tegelijkertijd steeds meer Amerikanen in gebreke bleven bij de hypotheken die hen zo vrij waren verstrekt. Toen de huizenprijzen in de Verenigde Staten begonnen te dalen, ontdekten degenen die hadden geïnvesteerd in hypotheekgebonden effecten dat ze lang niet zo veilig waren als geadverteerd, waardoor sommigen van hen in geldnood kwamen om hun eigen schulden af te betalen.

Toen wanbetalingen (leningen die niet kunnen worden terugbetaald) doorheen de Amerikaanse financiële sector begonnen te verspreiden als een epidemie en steeds grotere bedrijven beïnvloedden, werd de omvang van de crisis steeds duidelijker. Toen de financiële reus Lehman Brothers in september 2008 het grootste bedrijf werd dat ooit faillissement indiende in de geschiedenis van de Verenigde Staten, wisten financiële professionals, beleidsmakers en iedereen die oplette dat verdere escalatie tot een volledige economische neerval kon leiden.

Toen het erop leek dat de grote verzekeringsmaatschappij AIG wellicht de volgende zou zijn om te bezwijken, heeft de Federal Reserve, ondersteund door een nieuwe noodwet, een werkelijk opmerkelijke stap genomen. De centrale bank verklaarde de verzekeraar 'te groot om te falen', en samen met de Amerikaanse schatkist redde ze AIG door middel van een injectie van \$ 68 miljard (plus nog eens \$ 112 miljard aan garanties).

Dit luidde een nieuw beleidstijdperk in, zowel in de VS als daarbuiten, omdat de crisis internationaal om zich heen greep. In de daaropvolgende weken coördineerde de Federal Reserve nogmaals met het Amerikaanse Ministerie van Financiën om het voor \$ 405 miljard aan noodlijdende activa te laten kopen, terwijl aan de andere kant van de Atlantische Oceaan de Britse minister van Financiën, Alistair Darling, ook een noodmaatregel uitrolde in de vorm van een bankreddingsplan ter waarde van £ 137 miljard (\$ 230 miljard). Vergelijkbare maatregelen werden in andere Europese landen genomen.[^264]

Een onmiddellijke financiële instorting werd afgewend, maar alleen omdat grote delen van de financiële sector werden gered door openbare instellingen en de creatie van enorme hoeveelheden nieuw geld uit het niets; het morele risico stond nu volop in de schijnwerpers.

## Een nieuwe wereld

De overheidsinterventies zouden zich niet alleen tot reddingsoperaties beperken.

Midden in een crisis had de Federal Reserve opnieuw de rente verlaagd met als doel deflatie te vermijden en de economie weer op de rails te krijgen, deze keer tot bijna nul procent: geld lenen werd bijna gratis. Maar het leek weinig effect te hebben.

In november 2008 kondigde de Federal Reserve daarom een grootschalig programma aan ter aankoop van activa, genaamd Quantitative Easing (Kwantitatieve versoepeling). De Fed zou nog eens voor \$ 600 miljard aan hypotheekgedekte effecten opkopen met vers gecreëerde dollars, en breidde dit kort daarna uit naar het opkopen van bank- en overheidsschuld. De centrale bank kreeg al snel voor meer dan \$ 2000 miljard van deze drie activa in handen, waardoor de totale waarde van haar balans bijna verdrievoudigde.

Quantitative Easing (QE) stelt centrale banken in staat risicovolle activa van de markt te halen, maar het hoofddoel van deze programma's is om het geldaanbod te vergroten en deflatie tegen te gaan wanneer traditionele instrumenten de klus niet klaren. Met andere woorden, QE kan helpen om inflatie te stimuleren wanneer de rentetarieven tot nul (of bijna nul) zijn gedaald, door wanhopig duizenden miljarden rechtstreeks in de economie te pompen; een voorbeeld dat al snel door andere centrale banken over de hele wereld werd gevolgd.

En het *was* wanhopig. Volgens de toonaangevende theorie van Bernanke over geld en rente, zou QE zelfs helemaal geen inflatie moeten stimuleren als een rentetarief van nul procent dat al niet deed. Toch bleek het enigszins te werken. Zoals de voorzitter van de Fed grappend zei: 'Het probleem met QE is dat het in de praktijk goed werkt, maar niet in theorie.'[^265]

Toch betraden de centrale banken met de invoering van QE bijna volledig onbekend terrein. Niemand die leidinggaf aan deze opkoopprogramma's wist precies wat de effecten zouden zijn, of hoe lang het zou duren voordat dergelijke effecten zichtbaar werden. Sterker nog, de financiële crisis van 2008 en de nasleep daarvan markeerden het begin van een nieuwe en onzekere wereld van geld en financiën.

Oorspronkelijk opgericht als een leningverstrekker in absolute nood, ongeveer een eeuw geleden, was de Federal Reserve al bijna even lang de rentevoeten aan het manipuleren. Nu begon het ook winnaars en verliezers in de markt te kiezen met reddingspakketten en begon het zelfs middelen toe te wijzen doorheen de vermogensmarkten via QE. Het mandaat van de centrale bank was na verloop van tijd uitgebreid om taken te omvatten die even goed de verantwoordelijkheden zouden kunnen beschrijven die doorgaans aan centrale planners van de Sovjet-Unie werden toegeschreven.

Ondertussen bood de crisis --- net als de crisis van de jaren 1930 --- een klimaat waarin Keynesiaanse ideeën een heropleving konden maken: een groep economen, bekend als de 'Nieuwe Keynesianen'[^266], drongen er bij overheden wereldwijd op aan om het begrotingstekort te verhogen om zo nationale economieën te stimuleren. Toen IMF-directeur Dominique Strauss-Kahn in 2008 deze 'Keynesiaanse heropleving' aanbeveelde, stemden wereldleiders, onder wie de Amerikaanse president George W. Bush en de Britse premier Gordon Brown, in met het steunen van de plannen. Financiële stimuleringspakketten werden al snel over de hele wereld uitgerold.

Het grootste deel van Hayeks leven waren zijn ideeën gemarginaliseerd. Hayek had al in de jaren 1920 kritiek geuit op de rol van centrale banken, en sinds de jaren 1930 waarschuwde hij dat Keynesiaanse maatregelen weinig deden buiten het verlengen van onhoudbare economische oplevingen. Toch leken de zaken in de loop van de tijd alleen maar erger te worden. Geld was geëvolueerd tot een geopolitiek schaakstuk voor nationalisten, een machtsmiddel voor economische planners van centrale banken en vooral, een bron van economische onrust --- dat op zijn beurt de heropleving van de Keynesiaanse doctrine bevorderde.

Het monetaire systeem was in de vroege eenentwintigste eeuw zo ver verwijderd van Hayeks ideaal als maar mogelijk kon zijn, en er was geen oplossing in zicht.

Tenzij je toevallig geabonneerd was op een technologiemailinglijst in een bijna vergeten hoekje van het internet...

[^256]: Andrea Wong, 'The Untold Story Behind Saudi Arabia's 41-Year U.S. Debt Secret', Bloomberg, May 31, 2016, [https://www.bloomberg.com/news/features/2016-05-30/the-untold-story-behind-saudi-arabia-s-41-year-u-s-debt-secret#xj4y7vzkg.]

[^257]: Energy Exploration & Exploitation, 'World Oil Reserves 1948--2001: Annual Statistics and Analysis', Energy Exploration & Exploitation, vol. 19, no. 2 & 3 , <https://journals.sagepub.com/doi/pdf/10.1260/0144598011492561>

[^258]: Alex Gladstein, 'Uncovering The Hidden Costs of the Petrodollar', Bitcoin Magazine, April 28, 2021, <https://bitcoinmagazine.com/culture/the-hidden-costs-of-the-petrodollar>

[^259]: Wapshott, Keynes Hayek, 258--59.

[^260]: Wapshott, Keynes Hayek, 261.

[^261]: Wapshott, Keynes Hayek, 211--214.

[^262]: Milton Friedman and Anna Schwartz, A Monetary History of the United States .

[^263]: The Economist, 'Why don't rising house prices count towards inflation?' The Economist, July 29, 2021, [https://www.economist.com/the-economist-explains/2021/07/29/why-dont-rising-house-prices-count-towards-inflation.]

[^264]: US Department of the Treasury, 'Troubled Asset Relief Program ', available via: <https://home.treasury.gov/data/troubled-asset-relief-program>; Federico Mor, Bank Rescues of 2007-09: Outcomes and Cost, House of Commons Research Briefing, October 8, 2018, available via: <https://commonslibrary.parliament.uk/research-briefings/sn05748/>

[^265]: Rupal Patel and Jack Meaning, Can't We Just Print More Money? Economics in Ten Simple Questions, The Bank of England , 238.

[^266]: New Keynesians integrated more of the neoclassical ideas on free markets, but also assumed more potential market failures, in particular due to an inability of some prices to adjust to new circumstances quickly, justifying government intervention. This most notably includes the price of labor due to psychological factors.